### ISSUE TITLE
Test Failure: com.ibm.ws.request.timing.fat.HungRequestTiming.testParallelMultipleRequests

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#10018]
RTC 270036

```
testParallelMultipleRequests:junit.framework.AssertionFailedError: 2019-11-21-05:17:49:625 The server configuration was successfully updated message was not found!
at com.ibm.ws.request.timing.fat.HungRequestTiming.testParallelMultipleRequests(HungRequestTiming.java:93)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:193)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
```

**Comment by lamkavan** [comment]
Issue:
During the execution of testParalleMultipleRequests in the HungRequestTiming test class there is a failure with not finding the "successfully updated server configuration" log message in messages.log. After inspecting the log files from failed builds it is true that the the "successfully updated server configuration" log message is not in messages.log which is why the test case fails.

Cause:
The reason why the "successfully updated server configuration" log message is not logged into messages.log is because the message is only logged when the configuration trying to be updated to has functional differences to the configuration currently used. The order of the test methods in HungRequestTiming is not consistent and may vary. So, in certain situations the previous test may load configuration 1 and if testParallelMultipleRequests then tries to load configuration 1 there will be no "successfully updated server configuration" log message logged into messages.log. Instead the following is logged... "CWWKG0018I: The server configuration was not updated. No functional changes were detected".

Fix:
Before the execution of each test ensure that we load the original server configuration. Doing so means the order of execution for the tests no longer matters and we are guaranteed to always be trying to update to a unique server configuration. No further action necessary. PR is here  https://github.com/OpenLiberty/open-liberty/pull/10190
