### ISSUE TITLE
mpJWT Performance Issue

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#11075]
Last year a JWK cache was added to help performance when getting a JWK from a file (that never changes). https://github.com/OpenLiberty/open-liberty/commit/1365ebc673461c12a82c91a6369594eb192b995f#diff-13d391b07e858b6dee71d5a70cae165c
 
It looks like the problem is back in 20.0.0.3 (24% of the time spent in this test is getting the PublicKey from the JWK - again, from a file that never changes). In 20.0.0.2, this was ~0.
 
```
  Parent      0   0.00  24.00           0        1998    J:com/ibm/ws/security/jwt/internal/ConsumerUtil.getJwksKey(Lcom/ibm/ws/security/jwt/config/JwtConsumerConfig;Lorg/jose4j/jwt/consumer/JwtContext;Ljava/util/Map;)Ljava/security/Key;
 
    Self      0   0.00  24.00           0        1998    J:com/ibm/ws/security/common/jwk/impl/JwKRetriever.getPublicKeyFromJwk(Ljava/lang/String;Ljava/lang/String;Z)Ljava/security/PublicKey;
 
   Child      0   0.00  24.00           0        1998    J:com/ibm/ws/security/common/jwk/impl/JwKRetriever.getPublicKeyFromJwk(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/security/PublicKey;
 ```
 
Anyway, guessing this issue is why: https://github.com/OpenLiberty/open-liberty/issues/9588.
 
It is possible my test is bad, waiting to hear back on that.

**Comment by jhanders34** [comment]
#regression

**Comment by samwatibm** [comment]
What is the actual performance impact to a customer?  Is this regression considered a stop ship issue for 20.0.0.3 (GM next Wednesday)?   Thanks.

**Comment by jhanders34** [comment]
I took a look at the trace that Joe sent me and things make a lot more sense now.

JwkRetriever.getPublicKeyFromFile pass in null to the getJwkFromJWKSet for the keyText.  Since it is null, jwkSet.getPublicKeyBySetIdAndKeyText(setId, keyText); is never called to look at the PEM cache.  Since PEM caching now is only done in the PEM cache and jwksBySetId is not set, jwkSet.getPublicKeyBySetId(setId); will always return null.
