### ISSUE TITLE
Openid connect client, social, and saml should have option to allow subject be recreated from sso cookie

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#11311]
After login with openid connect client, an sso cookie is created. The sso cookie contains a custom attribute, custom cache key, which prevents subject recreation from sso cookie if subject cache is gone. While custom cache key guarantee local subject is consistent with identity provider, the requirement is not always true, there is case you want subject to be recreated from SSO cookie directly. For example, when sso cookie is JWT, sso cookie has sufficient data to recreate subject. It is useful to recreate subject from sso cookie in container environment where pod restarted, or requests are distributed among multiple pods.
Currently, Liberty openid conenct client has an internal configuration property, includeCustomCacheKeyInSubject
We should make it public, or provide a similar configuration property to disable custom cache key in sso cookie.

**Comment by ezhou365** [comment]
[notes.txt](https://github.com/OpenLiberty/open-liberty/files/4331301/notes.txt)

**Comment by brutif** [comment]
maybe a good property name would be "reconstructSubjectFromJwtSsoCookie".

**Comment by brutif** [comment]
Discussing with CL, a similar attribute exists in saml that is already exposed, allowCustomCacheKey, and in the two socialLogin oidc configs, includeCustomCacheKeyInSubject.  Rather than try to do it in the jwtsso feature code, we should add the same new, overriding property value, reconstructSubjectFromJwtSsoCookie, to all 3 features, which has the effect of setting includeCustomCacheKeyInSubject or allowCustomCacheKey to false.

**Comment by c00crane** [comment]
Added myself to stay in the loop for testing.

**Comment by ayoho** [comment]
Should be done - just need to double check that everything is delivered.

**Comment by ezhou365** [comment]
completed with #12230
