### ISSUE TITLE
Allow for duplicated metatype due to transformed bundles

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11388]
Several of the bundles that are to be transformed between Java EE and Jakarta EE have metatype.  The transformed bundle will end up with duplicate metatype, and Liberty needs to be able to handle this, in schema generation and config processing, as well as in generated doc that is created from metatype/schema.  Also, do we care any more about things like WDT autosuggesting which feature to enable based on config?

**Comment by brenthdaniel** [comment]
For most utilities we don't have any issues. For many of them (like the schema generator) we load metatype files individually, so there are no duplications. For others, the feature conflicts prevent two versions of the metatype from being loaded at the same time. 

One place where we do have issues is in the feature checker. There seem to be some errors preventing the new features from being included in the baseline. It's hard to diagnose at the moment because there are several other unrelated issues with the feature checker that need to be fixed first.

**Comment by brenthdaniel** [comment]
I think it's safe to close this out. I don't think any work is needed here.
