### ISSUE TITLE
Need to investigate to get Vert.x into Liberty

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#11481]
In light of the two issues proposed by SmallRye, https://github.com/smallrye/smallrye-reactive-messaging/issues/79 and https://github.com/smallrye/smallrye-reactive-messaging/issues/423, we need to investigate the possibility to bring Vert.x to Open Liberty.

**Comment by Azquelt** [comment]
Subtasks:
* Read and understand the smallrye PR and see how it would impact
  * our ability to transfer thread context
  * the automatic tuning of the liberty thread pool
* Prototype consuming this change to the RM provider into Liberty

**Comment by Azquelt** [comment]
From what I can see in vert.x, there's no capability to exert any control over the thread pool or the threads used for vert.x workers, other than manually setting the pool size when creating a named worker pool, or setting the default pool size in the startup options.

If you were to dig into the vertx internals, you might be able to get the ThreadPoolExecutor out and start adjusting its values, but (a) it's still not using the main liberty thread pool and (b) you're now relying on internals which may change.

**Comment by Azquelt** [comment]
I have a prototype built from the PR branch running in liberty. I see the following behaviour:

* `@Blocking` methods run on vert.x worker threads, in a thread pool created by vert.x
* Liberty's thread context does not get propagated to vert.x worker threads (as expected)
* non `@Blocking` reactive messaging methods start by running on a liberty thread under the `WASReactiveStreamsEngine`
* Later non-`@Blocking` reactive messaging methods which run after a `@Blocking` method run on a vert.x event loop thread.
  * It looks like RM sends `@Blocking` tasks to run on vert.x worker threads. When they're complete, vert.x then sends subsequent tasks to run on the vert.x event loop, creating it if necessary.

The vert.x model of having a single event loop thread for non-blocking tasks and a worker thread pool for blocking tasks makes sense. If we were to avoid using vert.x we'd need to work out how this should happen within liberty.

It's also worth noting that vert.x will do things like warn you if one of your non-blocking tasks takes too long (with the assumption that this is because you have actually done a blocking operation in it).

**Comment by Azquelt** [comment]
Experimenting with mpConcurrencyPropagation-1.0, I can propagate the application context to a vert.x worker and event loop thread.

I think this is sufficient to show that we could propagate the application context using our internal APIs.

I'm not sure if there are any other contexts we should test.

**Comment by Azquelt** [comment]
Given that vert.x doesn't seem to have any flexibility over the creation of its thread pools, we're going to look at making changes to the smallrye reactive messaging provider to allow Blocking tasks to be run on an alternative thread pool without using vert.x.

**Comment by tevans78** [comment]
This work is now being done by Gordon and tracked in box: https://ibm.ent.box.com/folder/112406221779

**Comment by tevans78** [comment]
All initial investigation has been done. Closing.
