### ISSUE TITLE
Async implementation of MP rest client returns CompletionStage of Collection of HashMap but expected CompletionStage of Collection of a user defined type

### ISSUE THREAD

**Issue by manish2aug** [OpenLiberty/open-liberty#11534]
Please find the details below

IBM Liberty version: 19.0.0.4
Features: jaxrs-2.1, jsonp-1.1, jsonb-1.0, mpRestClient-1.2
Gist url: https://gist.github.com/manish2aug/2f5d1e317e2b5bffbec67c7ffbf403ba
Issue: At runtime client doesn't return completion stage of collection of user defined type

**Comment by andymc12** [comment]
This is very similar to issue #6521, but specific to `CompletionStage` return types.  The fix for #6521 intentionally did not handle CompletionStages in the JsonBProvider, assuming that the underlying implementation would handle it, but it doesn't.  

I have reproduced this issue and should have a fix shortly.
