### ISSUE TITLE
Return HTTP 400 instead of 500 when the Content-Type of a Jaxrs request contains an invalid charset.

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#11793]

**Comment by WhiteCat22** [comment]
attempted to fix in #11420 but needs more work.

**Comment by epj** [comment]
The 500 code is not coming from wc, and this was not changed by pr 11420.  Nowhere in the path from catching the BadRequestException that jaxrs throws to returning the result does wc change the code 500.   There is a secondary exception in sendError() caused by the invalid encoding, but wc is not changing the status code as a result.  I've tested that the status code is already 500 before the secondary exception.

**Comment by WhiteCat22** [comment]
Fixed in https://github.com/OpenLiberty/open-liberty/pull/15340
