### ISSUE TITLE
Context root values specified in application.xml can't be overridden in server.xml

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#11909]
At the moment, context root values defined in the application.xml deployment descriptor take precedence over all other ways to specify them. This is a problem for some users who have applications that they aren't allowed to modify. 

We already have numerous ways to specify the context root. Instead of adding yet another one, perhaps it makes sense to make use of the current web-ext overrides in server.xml. We can change the precedence order without much risk of affecting existing users given that the web-ext context root would not be used today. We would, however, have to keep the current behavior for context root values specified in ibm-web-ext.xml. 

This solution might be a little confusing given that there are no other behavior differences between bindings/extensions specified in application artifacts and server.xml.

**Comment by cthigh** [comment]
This is important for traditional WebSphere to Liberty migration scenarios since the context-root can be changed at deploy time in tWAS. The migration tools could migrate the context-root from the merged configuration settings. Without this issue being fixed, if context-root is set in the application.xml, a code change is needed for migration if a different context-root is preferred.
