### ISSUE TITLE
Automatic EJB Timer does not fire after redeploying K8s pods

### ISSUE THREAD

**Issue by johnpica** [OpenLiberty/open-liberty#12078]
**Describe the bug**
Automatic EJB Timer does not fire after redeploying K8s pods
In the logs, I can see only _CNTR0219I: The server created 0 persistent automatic timer or timers and 0 non-persistent automatic timer or timers for the xyz.war module.._

**Steps to Reproduce**
Deploy liberty container with _ejbPersistentTimer-3.2_ configured and automatic timer _@Schedule_ k8s with 3 replicas. 
`@Startup
@Singleton
public class AutomaticTimerBean {
        private int counterAutomatic;
	@Schedule(minute = "*/1", hour = "*")
	public void automaticTimer() {
		logger.info("fire automaticTimer: {}", counterAutomatic++);
	}
}`
**Expected behavior**
After the first deploy on k8s:
- the _EJBTIMER_PART_ table will contain 3 records (3 different HOSTNAME because of the 3 pods)
- the table _EJBTIMER_PROP_ contains 1 record _!EJBTimerA!bpm-api#xyz.war_
- the table  _EJBTIMER_TASK_ contains 1 record _!EJBTimerA!xyz.war#AutomaticTimerBean_

The timer will fire and you will see each minute printed: 
_AutomaticTimerBean - fire automaticTimer: 0
AutomaticTimerBean - fire automaticTimer: 1
etc_
and it works fine for the first deploy.

After the second deployment in Kubernetes of the same liberty container, the timer will **not fire**.
After the second deployment on k8s:
- the _EJBTIMER_PART_ table will contain 6 records (3 different HOSTNAME because of the 3 pods + the 3 records from the first deployment)
- the table _EJBTIMER_PROP_ contains 1 record _!EJBTimerA!bpm-api#xyz.war_
- the table  _EJBTIMER_TASK_ contains 1 record _!EJBTimerA!xyz.war#AutomaticTimerBean_

**Diagnostic information:**
 - WAS Liberty Version: 19.0.0.9

**Comment by njr-11** [comment]
This happens because EJB persistent timers in Liberty are scoped to the database tables where they are stored, not to each individual server. This was done to allow for the eventual addition of a failover feature, #7774, which has only very recently been delivered.  The version you are using, 19.0.0.9, does not have the failover support yet, and so the first server to insert the automatic persistent timer retains ownership of it and continues to run it, whereas all other servers see that the timer exists and do not create a duplicate of it.  This is clearly not ideal when running in kubernetes.  However, with the introduction of #7774 (targeted for 20.0.0.5), all of the servers which point at the same database tables will share ownership of the EJB timers, and it will be possible for the timers to run on any of those servers which are active.
If the coordination/failover capability isn't desired and you were hoping for each server to run its own copy of the timers, you could point each server at a different database to accomplish that, although I would question whether the persistence of the timers really has much value in that case, and you should consider using non-persistent timers, which are never coordinated across servers.

**Comment by tkburroughs** [comment]
Note: if you really don't require "persistent" timers, but just want the timer to be running in each server process, the the best approach is to use non-persistent timers, which is easily done as follows:

`@Schedule(minute = "*/1", hour = "*", persistent = false) `

When using non-persistent timers, all `@Schedule` timers will be created in each server process when the application starts, and will be gone when the application/server stops.

**Comment by johnpica** [comment]
Thank you for the explanations. I will try Liberty 20.0.0.5
