### ISSUE TITLE
OL Beta: Output a NLS message at startup

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#12222]
A beta runtime should output a message at startup to make it clear that this is an unsupported beta.

The message should be output on both the command line (e.g. `server run`) and in the console.log so that is it very visible to the service teams as well.

**Comment by cbridgha** [comment]
This needs to be added to command line AND log files.

**Comment by jimblye** [comment]
Whether this is an early access release is determined by properties files in the wlp/lib/versions directory.   If you have WebSphere Liberty, there will be 2 properties files:  WebSphereApplicationServer.properties and openliberty.properties.  Each has a ...productEdition property.  I don't know if they always agree.   Also the code is written as though there might be more than 2 properties files.

I could make the message generic.  Something like: "This is an unsupported early release version of the product."
Or I could do: "This is an unsupported early release version of {0}."

For the second option, I could display a message for each of the "ProductInfos" ( .properties files ) that have productEdition set to EARLY_ACCESS. 

If we only want one message, then I would display "WebSphere Liberty" when both properties files are present or "Open Liberty" when just the openliberty.properties file is present.

It's actually a bit cleaner to just display a message for each of the Products.   It looks like this when both are present:

Starting server defaultServer.
CWWKE0953W: This is an unsupported early release version of Open Liberty.
CWWKE0953W: This is an unsupported early release version of WebSphere Application Server.
Server defaultServer started with process ID 59298.

So that is what I have done.   If only one of them is set to EARLY_ACCESS, then you only get the one message.
