### ISSUE TITLE
Dynamic logging of SOAP Messages in jaxws-2.2 and wsAtomicTransaction-1.2

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#12499]
Currently, both features require an app restart to enable the tracing of inbound/oubound SOAP messages. Dynamic logging can be enabled by sub-classing the LoggingIn(Out)Interceptor's within the Web Service Engine, and updating the WSAT's WSATFeatureBusListener class to use the new interceptor.

**Comment by andymc12** [comment]
In today's call, we discussed subclassing the LoggingIn/OutInterceptors so that `getMessageLogger` would return a valid logger if the trace specification was set to DEBUG (or FINE) or lower, but would return null otherwise. Then we would always add those interceptors. That should allow the interceptors to no-op if the trace spec is not set to DEBUG/FINE or lower, but would allow users to dynamically update the trace spec so that they would be able to see the nicely formatted request/response trace.

**Comment by neuwerk** [comment]
Closing this issues as this was implemented last year.
