### ISSUE TITLE
JMS 2.0 feature is missing from Open Liberty

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#126]
The JMS 2.0 feature should be part of Open Liberty.

**Comment by jwalcorn** [comment]
I believe we also want the wmqJmsClient-2.0 feature included as well, per offline discussion with Alasdair

**Comment by NottyCode** [comment]
Sorry for confusion caused, but I didn't mean we would move the wmqJmsClient-2.0 feature. You can use jms-2.0 and jca-1.7 to get OpenLiberty and MQ working together, you do not need the wmqJmsClient-2.0 feature.

**Comment by jwalcorn** [comment]
Thanks for the clarification Alasdair.  I'll try your suggestion of just using <resourceAdapter id=“wmqJms” location=“point to the RAR”/> without the wmqJmsClient-2.0 feature.  I'll have to try that on a full "commercial" Liberty server, since jms-2.0 is missing at the moment on Open Liberty (which leads to the following errors):

[INFO    ] FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: javax/jms/MessageListener com.ibm.ws.container.service.state.internal.ApplicationStateManager 31" at ffdc_17.09.21_14.27.08.0.log
[INFO    ] FFDC1015I: An FFDC Incident has been created: "com.ibm.ws.container.service.state.StateChangeException: java.lang.NoClassDefFoundError: javax/jms/MessageListener com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase 376" at ffdc_17.09.21_14.27.08.1.log
[ERROR   ] CWWKZ0106E: Could not start web application Notification.
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application Notification. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.lang.NoClassDefFoundError: javax/jms/MessageListener

**Comment by cbridgha** [comment]
https://github.com/OpenLiberty/open-liberty/pull/178

**Comment by cbridgha** [comment]
Just delivered the was-liberty side of this... closing
https://github.ibm.com/was-liberty/WS-CD-Open/pull/8309
