### ISSUE TITLE
Dev mode autorefresh browser, Browsersync not working

### ISSUE THREAD

**Issue by kllp** [OpenLiberty/open-liberty#12705]
In a minimal openliberty maven project folder i run
Server:  "mvn liberty:dev"
Browsersync: "browser-sync start --proxy "http://localhost:9080/ServletSample" --files *"

Browsersync only injects its Javascript in the page delivered at "localhost:3000/" and not in "localhost:3000/ServletSample"
In the browser only the first is refreshed. The second is not.
Nonetheless all changes are detected correctly by browsersync.
It just doesn't reload the non-root directory pages.

Is there another solution?
I try to avoid refreshing the browser manually with openliberty's dev mode. 
Thank you

**Comment by ericglau** [comment]
Browser-sync works by injecting Javascript content into the page, so the page must return HTML content in order for this to work.

For example, using the sample project from https://github.com/OpenLiberty/guide-maven-intro/tree/master/finish and running the commands that you described:

- http://localhost:3000/ServletSample/ will auto-refresh when you make changes to `src/main/webapp/index.html`.
- http://localhost:3000/ServletSample/servlet will not auto-refresh because the servlet returns plain text.  However, if you change the line in `src/main/java/io/openliberty/guides/hello/HelloServlet.java` to return HTML, e.g. `response.getWriter().append("<html><body>Hello! How are you today?\n</body></html>");` and refresh the page once, then the browser shows `Browsersync: connected` and any further changes to the servlet will be auto-refreshed. 

Let me know if the above doesn't work for you.

**Comment by kllp** [comment]
That helped but I found  out that Browsersync isn't suited for java frontend development.
It doesn't treat .xhtml files correctly and the setup is not straightforward.
For example you can't use <h:body> elements.
I couldn't get JSF to work with openliberty.
