### ISSUE TITLE
Port APAR PI87504 to JAXRS 2.1

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#1319]

**Comment by ewhoch** [comment]
This really doesn't make sense as an issue. There's nothing linked to it, no description, no one assigned, and it's referencing an internal artifact.

**Comment by jim-krueger** [comment]
#1320

**Comment by ewhoch** [comment]
Still very bare... I could google what PI87504 was, but that's not really ideal, but I'm tangentially seeing issue #1312.

It seems like this started with #1312 which has a light description (it's still open), the fix for that went with PR #1315, but that PR closed without merging and never had any linkage to #1312, so you can't navigate from one to the other.

That fix was abandoned in favor of rolling that into #1320, which used PR #1319 to deliver the code. Again, not linked. But these have no information in them, it's basically just code put into the stream with no searchable description of what the code is doing or fixing. In the future I'd advise yourself or @andymc12 to not merge or complete review of changes in this state.

Is it this? http://www-01.ibm.com/support/docview.wss?uid=swg1PI87504

and is this fixing 

"Section 3.3.4 of the JAXRS 2.0 specification indicates the
following:
"4. Checked exceptions and throwables that have not been mapped and cannot be thrown directly MUST be wrapped in a container-specific exception that is then thrown and allowed to propagate to the underlying container. Servlet-based implementations MUST use ServletException as the wrapper. JAX-WS Provider-based implementations MUST use WebServiceException as the wrapper."

Currently the Liberty JAXRS 2.0 server only returns an HTTP 500 message in this situation."
