### ISSUE TITLE
Design dashboard that takes advantage of the FT 3.0 metrics changes

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#13251]
Having metrics use tags opens up new opportunities for things we can put on a grafana dashboard.

In particular:

1. We can show multiple methods on the same graph as the method identifier is now a tag
2. We can display a top-k list of methods in a table (e.g. the top-5 methods with the most fallback calls) to highlight potential problem areas
3. If we can remove the drop-down to select the method, we could integrate some features into the main OpenLiberty dashboard

Existing OL dashboard here: https://grafana.com/grafana/dashboards/11706

**Comment by Joseph-Cass** [comment]
I have produced some graphs which address @Azquelt's 1st point:

![image](https://user-images.githubusercontent.com/55994281/90414448-b3449d00-e0a7-11ea-8d26-f579ad424b23.png)

The graphs down the left column represent individual methods for each different instance, where the graphs down the right show the aggregated values across all the selected instances (`All` instances in the example, though this can be any custom selection of instances)

This also addresses the 3rd point since the graphs no longer require a method to be selected, so any of the shown graphs _should_ be able to be used in the main OL dashboard.

I have uploaded the JSON here: https://github.com/Joseph-Cass/grafana/blob/master/microprofile-fault-tolerance-3.0-grafana.json

**Comment by Joseph-Cass** [comment]
I have also prototyped a `topK` table which, if we like, we can re-use for the other FT strategies, e.g.
- Top k methods most frequently applying Fallback
- Top k method retries per invocations

![image](https://user-images.githubusercontent.com/55994281/90421673-b04eaa00-e0b1-11ea-8384-2f0a0d36b04a.png)

**Comment by Joseph-Cass** [comment]
Following a chat with @Azquelt and @donbourne , we've decided to: Produce a section for Fault Tolerance for the OL dashboard
 - Add a `Fault Tolerance` row with a panel for each FT annotation in the OL dashboard published on grafana.com
 - Update the variable syntax throughout dashboard to be compatible with Grafana 6.x
 - Publish to somewhere live where the metrics team can review and update

**Comment by Azquelt** [comment]
This was set to done, but not actually closed.
