### ISSUE TITLE
Revisit how to treat ibm:beta="true" in GA builds

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#14081]
## Background

Currently we have one mechanism for gating new config as non-GA, and that is marking the element or attribute as `ibm:beta="true"`. Marking config as beta has the following characteristics for a GA build:

- The new config will NOT appear in generated config documentation
- The new config will NOT appear in the server.xml schema
- The new config WILL be usable if a user knew to specify it. 
- The new config WILL be active if present in a defaultInstances.xml or default attribute values

## Problem

The issue is the 4th bullet point above. Since there is no gate for noship config (e.g. `ibm:noship="true"`), developers must mark beta config as `ibm:beta="true"`, even if the new config is not ready for beta yet. This means we can have immature and not fully tested default configuration impacting GA builds. By the time we GA new config it must not change default behavior, but during the development process there may be a window of time where default behavior is changed, either on purpose or by accident.

### Option A

Update the config runtime to ignore `ibm:beta` metatype in a GA build. This would be consistent with behavior of someone specifying bogus/unknown config.

**Comment by tevans78** [comment]
The beta config should be treated as if it is just not there and deleted from the config. To be prioritized as an Epic.

**Comment by brenthdaniel** [comment]
> Update the config runtime to ignore ibm:beta metatype in a GA build. This would be consistent with behavior of someone specifying bogus/unknown config.

This is not true. It has been the core principle of Liberty config since the beggining of the project that ALL configuration is accepted and passed through regardless of whether it has valid metatype. This work item would be a massive change to our basic assumptions.

**Comment by tjwatson** [comment]
> This is not true. It has been the core principle of Liberty config since the beggining of the project that ALL configuration is accepted and passed through regardless of whether it has valid metatype. This work item would be a massive change to our basic assumptions.

"massive change to our basic assumptions".  Focusing on this, if the assumptions are changed WRT `ibm:beta=true` what is the fall out of this massive change?  If I understand this correctly the proposal is to remove all values from the config handed to targets of anything marked `ibm:beta=true` when running on a GA build.  Should not the targets of a config map already be able to handle the beta config not being there?

Also, do we allow product extensions to use `ibm:beta=true`?  Does the proposed behavior apply to product extension meta-data also?  This seems strange if it does.  Product extensions may have some concept of beta, but they will likely want to allow their betas to be installable onto our GA builds.  If we do anything here WRT `ibm:beta=true` I think it must only be done for meta-type defined by our own bundles and not the ones from product extensions.

**Comment by brenthdaniel** [comment]
There isn't much fallout with respect to ibm:beta specifically. But we have repeatedly over the years decided against certain changes because it violates the "all config gets passed through" principle (eg, validating attributes and issuing warning messages if we see config that we don't expect.) It's worth having a conversation about whether we are changing that assumption altogether (and should pursue all the things we've avoided doing over the years) or saying that we think this case is important enough to violate the principle and that it will be isolated enough to not matter. 

We also would need to accept that the first release with this change would break for any customers who were leveraging beta function in a GA build. I also wonder if our testing is sufficient to cover both beta and GA scenarios. 

I don't think we have to worry about ibm:beta in product exensions because we haven't documented it anywhere.

**Comment by tjwatson** [comment]
> There isn't much fallout with respect to ibm:beta specifically. But we have repeatedly over the years decided against certain changes because it violates the "all config gets passed through" principle (eg, validating attributes and issuing warning messages if we see config that we don't expect.) It's worth having a conversation about whether we are changing that assumption altogether (and should pursue all the things we've avoided doing over the years) or saying that we think this case is important enough to violate the principle and that it will be isolated enough to not matter.

I would like to have the discussion over what has been avoided over the years here.  I was not part of the original principle so do not have all the history of why the principle exists, but would like to also understand what the principle was trying to protect.  We should continue to understand what the principles are and make sure they still make sense and are not around just for principle's sake. Perhaps there is a place such principles are documented and justified?

> 
> We also would need to accept that the first release with this change would break for any customers who were leveraging beta function in a GA build. I also wonder if our testing is sufficient to cover both beta and GA scenarios.

This is something the POC should decide.  In isolation my decision is likely always going to be: "We should not continue allow things we do not want to support in the field".

> 
> I don't think we have to worry about ibm:beta in product exensions because we haven't documented it anywhere.

We have a concern about breaking customers who leverage undocumented (maybe beta) function in GA builds.  That same concern seems like it would apply to product extensions that use an undocumented `ibm:beta` attribute in their own extension.  But maybe I misunderstand what you mean by not having to worry here.  Regardless, my vote here would be to have consistent behavior and not special case our own features with respect to `ibm:beta` with the risk of breaking some unlikely usage by a product extension.

**Comment by NottyCode** [comment]
We don't want people using beta function in a GA release since the function may not be fully functioning, tested and so on. Also the configuration may change. This proposal to remove beta config from a GA is one proposal on how to stop this happening, but we could choose others. The thing is this allows us to make the change in one place and have it protect everyone, rather than having everyone work out if it is GA or not and then remove the configuration.

**Comment by tevans78** [comment]
Moved back to "discussing" for further discussion next time

**Comment by tjwatson** [comment]
Design discussion: decided to produce an error message instead of automatically removing beta attributes from config when running on a GA driver.

Remaining concern is if bundles are included in liberty that provide default configuration marked beta.  The practice sounds strange.  Producing a new message will cause an FATs that enable such a feature to fail. Plan is to look at introducing a new error message.

**Comment by cbridgha** [comment]
Implementation of this feature should also consider internal attributes..   merging from #16318 - If a message is to be produced it should behave similar or be the same as the message for the beta attribute usage. In both cases the error message would be logged but the config would be passed through the same as it is today. For internal attributes we will need to differentiate configuration included in default instances included in feature bundles vs. the config set by the user. Only configuration set by the user should produce the error message.

**Comment by malincoln** [comment]
Per @cbridgha this is still valid.

**Comment by malincoln** [comment]
Agreed to close.
