### ISSUE TITLE
Support multi-release jars in user applications

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#1423]

**Comment by tbitonti** [comment]
See: http://openjdk.java.net/jeps/238
and: http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-September/013172.html

There are two initial considerations:

(1) Toleration of classes under META-INF/versions
(2) Processing of classes under META-INF/versions.

Following, there is the consideration:

(3) The impact MR with the javaEE specifications.

The issue (1) arises when applications directly use MR JARs, or, perhaps more frequently, when applications include a JAR which is enabled for MR.  This is already the case for applications in use by TWAS, which encountered this issue with "lib4j" JAR files.  See TWAS APAR PI89708 and JAR file "log4j-api-2.9.1.jar": http://www-01.ibm.com/support/docview.wss?uid=swg1PI89708.

For our current annotation scanning, this problem occurs because class files are present in a location which, prior to MR, was not valid for class files.  The path to a class resource is required to match the qualified package of the class.  "META-INF" is not a valid simple name for a java package.  Prior to MR, classes were never present under META-INF, and this location was not filtered to prevent the scanning of classes at that location.  With MR, classes are now present under META-INF, and extra code is necessary to ignore the classes.

**Comment by tbitonti** [comment]
The issue (2) has impacts at the least to runtime classloading, which, if MR aware, must perform extra steps to select the class resource to use for a target class.  This is detailed in the open JDK discussion, which has:

Class loader resources

A resource URL, produced by a class loader, identifying a resource in a MRJAR will refer directly to a versioned entry (if present). For example for a versioned resource, foo/baz/resource.txt:

URL r = loader.getResource("foo/baz/resource.txt");

the URL ‘r’ may be: jar:file:/mrjar.jar!/META-INF/versions/9/foo/baz/resource.txt

rather than: jar:file:/mrjar.jar!/foo/baz/resource.txt

**Comment by tbitonti** [comment]
The issue (2) would seem to have additional impacts to annotation scanning, if different class versions are allowed to have different annotations.  For JavaEE cases, this may not be allowed.  For cases such as our dynamic trace injection or dynamic test definitions, the impact is unclear.

**Comment by tbitonti** [comment]
The issue (3) is rather open. For example, are WAR files to be enabled for MR?  Are JavaEE active annotations allowed to be different in different class versions?

**Comment by tbitonti** [comment]
Generally, for annotation scanning, if scanning must be MR aware, there are two problems:  

First, scans must either generate version aware result buckets, and the query APIs must be updated to include a version parameter, or, the version parameter must be provided when the results are generated, and the scan step must select the correct class version for scanning.

If the scan step must be version aware, the second issue arises: Simple iteration would no longer be sufficient to process classes of a JAR file.  Upon encountering a class, the iteration must know if there is another version of the class which should be used in preference to the immediately present class version.  That is to say, iteration must obtain a complete resource list, then select resources appropriate for the target version, then perform the scan of the selected resources.

**Comment by tbitonti** [comment]
OpenJDK Links:

Top javaEE spec discussion group:
    https://javaee.groups.io/g/javaee-spec
Top Servlet JavaEE spec discussion group:
    https://javaee.groups.io/g/servlet-spec
Discussion re: multi-release JAR annotation scanning in the Servlet spec discussion group:
    https://javaee.groups.io/g/servlet-spec/message/74
