### ISSUE TITLE
How to handle singleton/toleration of "io.openliberty" vs "com.ibm" features - particularly in MicroProfile features

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14641]
This design issue comes from issue #14611.  The net of that issue is that the `mpGraphQL-1.0` feature cannot currently tolerate `mpConfig-2.0` (part of MP 4.0) because: (1) it depends on the `mpConfig-1.4` feature (both API and impl) and (2) the `mpConfig-1.4` feature starts with "com.ibm.websphere.appserver" and `mpConfig-2.0` feature starts with "io.openliberty" - therefore they are not the singletons - and `mpGraphQL-1.0` cannot tolerate `mpConfig-2.0`.

First decision: do we care?  I think it would be very limiting for GraphQL users to be locked in to MP 3.3 technologies, but maybe we can live with that... 

Assuming we care, second decision: How do we make this work?  Here are a few options:
(1) MP 4.0 has not shipped - it's not too late to rename the new features to start with "com.ibm.websphere.appserver"

(2) Update the feature manager to match "com.ibm.websphere.xyz" with "io.openliberty.xyz" so that 
```
-features=com.ibm.websphere.appserver.mpConfig-1.4;ibm.tolerates=2.0,\
```
just works as if `mpConfig-2.0`'s symbolic name started with "com.ibm.websphere.appserver".

(3) The hard way... create `mpCompatible-3.3`, `mpCompatible-4.0`, etc. features as described in issue #14219. Then features like `mpGraphQL-1.0` must drop its dependency on `mpConfig-1.4` and instead depend on `mpCompatible-3.3;ibm.tolerates=4.0`.  Then create two new auto-features for `mpGraphQL-1.0+mpCompatible-3.3` and `mpGraphQL-1.0+mpCompatible-4.0` that provide features `mpConfig-1.4` and `mpConfig-2.0`, respectively.

I prefer option 1 or 2 due to the simplicity.  Option 3 will likely work, but it adds a lot of overhead - and will likely require this same sort of approach for future changes - i.e. `mpLRA` might have to do the same thing to work with MP 4.1, 4.2, 4.3, etc. `mpGraphQL-1.0` would have to add or update auto-features with MP 4.1, 4.2, etc.

**Comment by tjwatson** [comment]
This relates back to issue #9214

At that time we decided against the need to alias because the Jakarta boundary likely wasn't one that could be tolerated across so it would be acceptable to rename the long names of the Jakarta features.  That whole discussion hinged on the fact that we were only considering renaming the Jakarta features because of the clear boundary.  I see no such clear boundary for MP features.

The reason we even considered renaming any of the Jakarta features was because of the TM concerns over the short feature names for things like EBJ, JSF, JSP etc.  Without the TM concern I have doubts that we ever would have considered renaming any of the features for Jakarta 9.  There is no customer need that would justify driving such work.

With all that in consideration I advise keeping the `com.ibm.websphere.appserver` prefix for all new versions of our public/protected features that are not related to Jakarta features.

**Comment by NottyCode** [comment]
I think based on our prior discussion we said that renaming should only happen where there is no requirement to tolerate between the old and new versions. This is the case in Jakarta EE 8 -> 9 because of the package name changes.

**Comment by mbroz2** [comment]
Result of poll:
![image](https://user-images.githubusercontent.com/3076261/97316735-15541800-1838-11eb-8da4-4c0c0f72f4a7.png)

**Comment by mbroz2** [comment]
We'll use this issue to rename all the MP features back to com.ibm, which @tevans78 will own.
