### ISSUE TITLE
MP GraphQL does not scan JARs in WEB-INF/lib for GraphQL components

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14650]
Classes annotated with things like `@GraphQLApi`, `@Type`, etc. or types referenced from root level queries that exist in JARs in the WEB-INF/lib directory are not processed.  This means that only classes in the WEB-INF/classes directory are processed by the MP GraphQL runtime.

**Comment by knives85** [comment]
Hi all, I'm trying to integrate mpGraphql in my microprofile project and it seems this issue is still present.
I'm using liberty-maven-plugin 3.2 and liberty 20.0.0.12 in dev mode.

I've uploaded an example here [openliberty_graphql](https://github.com/knives85/openliberty_graphql). Here there are 2 classes annotated with @GraphQlApi, one in the top war module and one in the nested jar. When deployed it seems like only the top module Endpoint is discovered.

Can you please check if I'm doing something wrong?

Thanks in advance

**Comment by shubham-bakshi** [comment]
If anyone is still looking for a solution, you can add a smallrye maven plugin with following configuration
<plugin>
  <artifactId>smallrye-graphql-maven-plugin</artifactId>
  <groupId>io.smallrye</groupId>
  <configuration>
    <includeDependencies>true</includeDependencies>
    <includeScalars>true</includeScalars>
  </configuration>
  <executions>
    <execution>
        <goals>
            <goal>generate-schema</goal>
        </goals>
    </execution>
  </executions>
</plugin>
