### ISSUE TITLE
OpenAPI 2.0 Startup

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#14678]
When comparing microProfile-4.0 startup time to microProfile-3.3 startup time, I am seeing a regression. The regression looks to be related to mpOpenAPI-2.0, specifically the jandex scanning it does at startup.

This is with a very simple app, so things are exaggerated, but seeing almost 17% of the startup time spent in io/openliberty/microprofile/openapi20/utils/IndexUtils.getIndexView
```
  Parent      0   0.55  16.94           1          31    I:io/openliberty/microprofile/openapi20/ApplicationProcessor.processWebModule(Lcom/ibm/wsspi/adaptable/module/Container;Lcom/ibm/ws/container/service/app/deploy/WebModuleInfo;)Lorg/eclipse/microprofile/openapi/models/OpenAPI;
 
    Self      0   0.55  16.94           1          31    I:io/openliberty/microprofile/openapi20/utils/IndexUtils.getIndexView(Lcom/ibm/ws/container/service/app/deploy/WebModuleInfo;Lio/smallrye/openapi/api/OpenApiConfig;)Lorg/jboss/jandex/IndexView;
 
   Child      0   0.00  16.39           0          30    I:io/openliberty/microprofile/openapi20/utils/IndexUtils.processJar(Ljava/io/InputStream;Lorg/jboss/jandex/Indexer;Lio/smallrye/openapi/runtime/scanner/FilteredIndexView;Lio/smallrye/openapi/api/OpenApiConfig;)V
``` 

Farther down the stack (jandex code -13%)
```
  Parent      0   0.00   0.55           0           1    I:io/smallrye/openapi/runtime/util/TypeUtil.index(Lorg/jboss/jandex/Indexer;Ljava/lang/Class;)V
  Parent      0   0.00   0.55           0           1    I:io/smallrye/openapi/runtime/scanner/OpenApiDataObjectScanner.index(Lorg/jboss/jandex/Indexer;Ljava/lang/String;)V
  Parent      0   0.00  12.02           0          22    J:io/openliberty/microprofile/openapi20/utils/IndexUtils.processFile(Ljava/lang/String;Ljava/io/InputStream;Lorg/jboss/jandex/Indexer;Lio/smallrye/openapi/runtime/scanner/FilteredIndexView;Lio/smallrye/openapi/api/OpenApiConfig;)V
 
    Self      0   0.00  13.11           0          24    J:org/jboss/jandex/Indexer.index(Ljava/io/InputStream;)Lorg/jboss/jandex/ClassInfo;
 
   Child      0   1.09   2.73           2           5    J:org/jboss/jandex/Indexer.processConstantPool(Ljava/io/DataInputStream;)Z
   Child      0   0.00   2.19           0           4    J:org/jboss/jandex/Indexer.verifyMagic(Ljava/io/DataInputStream;)V
   Child      0   0.00   2.19           0           4    J:org/jboss/jandex/Indexer.processMethodInfo(Ljava/io/DataInputStream;)V
   Child      0   0.00   1.64           0           3    J:org/jboss/jandex/Indexer.processClassInfo(Ljava/io/DataInputStream;)V
   Child      0   0.00   1.64           0           3    J:org/jboss/jandex/Indexer.applySignatures()V
   Child      0   0.00   1.09           0           2    J:org/jboss/jandex/ClassInfo.setMethods(Ljava/util/List;Lorg/jboss/jandex/NameTable;)V
   Child      0   0.00   1.09           0           2    J:org/jboss/jandex/Indexer.processFieldInfo(Ljava/io/DataInputStream;)V
   Child      0   0.00   0.55           0           1    J:org/jboss/jandex/Indexer.processAttributes(Ljava/io/DataInputStream;Lorg/jboss/jandex/AnnotationTarget;)V
``` 

It would be nice if we could cache the jandex stuff on startup so we only do it on the first start if the app hasn't changed.

**Comment by Azquelt** [comment]
Hi @jdmcclur, I think we have a fix for this, could you try this again with my personal build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_DWmMICnBEeugFadUkByo4Q

**Comment by jdmcclur** [comment]
@Azquelt - yes, this looks better. Startup times after the initial start with OpenAPI 2.0 are within acceptable variance of where they were with 1.1. The initial start time is longer, guessing because of additional overhead of making things work with smallrye (the jandex scanning).


 startup (s) | initial start | after initial start
-- | -- | --
OpenAPI 1.1 - baseline | 8.093 | 1.532
OpenAPI 2.0 - before fix | 8.917 | 1.932
OpenAPI 2.0 - after fix | 9.205 | 1.559

**Comment by Azquelt** [comment]
Hmm, I'd expect OpenAPI 2.0 to be slower than OpenAPI 1.1 on initial start since it does its own scanning, but I'm a bit surprised that after the fix the initial start is slower than before the fix.

I guess it could be down to the overhead of serializing the model to a file so that we can cache it.

**Comment by Azquelt** [comment]
Hmm, how much of an issue is that? We can try storing the model in the cache asynchronously since that doesn't need to happen before the app starts.

**Comment by jdmcclur** [comment]
I'll defer to the startup experts. @jhanders34, @gjdeval - how much should we care about the initial startup above?

**Comment by Azquelt** [comment]
I've implemented writing the model cache asynchronously, could you see if this PB improves the first startup time?
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_CbuJ0C5XEeuXe4FTUa5Giw

**Comment by jdmcclur** [comment]
In my small app, it did not help. The work is being done on a different thread, but takes about the same time.
I can try on a bigger app when I get back next week.

```
  Parent      0   0.00   1.82           0          19    I:io/openliberty/microprofile/openapi20/cache/CacheEntry.lambda$writeAsync$0()Ljava/lang/Void;
 
    Self      0   0.00   1.82           0          19    I:io/openliberty/microprofile/openapi20/cache/CacheEntry.writeModel(Ljava/nio/file/Path;)V
 
   Child      0   0.00   1.82           0          19    I:io/smallrye/openapi/runtime/io/OpenApiSerializer.serialize(Lorg/eclipse/microprofile/openapi/models/OpenAPI;Lio/smallrye/openapi/runtime/io/Format;)Ljava/lang/String;
```

**Comment by Azquelt** [comment]
Hmm, that's expected, it should take the same amount of time, but on another thread, but it shouldn't prevent the app from starting while it runs. So I'd expect to see it take the same amount of time, but I'd expect the server startup to finish more quickly.

**Comment by jdmcclur** [comment]
Hmm, well, seems like a good plan, but it doesn't seem to help startup time at all. I looked at it more today, but no progress - I'll investigate more tomorrow.

**Comment by Azquelt** [comment]
Did you have a chance to look at it?

Any idea where the time waiting for the app to start is coming from?

Also, what are you measuring as the startup time? Just the time until the server reports that the app has started or are you waiting until a request to the app succeeds or a request to the OpenAPI endpoint?

**Comment by jdmcclur** [comment]
I am measuring when the server reports the app has started, basically doing this from the bin directory:
```
rm -rf ../usr/servers/.classCache
time ./server start --clean
```

I am not sure what is going on yet.

**Comment by jdmcclur** [comment]
ok, after doing many runs, it looks your change is helping a bit (.22 seconds in the case below). I confirmed that it is working, and is asynchronous. But it is still slower (.25s) than it was before, so something else is going on. I am trying to figure out what that is. I put in a sleep so the cache is generated 15 seconds later, so resources didn't compete during the startup, but it measured about the same as the last row.

build   | initial startup (s) (average of 15) | %
-- | -- | --
20.0.0.12-ga   (mpopenapi-1.1) | 8.04 | 90.3%
20.0.0.12-ga (mpopenapi-2.0) baseline| 8.90 | 100.0%
fix1 (added cache which helps starts   after first) | 9.37 | 105.3%
fix2 (generate cache async) | 9.15 | 102.8%

**Comment by Azquelt** [comment]
I don't know why that would be either, as it looks like it's not making much of a difference, I haven't merged the change since I don't really like how much it complicates the code.

Could we please have an update on whether the current performance is acceptable? Is it still @jhanders34 and @gjdeval we need to ask about that?

**Comment by jhanders34** [comment]
Andrew it is still me to get the approval from.  Of course I talk to the team about approvals.  Joe is the main person from a MP perspective and I look to him to tell me what he thinks.  When it is a startup problem, Gary will also get involved of course since he is the resident startup SME.  There is a lot of debate going on right now with approvals with MP 4.0 since we aren't using the final APIs  yet so technically things are not feature complete.

**Comment by Azquelt** [comment]
Thanks @jhanders34 and @jdmcclur.

So, it looks like the startup performance is better after adding the caching but the initial start is slightly worse, and my attempt to rectify that was only a marginal improvement.

However, I'm not sure if we're now in a situation where:
* the current performance is not good enough and must be improved
* the current performance is ok, but we should work to see if we can improve it further
* the current performance is fine and we can close this issue

My major concern is that if the current performance is not good enough then we may have to consider something more drastic like revisiting the decision to use smallrye-openapi which would mean we suddenly have a _lot_ more work to do than we had anticipated.

Even though we're not feature complete because we don't have final APIs, I'd really appreciate some guidance on how big a problem this issue is so I know if we need to start planning to do that work.

The only small scale idea I have left to try for this issue is changing the caching to cache the jandex index instead of the final OpenAPI model to see if the serialization there is faster.

**Comment by jdmcclur** [comment]
@Azquelt - I recommend we go with:

- the current performance is ok, but we should work to see if we can improve it further

Startup performance after the initial startup looks good, which is what we focus on, but it would be nice to improve this. Have you talked to @tbitonti? Does he have any good ideas here?

**Comment by Azquelt** [comment]
@jdmcclur I got back to this. Could you try the personal build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__Gn20Hp0Eeu8SN1zElUVXg

It should reduce the number of times we're opening and closing zip files, so I'd expect it to show a slight improvement in the cold startup.

I also experimented with caching the jandex index instead of the final openapi model, but this was slower for both the warm and cold start.

**Comment by Azquelt** [comment]
I forgot to mention that the code for the change is in #16059 

@jdmcclur Were you able to determine whether this made a difference to the cold start time?

I'm off for the next week and a half, @tevans78 or @Joseph-Cass are the people to ask if there are any questions.

**Comment by jdmcclur** [comment]
In the test cases I have tried, it doesn't seem to make a difference. I still need to try an app with a lot of files to open/close.

**Comment by Azquelt** [comment]
We've tried several approaches but haven't come up with anything that shows a measurable improvement so I'm going to suggest we give up for now and close this issue.
