### ISSUE TITLE
Private API features do not declare programming model affinity (i.e. eeCompatible dependency)

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#14833]
A server will fail to detect conflicting API features in the resolved feature set for any feature F which:

- Includes eeCompatible-x.0 (depends on some programming model compatibility feature)
- Includes API-1 that is compatible with ee-x.0
- Includes API-2 that does not declare an eeCompatible-y.0 dependency
- Lacks eeCompatible-y.0

For example: Feature F contains servlet-5.0, com.ibm.webserver.appserver.javax.cdi-1.2, and lacks a public feature which includes eeCompatible-7.0.

How should we address this issue?  Inspection of feature internals?  Improve feature validation? 

We could declare the ee/mp versions (i.e. compatibility and tolerations) for each private API feature.  That would entail working with the ee team(s) to determine the ee versions allowed for each API feature. 

Doing a quick scan, these API do not declare ee compatibility: _annotation, cdi, connector, ejb, interceptor, el, jsf, jsp, mail, servlet, persistence, transaction, validation_; these do: _jaxrs, json_.

**Comment by tjwatson** [comment]
An alternative to updating the private features to include a compatible feature specification would be to update any protected/public that pulls in the API to ensure they specify the correct compatible feature.

I think updating the private features would be more clear and less work overall.

**Comment by tjwatson** [comment]
One thing we could do:
- Add eeCompatible-9.0 to ALL the Jakarta 9 private API features with no tolerates for < 9
- Add eeCompatible-8.0 to ALL the Javax private API features with to to 6 and 7

I believe this would ensure zero migration for all < EE 9 features while ensuring we do not allow < EE 9 APIs to be loaded when there is at least one EE API >= 9 being used.

We could then do more analysis on the < 9 EE private API feature to determine if it is safe to lock them down more between the 6-7-8 versions, but as of now I do not believe we do any of that today. Any more lock down there would be a risk to zero migration.

**Comment by andymc12** [comment]
This came up in a slack conversation wrt `restfulWS-3.0` / `restfulWSClient-3.0` features' dependency on MP Config API.  The dependency exists because RESTEasy 4.X depends on MP Config as it's configuration mechanism.  As it currently stands, restfulWS-3.0 depends on restfulWSClient-3.0 which depends on the MP Config 1.4 API private feature which depends on CDI 2.0 private feature.  This results in a "mixing" of EE8 (CDI 2.0 API) and EE9 (CDI 3.0 API + Impl) technologies.

If we want a clean separation between EE8 and EE9, then this needs to be resolved.  Here are a few options we've discussed for this specific case:
1) include some MP Config API classes in the RestEasy bundle, they don’t need to be exposed to anywhere else
2) stop the MP Config API feature from including the CDI API … this might break the private feature - it would certainly require making the imports on CDI packages to be dynamic
3) split the MP Config API private feature in two; non-CDI and CDI
4) Overlaid RestEasy code to remove MP Config dependency completely
5) refactor RESTEasy so that it can optionally depend on MP Config, but can allow other containers to plug-in their own config mechanism.  This will require buy-in from the RedHat folks, and might not happen on the schedule we're hoping for - but it's probably the most architecturally clean option.
6) something else??

**Comment by andymc12** [comment]
Option 5: I opened JIRA [RESTEASY-2767](https://issues.redhat.com/browse/RESTEASY-2767) and PR https://github.com/resteasy/Resteasy/pull/2590 to address.
