### ISSUE TITLE
Issue when deploying Open Liberty application to Openshift

### ISSUE THREAD

**Issue by levipapp** [OpenLiberty/open-liberty#14936]
I'm trying to expose a SOAP service in open liberty that is connected to a db. For that I added a data source configuration in the server.xml file. It works locally(docker image run locally connected to remote DB) but when I try to run the application in Openshift I get this error:
[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [com.ibm.lom.inputservice.facade.IsPrintServiceWSmpl] in application [input-service]: java.lang.NoClassDefFoundError: javax.xml.soap.SOAPException
	at com.ibm.ws.jaxws.globalhandler.JaxwsGlobalHandlerServiceImpl$JaxWSGlobalHandlerBusListener.initComplete(JaxwsGlobalHandlerServiceImpl.java:111)
	at [internal classes]
Caused by: java.lang.ClassNotFoundException: javax.xml.soap.SOAPException cannot be found by com.ibm.ws.jaxws.common_1.0.45.cl201020200915-1100
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:464)
	... 1 more
[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5115)
	at [internal classes]
Caused by: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:360)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: javax.xml.soap.SOAPException
	at com.ibm.ws.jaxws.globalhandler.JaxwsGlobalHandlerServiceImpl$JaxWSGlobalHandlerBusListener.initComplete(JaxwsGlobalHandlerServiceImpl.java:111)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.xml.soap.SOAPException cannot be found by com.ibm.ws.jaxws.common_1.0.45.cl201020200915-1100
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:464)
	... 1 more

- If I remove the data source configuration from the server.xml file the application works in Openshift. We are using the same data source configuration on several other micro services and they work in Openshift.

- A workaround that we found with the help of Open Liberty guys is to add to the bootstrap.properties one of the following parameters: osgi.clean=true or osgi.checkConfiguration=false. (They came to the conclusion that the issue is happening because the timestamps are changing for the files contained in the image from the time it is built to the time it is run in Openshift.)

- For the service I just used a wsdl file to generate the web service.
- The Open Liberty image that I used is: openliberty/open-liberty:kernel-java11-openj9-ubi
- I just built the docker image manually and pushed it to Openshift.

**Comment by tjwatson** [comment]
It sounds to me like your scenario for creating the Docker image is not that complex.  Would you be willing to create a github repo with an example of how you are building the image?  I don't need the actual application, just all the settings used to configure liberty and the image would help.

**Comment by bellds** [comment]
Posting as an FYI.

Our team also seem to be having this problem. 
We are getting:
`java.lang.NoClassDefFoundError: org/apache/cxf/jaxrs/validation/JAXRSBeanValidationFeature`

Our image is based
`FROM  ibmcom/websphere-liberty:20.0.0.10-full-java8-ibmjava-ubi-amd64`

We believe we are successfully working around the problem using
`osgi.checkConfiguration=false` in the `bootstrap.properties`

**Comment by tjwatson** [comment]
> We believe we are successfully working around the problem using
> `osgi.checkConfiguration=false` in the `bootstrap.properties`

That setting disables a check done by Equinox which checks the timestamps of every installed Liberty JAR to see if the timestamp has changed since the last launch of Liberty.  For the types of failures we are seeing here it appears at least the timestamp of of the JAR `lib/com.ibm.ws.org.eclipse.equinox.region_xxx.jar` has changed since the time Liberty primed its own cache at docker image build time.  This causes Equinox to toss the `equinox.region` bundle at next launch of Liberty.  The `equinox.region` bundle does get re-installed by Liberty, but at that point it is too late.  The `equinox.region` bundle is what controls visibility to the API packages which Liberty has designated as available to applications and other Liberty bundle JARs.  This causes the wrong resolution and results in the different kinds of class loading issues we have seen in some OpenShift scenarios.

What is a mystery is why the timestamp of the `equinox.region` bundle appears to be changing here.  Getting to the bottom of that would help understanding how we can prevent such timestamp changes.  Such changes not only invalidate the caching done by the Equinox Framework it also has impacts on how the j9 JVM stores classes in its shared classes cache for faster class loading.

Getting to the bottom of the timestamp change detection is good, but even if we figure out how to prevent that Liberty should be fixed to recover from such a scenario.  In PR #14940 I have already disabled the timestamp check to work around this.  In PR #15016 I hope to re-enable the check and have code in place to properly recover from the situation.

**Comment by tjwatson** [comment]
This issue was fixed by PR #14940 when I disabled the `osgi.checkConfiguration` setting by default.

But I did re-enable it with PR #15016 along with a fix to recover when the region bundle is discarded.

**Comment by veenarm** [comment]
Why was this closed?
We just got the same issue with jdk11 - 21.0.0.1, added the osgi false to bootstrap fixed it, but i think it might be due to a different underlying SCC issue?
