### ISSUE TITLE
Install features behind proxy: http_proxy is not accepted with username and password

### ISSUE THREAD

**Issue by ByTe-ErRoR** [OpenLiberty/open-liberty#15017]
**Describe the bug**

When trying to install features behind a corporate proxy then the `featureUtility` has a problem to verify the proxy syntax. The  same proxy works in many case but not for open liberty to install features on the kernel version.

```
CWWKF1400E: The format of the <my proxy settings> http_proxy environment variable is invalid. Ensure that the http_proxy variable is in the http_proxy=http://<proxy-host>:<proxy-port> format.
```

**Steps to Reproduce**
1. Set the proxy variable `http_proxy` with a user name and password `http://<username>:<password>@<sever>:<port>`
1. run the command `featureUtility installFeature <a feature>`

**Expected behavior**
That no error message appears and a http proxy is accepted with username and password syntax.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.11 Kernel
 - Java Version:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

**Comment by hermankailey** [comment]
Hi thanks for opening this issue it will allow us to clarify the use cases for featureUtility. We believe this is the intended behavior for featureUtility. We did not wish to encourage sending a password over an http connection so in order to use a proxy with a password the user must use the https_proxy variable. Below are some example use cases for the supported proxy variable formats:

https_proxy=https://user:password@proxy-server:3128
http_proxy=http://proxy-server:3128

**Comment by BlueSKySec** [comment]
Unfortunately, this doesn't work.

Environment:

CentOS Linux release 8.3.2011
OpenLiberty 20.0.0.12
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)

Settings:

declare -x http_proxy="http://SomeUser:SomePass@someProxy:80"
declare -x https_proxy="http://SomeUser:SomePass@someProxy:80"
declare -x no_proxy="10.130.130.111,localhost"

FYI, for security reasons, I changed User / Pass & hosts.

Someone care to elaborate?

TIA

Gregor
