### ISSUE TITLE
Test Failure: com.ibm.ws.request.probe.fat.RequestProbeTest.testReqTimingDynamicDisable

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#15168]
RTC 280114

```
testReqTimingDynamicDisable:junit.framework.AssertionFailedError: 2020-12-02-03:24:56:349 [Unexpected FFDC reporting java.lang.NullPointerException was found (count = 1): C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\ProbeServer\logs\ffdc\ffdc_20.12.02_03.24.39.0.log
>------Start of DE processing------ = [12/2/20, 3:24:39:130 GMT]
>Exception = java.lang.NullPointerException
>Source = com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl$3
>probeid = 378
>Stack Dump = java.lang.NullPointerException
>    at com.ibm.ws.request.timing.RequestTimingService.serverStopping(RequestTimingService.java:406)
>    at com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl$3.run(RuntimeUpdateManagerImpl.java:373)
>    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>    at java.base/java.lang.Thread.run(Thread.java:834)
]
```

https://github.com/OpenLiberty/open-liberty/blob/77c39dbe3d666748fbf4ec0057a689e8416ce796/dev/com.ibm.ws.request.timing/src/com/ibm/ws/request/timing/RequestTimingService.java#L406

**Comment by fmhwong** [comment]
The NPE can be easily fixed by doing a null check but the question is why it `slowRequestProbeExt` is not set.

**Comment by pgunapal** [comment]
This is a test bug, where there is a timing issue in the com.ibm.ws.request.probe.fat.RequestProbeTest.testReqTimingDynamicDisable test case, where the test case makes a server config update, which removes the requestTiming feature. The server config update takes awhile, and the test case does not wait long enough for the server config update success message and proceeds on to shut down the server. During the shut down of the server, the server config update happens and removes the requestTiming feature, so when the server is trying to clean up all the SlowRequestTimingProbeExtension objects in the RequestTimingService.serverStopping() method, it causes a NPE, since all requestTiming objects are already removed during the server config update. The fix is to make sure the test case waits longer for the server config update message to appear before proceeding.
