### ISSUE TITLE
Failing basic registry groups merge

### ISSUE THREAD

**Issue by nehapa08** [OpenLiberty/open-liberty#15363]
We are trying to create a new user-'newuser' in BasicRegistry and adding it to the already created group-'FTM Administrator' using configDropins, but configuration for `<group>` is not getting merged and we are running into following error-

[ERROR ] CWWKS3105E: Multiple groups with the name 'FTM Administrator' are defined. The entries for this group will not be used.

server.xml snippet for basic registry-
`<basicRegistry id="basic" realm="BasicRealm">  
     <user id="adminUser" name="fxhadmin" password="${env.FXH_EPASS}"></user>
        <group id="admin" name="FTM Administrator">                                     
          <member id="adminUser" name="fxhadmin"/>
        </group>
   </basicRegistry>                             
`

add-user.xml snippet
`<server description="Default server">
    <basicRegistry id="basic" realm="BasicRealm">                       
        <user id="user" name="newuser" password="newpass"></user>
        <group id="admin" name="FTM Administrators">                                     
          <member id="user" name="newuser"/>
        </group>
    </basicRegistry>     
</server>`

Ideally the config for basic-registry should merge and group with id=admin, should have two users added. But its failing.

Liberty verion-
Product name: WebSphere Application Server
Product version: 20.0.0.12
Product edition: BASE

**Comment by irobins** [comment]
The same behaviour occurs in a single cofig file e.g.
Your understanding is consistent with https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_confg_element_merging_rule.html

I'm not sure why a merge doesn't occur for
    <basicRegistry id="basic" realm="BasicRealm">
        <user name="admin" password="password" id="adminUser"/>
        <group name="FTM_Administrators" id="admin">
                	<member name="admin" id="adminUser"></member>
        </group>

    </basicRegistry>
    <basicRegistry id="basic" realm="BasicRealm">
        <user name="newadmin" password="newpassword" id="newadminUser"/>
        <group name="FTM_Administrators" id="admin">
            	<member name="newadmin" id="newadminUser"></member>
        </group>
    </basicRegistry>

Desired behaviour, per doc https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_confg_element_merging_rule.html , is for the 2 members to be merged into "FTM Adminstrators" group.

**Comment by brenthdaniel** [comment]
This issue could potentially prevent successful merging of several different Liberty configuration elements. It is likely that the only time an error would be issued is this particular case with basicRegistry. 

It's possible when this is fixed that it could cause configurations that were working to run into problems because configuration that was previously ignored will now be merged correctly. The affected elements and attributes are:

-basicRegistry
  - user
  - group
- authFilter
   - webApp
   - requestUrl
   - remoteAddress
   - host
   - userAgent
   - requestHeader
   - cookie
- auditFileHandler
   - events
- openIdConnectProvider
   - scopeToClaimMap
- fileRegistry
   - baseEntry
- ldapRegistry
   - failoverServers
   - registrBaseEntry
   - loginProperty
   - ldapEntityType
- federatedRepository
   - realm
   - supportedEntity
   - extendedProperty
- keyStore
   - keyEntry
- ssl 
  - outboundConnection
- mailSession
  - property
