### ISSUE TITLE
The metatype trustStoreRef in jwtBuilder does not have meaning and should be removed

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#15416]
The metatype trustStoreRef in jwtBuilder for jwt-1.0 feature does not have meaning and should be removed

**Comment by ayoho** [comment]
The `jwtBuilder` element is now capable of building JWEs, and in doing so needs access to a key management key. We've implemented that by pulling the key management key from the trust store that's configured via the `trustStoreRef` attribute in the `jwtBuilder`, so that attribute is now necessary. Since it's a needed attribute now, I'm going to close this issue.

**Comment by chunlongliang-ibm** [comment]
OK, can you update metatype to c;early state the purpose of the attribute

**Comment by ayoho** [comment]
Sure, we can look at doing that as part of https://github.com/OpenLiberty/open-liberty/issues/15431.
