### ISSUE TITLE
Update mpReactiveMessaging-1.0 so that it supports MicroProfile 4.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15440]
This may be a simple as tolerating mpConfig-2.0. However, I have a feeling that it will also need to force the correct version of the MP Context Propagation API, which is an indirect dependency from the concurrent-1.0 feature.

**Comment by Azquelt** [comment]
This requires changes to the implementation, particularly `ConnectorConfig` which implements the `Config` interface which has changed in MP Config 2.0.

Also, at the moment, we can't update to a newer version of smallrye-reactive-messaging past the point that they introduced a dependency on vertx.

**Comment by tevans78** [comment]
Seems likely that a new version is required to support MicroProfile 4.0. So this work may be covered under https://github.com/OpenLiberty/open-liberty/issues/9243

**Comment by Azquelt** [comment]
I'm not sure why a new version of the spec (which is what seems to be suggested in #9243) would be required to support MicroProfile 4.0.

**Comment by Emily-Jiang** [comment]
@Azquelt with vert.x dependency, can we still pull in just not support `@Blocking`?

**Comment by Emily-Jiang** [comment]
We can create a branch off SmallRye RM to update its dependency on MP Config from 1.x to 2.0. We can then consume the new jar to get OL's MP RM impl to work with MP 4.0.

**Comment by Azquelt** [comment]
I prototyped a few ways of doing this but none of them were satisfactory.

**Update to the latest release of smallrye reactive messaging**: This is non-starter, smallrye reactive messaging has added many new features since we last consumed an update for it. We'd be exposing users to all of those changes when they updated liberty despite not changing their server.xml.

**Create a 1.x branch in smallrye reactive messaging starting at the 1.1.0 release**: Closer, but the 1.1.0 release of smallrye reactive messaging contains incompatible changes to at least the `Message` API class. In particular, a `Message` implementation must override the default implementation of the `getAck()` method for acknowledgement to work correctly and this method doesn't exist in the 1.0 release of the API.

**Create a 1.0.x branch in smallrye reactive messaging starting at the 1.0.8 release**: From a technical perspective, this would work. However it's not possible to have an implementation of `ConnectorConfig` which works with both MP Config 1.x and 2.0 due to the references to the new `ConfigValue` interface (required for 2.0 and not present in 1.x). This would mean we'd want to make a new release (1.0.9) which dropped support for MP Config 1.x and required 2.x which isn't an acceptable change for a micro release.
