### ISSUE TITLE
GA BLOG - MP Config 2.0 blog

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#15611]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this newly released feature/function of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
   
   Short feature name (eg websockets-1.0): 

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by Joseph-Cass** [comment]
For reference, a lot of the material is similar to that found in the [Beta blog post for mpConfig-2.0](https://openliberty.io/blog/2020/10/27/microprofile40-jakartaee9-beta-200012.html#conf) which was based on the [BETA BLOG - MicroProfile Config 2.0 issue](https://github.com/OpenLiberty/open-liberty/issues/14519)

For the following Epic: https://github.com/OpenLiberty/open-liberty/issues/11016

I started re-writing out all the bullet points, but realised it would be easier to highlight any changes from the existing beta blog post:

-  In the first sentence, `ConfigSoures` could link to the JavaDoc: https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/spi/ConfigSource.html
> MicroProfile Config enables application configuration from different locations ([ConfigSources](https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/spi/ConfigSource.html)). 
    
- For simplicity and readability, I think it may be worth defining some config property values at the start of the `Functional Changes` section (before any bullet points) and using those values throughout the examples. We could say:

> The examples below use the following config property values defined in a `META-INF/microprofile-config.properties` file on the classpath:
> ```
> server.host=example.org
> server.port=9080
> server.url=http://${server.host}
> %test.server.name= example.test.org
> ```

-  The first `Functional Changes` bullet point (for `@ConfigProperties`) could have a little more detail:

> Provides a way to retrieve a number of related config property values, with a shared specified prefix, into a CDI bean using the @ConfigProperties annotation.
> ```
> @ConfigProperties(prefix="server")
> @Dependent
> public static class ServerDetailsBean {
>    String host;
>    int port; 
> }
> ```
> This bean can then be injected into another class:
> ```
> @Inject
> @ConfigProperties
> ServerDetailsBean serverDetails;
> ```
> Where the config property values can be easily retrieved within the class the bean was injected into with:
> - `serverDetails.host` which would retrieve a `String` of the config property defined as `server.host`, returning `example.org`
> - `serverDetails.port` which would retrieve an `int` of the config property defined as `server.port`, returning `9080`

    
-  The second `Functional Changes` bullet point (for `ConfigValue`) uses a programmatical example. We should probably use a CDI example:

> ```
> @Inject
> @ConfigProperty(name="server.host")
> ConfigValue serverNameConfigValue;
> ```
> calling `serverNameConfigValue.getSourceName()` would return `PropertiesConfigSource[source=file:/<path-to-file>/META-INF/microprofile-config.properties]`

-  The third `Functional Changes` bullet point (for `Property Expression`) could be simplified if we've already defined the config property values:

> Supports [Property Expressions](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#property-expressions), which provide a way to set and expand variables in property values using the `${}` syntax. For example, the config property `server.url` defined as `http://${server.host}` will be resolved to `http://example.org` since `server.host` is defined as `example.org`
> 
> Previous working configurations might behave differently if the configuration in use contains values with Property Expressions syntax.

-  The fourth `Functional Changes` bullet point (for `Optionalxxx` Converters) needs updating to an example config property (if we decide to use them):

> ```
> @Inject
> @ConfigProperty(name = "server.port")
> private OptionalInt optionalServerPort;
> ```

- The current links to the spec all link to a "Release Candidate" (RC) version of the spec. These need updating to the released version. i.e. the link for Property Expression is currently:
    - https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#property-expressions
and needs updating to
    - https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#property-expressions

- We're in the progress of developing a "breaking changes" page in the docs, [discussed here](https://github.com/OpenLiberty/docs/issues/3443#issuecomment-780216141). It may be worth keeping an eye out for that page, and linking to it if it is released before the blog.

Thanks :) !

**Comment by Joseph-Cass** [comment]
For readability, here's what the beta blog + new suggestions would look like (Note: I haven't copied across all the links from the beta blog post- these should still be included):

**New capabilities (@ConfigProperties, ConfigValue api, Config Profiles, and more) in MicroProfile Config (MicroProfile Config 2.0)**

MicroProfile Config enables application configuration from different locations ([ConfigSources](https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/spi/ConfigSource.html)). MicroProfile Config 2.0 in Open Liberty consumes SmallRye’s implementation of the specification.

MicroProfile Config 2.0 is a major version release (from 1.4) which introduces Functional and API/SPI changes.

**Functional Changes**

The examples below use the config property values defined in this example `META-INF/microprofile-config.properties` file (A [default ConfigSource](https://openliberty.io/docs/21.0.0.1/external-configuration.html#_default_configsources)) which would be found on the classpath:
```
server.host=example.org
server.port=9080
server.url=http://${server.host}
%testing.server.name= example.test.org
```

- Provides a way to retrieve a number of related config property values, with a shared specified prefix, into a CDI bean using the `@ConfigProperties` annotation.

```
@ConfigProperties(prefix="server")
@Dependent
public static class ServerDetailsBean {
   String host;
   int port; 
}
```
This bean can then be injected into another class:
```
@Inject
@ConfigProperties
ServerDetailsBean serverDetails;
```
Where the config property values can be easily retrieved within the class the bean was injected into with:
     - `serverDetails.host` which would retrieve a `String` of the config property defined as `server.host`, returning `example.org`
     - `serverDetails.port` which would retrieve an `int` of the config property defined as `server.port`, returning `9080`

- Allows you to easily determine which was the "winning" ConfigSource (the ConfigSource with the highest ordinal) for a specified config property via ConfigValue. A ConfigValue object holds information about the config property name and value, the name of the ConfigSource from where the config property was loaded and the ordinal of that ConfigSource. You can retrieve a ConfigValue object for a given config property by CDI injection:

```
@Inject
@ConfigProperty(name="server.host")
ConfigValue serverNameConfigValue;
```
calling `serverNameConfigValue.getSourceName()` would return `PropertiesConfigSource[source=file:/<path-to-file>/META-INF/microprofile-config.properties]`

- Enables an application to include configuration for different environments and development stages while only one of them is active (e.g. dev, test, prod) using [Config Profiles](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#configprofile). The Config Profile can be specified using the mp.config.profile property, which can be set in any of the configuration sources. Once it is set, the corresponding properties associated with the active profile are used. The value can also be set at application start-up, for example:
```
java -jar myapp.jar -Dmp.config.profile=testing
```
The mp.config.profile property works on both the property level and config file level:

On the property level profiles can be used by setting config property values specific to the selected profile. For example, with `mp.config.profile` set to `testing`, the config property `server.name` would resolve to `example.test.org`

If `mp.config.profile` was not set, `server.name` would resolve to `example.org`.

On the config file (`microprofile-config.properties`) level the property `mp.config.profile` also activates the corresponding `microprofile-config-<mp.config.profile>.properties` with `microprofile-config.properties` as the fallback.

- Supports [Property Expressions](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#property-expressions), which provide a way to set and expand variables in property values using the `${}` syntax. For example, the config property `server.url` defined as `http://${server.host}` will be resolved to `http://example.org` since `server.host` is defined as `example.org`

Previous working configurations might behave differently if the configuration in use contains values with Property Expressions syntax.

- Two new methods have been introduced to Config.java:

    - `List<T> Config.getValues(String propertyName, Class<T> propertyType)`

    - `Optional <List<T>>Config.getOptionalValues(String propertyName, Class<T> propertyType)`

The methods have been added to enable you to retrieve multi-valued config property values as lists instead of arrays. The methods return the resolved property values with the specified propertyType for the specified propertyName. For example, `config.getOptionalValues("server.port", Integer.class).toString()` would return `Optional[[9080]]`

- OptinalInt, OptionalLong and OptionalDouble are now provided as built-in Converters. The new Converters can be used like any of the other built-in Converters, converting injected config property values to a defined type:
```
@Inject
@ConfigProperty(name = "server.port")
OptionalInt optionalServerPort;
```

**Incompatible changes**
If you move up from MicroProfile Config 1.x to 2.0, please take care of the following incompatible changes:

ConfigSource.getPropertyNames is no longer a default method. The implementation of a ConfigSource must implement this method.

Previous versions of the specification would not evaluate Property Expressions. As such, previous working configuration may behave differently (if the used configuration contains values with Property Expressions syntax). Property Expressions can be disabled by setting the property mp.config.property.expressions.enabled with the value of false.

Empty values or other special characters are no longer valid Config property values. This means that Config.getValue(String propertyName, Class<T> propertyType) will never return null; a NoSuchElementException will be thrown if either a Config property value is not defined, is defined as an empty string, or its converter returns null. In the previous release, the empty value was returned as an empty value. For more information, please refer to this section of the spec.

To enable the new beta features in your app, add them to your server.xml:
```
<featureManager>
   <feature>cdi-2.0</feature> <!-- required for supporting configuration injection -->
   <feature>mpConfig-2.0</feature>
</featureManager>
```
For more information:

Release Notes for MicroProfile Config 2.0

MicroProfile Config 2.0 Milestone

**Comment by jakub-pomykala** [comment]
Closing as this is now live [here](https://openliberty.io/blog/2021/03/31/microprofile-config-2.0.html)
