### ISSUE TITLE
AroundConstructTestServlet.testInterceptorNotCalledTwice does not pass

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15711]
https://github.com/OpenLiberty/open-liberty/blob/1d160bafc1969d4bd2a5a87f763b20a220704664/dev/com.ibm.ws.cdi.ejb_fat/test-applications/aroundConstructApp.war/src/com/ibm/ws/cdi12/test/aroundconstruct/AroundConstructTestServlet.java#L143

`testInterceptorNotCalledTwice` was previously not properly marked as a `@Test` and so has not been run in a while. Don't know how long. When I re-enabled it, it fails, the constructor interceptor appearing to be run twice.

**Comment by benjamin-confino** [comment]
It looks like it failed because the constructor is being called once for Ejb and once for StatelessEjb in the same request. Since both are annotated `@Intercepted` and since this code block calls them both 

```
    protected void before() {
        ejb.doSomething(); // need to actually use the injected bean, otherwise things go a bit funny
        stateless.doSomething();
    }
```

I think the problem is in the test. I'd like to run this past the team, but I think the solution could be to ensure the logger includes which class is being intercepted for constructor interceptor.
