### ISSUE TITLE
Provide support for Elastic Common Schema

### ISSUE THREAD

**Issue by awiradarma** [OpenLiberty/open-liberty#15727]
**Is your feature request related to a problem? Please describe.**
It's always challenging to perform log analysis across multiple log sources, even using log aggregator tools, because there is not a consistent set of fields that the different log sources adhere to. 

**Describe the solution you'd like**
A feature to generate Open Liberty logs that comply to  Elastic Common Schema (ECS) or at the very least, a published documentation or guide to help us map Open Liberty log fields to ECS

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by donbourne** [comment]
ECS reference at https://www.elastic.co/guide/en/ecs/current/index.html

**Comment by faandg** [comment]
@fmhwong could you elaborate why this was closed? There is no PR ref, is this implemented or rejected?

**Comment by fmhwong** [comment]
@faandg I presumed this was not needed anymore as there was no activities since 2021.  Reopening...

**Comment by donbourne** [comment]
I believe it's correct to close this issue as ECS and OpenTelemetry Semantic Conventions have converged into a single schema maintained by OpenTelemetry (see https://opentelemetry.io/blog/2023/ecs-otel-semconv-convergence/).  Our `mpTelemetry-2.0` feature (currently in 24009-beta) emits logs that adhere to the OpenTelemetry semantic conventions for logs.

We also have documented the fields in our JSON logging schema so that it would be easy for people to map Liberty's fields to new field names (for example, using jq).  See https://openliberty.io/docs/latest/json-log-events-list.html .

You can also use the server.xml `logging` element's `jsonFieldMappings` to rename json fields right in the server configuration.
