### ISSUE TITLE
Portable DataSource configured in application does not work 

### ISSUE THREAD

**Issue by hantsy** [OpenLiberty/open-liberty#15824]
As I know, JDBC driver as part of deps in an application should register a JDBC driver automatically and configured DataSource via web.xml or `@DataSourceDefinition` should work since Java EE 6 and EE 7. 

But I do not think they work in OpenLiberty till now(21.0.0.1).

And since Java EE 6, the application server should provide a default DataSource out of box via JNDI name `java:comp/DefaultDataSource`. This does not work if I do not configure a `DefaultDataSource` myself.

I am not a Java EE expert not sure if the above items are a must in the TCK.

Hope it works and simplifies the development work for developers. 

Currently, I maintained a simple [jakartaee8-starter-boilerplate](https://github.com/hantsy/jakartaee8-starter-boilerplate) to provide a simple template for the newbies to kickstart a Jakarta EE project.

But it seems to [start a Jakarta EE project on OpenLiberty is not easy when adding some db related sample codes](https://stackoverflow.com/questions/66077552/configure-default-data-source-for-arquillain-test-in-openliberty).

**Comment by frowe** [comment]
To your first point, creating a datasource via deployment descriptor or annotation does register the requested JDBC driver in jndi, however, you must configure the driver as a library so that the Liberty classloader can find it.  The EE specs do not require that you be able to bundle a JDBC driver in an EE application.
To your second point, the EE spec does require the app server provide a default datasource resource registered as java:comp/DefaultDataSource and Liberty does so.  However, the spec does not require that the app server provide a database out of the box, so Liberty does not.  You will need to obtain and configure the database of your choice and update the DefaultDataSource configuration to point to it.
