### ISSUE TITLE
header name case is being cached in server

### ISSUE THREAD

**Issue by ilam-natarajan** [OpenLiberty/open-liberty#15841]
I just observed header names are being cached(including case) in liberty server. 
if a header name is `all-small-case`
and in first hit, user sends it `all-Small-Case`, then even if an api intends to send `all-small-case` in response header, client gets "all-Small-Case"
after this, even if user sends `all-small-case`, server returns `all-Small-Case` to client.
looks like server caches the header name in first hit (along with the exact case that was sent in request).

I did not file this as a bug, because I know HTTP header names are supposed to be treated case-insensitive. 
I just wanted to understand if this case caching behavior is known/intentional.

If you would like an reproducible example

[start.zip](https://github.com/OpenLiberty/open-liberty/files/5946983/start.zip)

1.  mvn liberty:run
2. curl --location --request GET 'http://localhost:9080/system/properties' --header 'all-Small-Case: yes'
3. curl --location --request GET 'http://localhost:9080/system/properties' --header 'all-small-case: yes'

**Comment by wtlucy** [comment]
Hi @ilam-natarajan, thanks for providing the example - you're correct with your understanding that Liberty _caches_ the first header name (key) it receives, for performance reasons. Those cached header keys are created with whatever case we first encounter, but then subsequent lookups are case-insensitive. This behavior is intentional.

Reviewing HTTP channel classes like [BNFHeadersImpl](https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java), enabling HTTP channel logging along the lines of ```<logging  traceSpecification="HTTPChannel=all:GenericBNF=all:HTTPDispatcher=all"/>```, and searching for your header name can help to give an idea of how Liberty processes headers.

**Comment by ilam-natarajan** [comment]
thanks @wtlucy for the clarification. I will close the issue.
