### ISSUE TITLE
Openliberty Bootstrap Classload does not support multi release jars

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#16078]
**Describe the bug**
If a multi release jar is used as a boot jar (`type="boot.jar"`) the never versions of a resource won't be loaded.
The only known workaround so far is to set the bootstrap property `verifyJarSignature=true`.

**Steps to Reproduce**
Add a multi release jar with `type="boot.jar"` and `verifyJarSignature=false` (default value).
All newer versions of resources will simply be ignored and the java 8 version is loaded.

**Expected behavior**
Openliberty own classloader supports mullti release jar.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.1
 - Java Version: >= 9
 - server.xml configuration doesn't matter

**Additional context**
To give some context information we have written a logging feature using log4j 2 and are using java 8 until now.
Log4j 2 has multi release jars to be compatible with java 8 and newer java versions.
If we want to use java 11 the server only start if we set `verifyJarSignature=true`.

**Comment by tjwatson** [comment]
The enhancement to support this would need to happen in `com.ibm.ws.kernel.internal.classloader.JarFileClassLoader`.  The reason it works with `verifyJarSignature=false` is because that uses `com.ibm.ws.kernel.internal.classloader.BootstrapChildFirstURLClassloader` which extends `URLClassLoader` from the JVM that already has support for multi-release JARs.

Other JARs included in a user feature that get installed as bundles will also have support for multi-release JARs.  I have not confirmed if JARs configured as shared libraries or if JARs included in a application will support multi-release JARs.  If we are to support multi-release JARs for boot JARs then I think we should be consistent and make sure it is supported for the other JARs that can be configured and loaded by Liberty.

**Comment by tjwatson** [comment]
How are you configuring your logging feature?  Features that are not part of the Liberty project itself must be installed as a user or product extension.  The `type=boot.jar` is not supported in user/product extensions?  Where do you place your logging feature JARs to get them loaded as boot jars?

**Comment by jonasrutishauser** [comment]
The feature has to be installed manually. We create a zip having already the correct file structure such that it can be extract in an openliberty installation.
The jars are placed in the `lib` directory and the feature descriptor is placed in the `lib/platform` directory.
Then we simply have to define the `websphere.log.provider` bootstrap property.

**Comment by tjwatson** [comment]
The feature you are using happens to be using an internal `type=boot.jar` that generally is not available to supported product/user extensions.  It is unlikely we will focus effort to fixing this internal for this case.  That being said, if you want to take a look at solving the problem we can look at reviewing a PR to address the issue.
