### ISSUE TITLE
ID: authFilter element is missing from generated feature docs and has incorrect descriptions

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/open-liberty#16127]
**Describe the bug**
The Open LIberty autogenerated docs for the `authFilter` element, which is generated from [this metatype.properties file](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties) (and other files in the [com.ibm.ws.security.authentication.filter directory](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.security.authentication.filter)), has two issues:

1. The autogen is not pulling in the attribute descriptions from [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties). Instead, it pulls in a single description for all the attributes, "A unique configuration ID.". See [the authFilter autogen page](https://www.openliberty.io/docs/21.0.0.2/reference/config/authFilter.html) for example.
2. The `authFilter` configuration element has disappeared from all generated feature doc pages which previously included the element in the "Feature configuration elements". This bug occurred sometime between the 20.0.0.11 and 20.0.0.12 Ga releases. For example, see the [20.0.0.11 version of the MpJWT feature page](https://www.openliberty.io/docs/20.0.0.11/reference/feature/mpJwt-1.1.html), which displays the element, and any later version of the feature page, [for example 21.0.0.2](https://www.openliberty.io/docs/21.0.0.2/reference/feature/mpJwt-1.1.html), which do not. This is the case for all liberty features that use `authFilter` .

This information is not maintained by the docs team and is pulled in automatically from properties files in the Open Liberty repo.

**Steps to Reproduce**
See doc links above

**Expected behavior**
1. The authFilter autogen page should pull in the appropriate attribute descriptions that are specified in [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties).
2. all version of feature pages for feaures that use authFilter should display the authFilter element in the "Feature configuration elements" list.

**Diagnostic information:**
 - OpenLiberty DOCS Versions 20.0.0.12 and later (currently through 21.0.0.2)

**Additional context**
https://github.com/OpenLiberty/open-liberty/pull/14099 may be relevant @jvanhill @utle

**Comment by utle** [comment]
Hi @dmuelle,
We still have this problem with the latest build?

**Comment by dmuelle** [comment]
@utle for now, yes. The autogenerated docs are only built once for each release, so the most current version we have now is the 21.0.0.2 release, which is still missing `authFilter` on the feature pages. We won't have the new autogen version for 21.0.0.3 until sometime after GM. So if there have been recent changes, they won't show up until the doc is generated for 21.0.0.3

**Comment by jvanhill** [comment]
So the explanation for why this happens. The metadata for the `authFilter` element is in the `com.ibm.ws.security.authentication.filter` bundle. This bundle has dependencies on javax.servlet classes. This meant, that when I added support for EE9, this bundle needed to be transformed to create a new bundle (`io.openliberty.security.authentication.internal.filter`) with jakarta.servlet namespaces.

Only one of these bundles can / should be loaded at a single time and that is dependent on the level of the servlet feature being used. To correctly select the version of the bundle we require, two auto feaures were created. One for [EE 6/7/8](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.authFilter1.0.javaee.feature) and one for [EE9](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.authFilter1.0.jakarta.feature).

As part of this selection, all of the features that previously relied on the `com.ibm.ws.security.authentication.filter` bundle, no longer could directly rely on it. They needed to rely on the auto-feature loading it. Thus, a side-effect of no longer directly depending on that bundle is that the configuration for authFilter is no longer directly tied to these other features, such as `mpJwt-1.1`.

I am not sure what the fix is for this. The feature doc tool would need to look through all of the auto features and somehow determine if the features enabled by the primary feature, would enable the auto feature, and then it would have to include the configuration elements and attributes for the feature(s) spun up by the auto-feature. It might also have to consider any conflicts between multiple versions of an auto-feature (for example the jakarta and javaee versions) that might exist.

I also believe this is an issue for API/SPIs and perhaps javadoc as well that is included in auto features. I  don't think they get included.

@jhanders34 -are you aware of this issue? I assume many of our EE9 features are going to see this sort of behavior.

**Comment by jhanders34** [comment]
I have looked into this issue and I have a suggestion on how to resolve it.  I believe we should have a separate subbundle in the projects that just has the metatype OSGI properties in it.  This is similar to the com.ibm.ws.jdbc.metatype project and a couple of other projects that only have the metatype in them.  They did this for the same reason that we are hitting now I assume.  By doing a subbundle we do not need a separate project in open liberty for the metatype only and it can stay in the same project, but will be in a separate bundle that is not transformed.  Additionally you will need to update the feature definition to include the new bundle of course.

I did some analysis, and I believe that the list of bundles that are in auto features that have metatype that need this change are:

com.ibm.ws.ejbcontainer.security
com.ibm.ws.security.audit.file
com.ibm.ws.security.audit.source
com.ibm.ws.security.authentication.filter
com.ibm.ws.security.authentication.tai
com.ibm.ws.security.jaas.common
com.ibm.ws.security.jwt
com.ibm.ws.security.openidconnect.client
com.ibm.ws.security.openidconnect.server
com.ibm.ws.security.social
com.ibm.ws.security.spnego
com.ibm.ws.session
com.ibm.ws.session.cache
com.ibm.ws.session.db

**Comment by jhanders34** [comment]
In the end I went with a different approach for this issue to avoid having extra bundles.  I switched from using auto features to using private singleton features.  This has caused a separate issue with the all, beta and ga features packages.  @tjwatson and @cbridgha are working on a solution for those packages to allow for the code change to remain and get the desired behavior for those packages.
