### ISSUE TITLE
com.ibm.ws.security.mp.jwt.tai.MicroProfileJwtTAI corrupts http response

### ISSUE THREAD

**Issue by MichaelNesterenko** [OpenLiberty/open-liberty#16538]
**Describe the bug**
In our application we need to support both Basic and JWT authentication.

Following server.xml configuration is used:
```
<trustAssociation failOverToAppAuthType="true" />
<mpJwt
	id="jwt"
	issuer="someIssuer"
        ....
/>
```
Due to failOverToAppAuthType setting after TAI authentication fails flow proceeds to other authentication methods. And subsequently it uses Basic authentication which successfully authenticates request.

Problem is with following method:
```
MicroProfileJwtTAI.handleMicroProfileJwtValidation(HttpServletRequest, HttpServletResponse, MicroProfileJwtConfig, String, boolean)
```
It is unable to parse Authorization header like `Basic dXNlcjpwYXNz` and when JWT creation fails it updates HttpServletResponse with response code 401 and sets header `WWW-Authenticate`.

At the end payload from downstream servlet is returned (subsequent basic authentication succeeds) with http status 401 and `WWW-Authenticate` header.

Need to avoid calling MicroProfileJwtTAI when Authorization header is not Bearer or avoid updating http response in case of unexpected Authorization header value.

**Steps to Reproduce**
Submit http request with Basic authentication header

**Expected behavior**
Response has status 200 and does not contain WWW-Authenticate header

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.3
 - Java Version: openjdk version "11.0.10" 2021-01-19

**Additional context**

**Comment by teddyjtorres** [comment]
Thank you for reporting your issue.

When the mpJwt-1.x feature is enabled, a valid JWT is required by default. This is documented in,

https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-configuring-microprofile-json-web-token

> Optional: Configure Liberty to apply the mpJwt-1.0 feature only to applications that have a login method name of MP-JWT.
By default, if the mpJwt-1.0 feature is configured, all authorized requests must include a valid JWT in the HTTP header. To modify the default behavior to require the JWT authentication token in some applications only, add the ignoreApplicationAuthMethod="false" configuration attribute to the <mpJwt> element in the server.xml file. Then, configure the application in one of two ways:
The application has an @LoginConfig annotation with the MP-JWT login method declared as the authentication method.
For example, @LoginConfig(authMethod = "MP-JWT", realmName = "MP-JWT").
>
> The web.xml file for the application has a declaration for the MP-JWT authentication method in the login-config element.
>
> For example, <login-config> <auth-method>MP-JWT</auth-method> <realm-name>MP-JWT</realm-name></login-config>.

Setting failOverToAppAuthType in the trustAssociation element does not override that behavior, since it is up to each TAI implementation to determine whether the request is continued or not. Some TAIs may issue a 401. This particular TAI does not allow continuing the request if there is no valid JWT.

One alternative is to use an authFilter with the mpJwt element. For example, an authFilter can be created to match requests that have an Authorization header with the Bearer scheme,

https://www.ibm.com/docs/en/was-liberty/nd?topic=configuration-mpjwt#authFilter/requestHeader

It would look like,

```
  <mpJwt
	id="jwt"
	issuer="someIssuer"
        ....
        authFilterRef="myAuthFilter"
  />
  <authFilter id="myAuthFilter">
    <requestHeader id="bearerContainingRequests" matchType="contains" name="Authorization" value="Bearer" />
  </authFilter>
```

Other authFilter options are described in https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-authentication-filters.

Please let us know if you have any issues using the authFilter.

Regards,

Teddy

**Comment by MichaelNesterenko** [comment]
Hi teddyjtorres,

Yes authFilter fixed this behavior, thanks for help!

**Comment by teddyjtorres** [comment]
You're welcome. We're glad to help.
