### ISSUE TITLE
Improve featureUtility performance with remote repository

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/open-liberty#16700]
FeatureUtility can take a long time to resolve features when using a remote repository with a slow network. 

Areas that could be improved: 
1.  Check and retrieve more than one checksums from maven repository
2. Check more than one artifact urls for missing features

**Comment by jdmcclur** [comment]
3. Look into caching assets instead of jsonobjects and caching per file so a file doesn't need to be parsed/deserialized more than once. This won't help with a slow network, but will speed things up.
https://github.com/OpenLiberty/open-liberty/blob/ab5f0ec8ce73c63f5a92a2e307e34c27d66c54d2/dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/SingleFileClient.java#L66

**Comment by jdmcclur** [comment]
4. Download more than 1 file at once - https://github.com/OpenLiberty/open-liberty/blob/5e6910dd459f798a95f210f7e4d9868d01bfe4f2/dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java#L100

**Comment by jjiwooLim** [comment]
5. Changing SingleFileRepositoryConnection to cache the client between calls to createClient would significantly reduce the json parsing we do. It looks like the SingleFileClient class already detects changes to the underlying file and repress as necessary so I think this would be safe:
 
https://github.com/OpenLiberty/open-liberty/blob/43eeef190f08cb845850d8bad1b21ab3c88d5b54/dev/com.ibm.ws.repository/src/com/ibm/ws/repository/connections/SingleFileRepositoryConnection.java#L39

**Comment by jjiwooLim** [comment]
6. Looking at the feature.json file it seems that the json contains the sha256 of the downloaded esa file so there is no need to download the sha hash from maven central because we can already validate the download using the json content.
