### ISSUE TITLE
What should be in the default server template for open liberty

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#169]
For Open Liberty the default server template configures jsp-2.3 and nothing else. For WebSphere Liberty the default server template varies, but tends to support the biggest feature possible, so javaee-7.0 or webProfile-7.0 depending on the image.

Question is what should we do for Open Liberty. It would be good to get this right from the get go.

Perhaps we should provide multiple templates so you can do --template=javaee7 --template=webProfile7 to provide a choice.

**Comment by garypicher** [comment]
I definitely like the idea of offering alternate templates, but we still need to pick a default.

I'm so torn on this...  I, personally, like the minimalist approach of jsp-2.3, and I worry that making something like javaee7 the default defeats the purpose of features and takes the focus off of the composeable and lightweight nature of the app server.

But I feel like my reasons for preferring this are not necessarily well grounded.  Do I really want someone to drop in their application and have it not work due to a missing feature, simply because I get offended at loading code I don't need?  Probably not.

So I think the "biggest feature possible" approach is probably correct, despite my personal preference.

Regardless of what we pick, I definitely like offering a handful of other options as alternate templates.

**Comment by NottyCode** [comment]
I know what you mean. There is a downside to choosing javaee-7.0 as the default. It requires a keystore to be configured with either a password or a keystore. If you don't have that it doesn't work, so you can't get an out of the box user experience. This is because the ORB (required for remote EJB) needs the keystore and blocks app startup until there is one. We require a password for the keystore because default keystore passwords are a bad bad bad idea for security, and providing a default certificate is equally bad practice.

This is basically the tradeoff for getting security right and ease of use.

webProfile-7.0 doesn't have that downside, you just wont get https until you configure the keystore but the applications will otherwise start. I think webProfile-7.0 is a better fit for everything.

Another option would be microProfile-1.2.

**Comment by ewhoch** [comment]
Is it fair to think a familiar user wouldn't care about this? Or if they did, it would be to used as a command line shortcut to setup a different default server template direct from the command line and maybe save a visit to the server.xml after creation.

If someone is unfamiliar, than the server start/run/create is going to have a few purposes. It brings up the concepts of the folder structure of a server (wlp/usr/server), server name == folder name, and server.xml being config. 

If we're trying to make the second scenario easier then a sensible goal could be something like making the most full-featured template that doesn't require touching the server.xml.

**Comment by garypicher** [comment]
I didn't realize javaee-7.0 requires manual config, which is a big no-no for a default.  So scrap that.

I think that webProfile-7.0 and microProfile-1.2 are compatible, so could we include both?

Alternately, I like Erik's basic goal of "making the most full-featured template that doesn't require touching the server.xml", but I worry that the resultant list of features would be long and messy looking.  I personally find a long feature list to be unappealing, but maybe that's just me?

**Comment by alexmulholland** [comment]
I have seen too many liberty configurations that include unused many features, simply because they were in the default server config.  Most developers are familiar with adding components to a servlet engine; this approach exploits one of the core benefits of liberty (you can have a full integrated/tested EE7 stack _but you don't have to_) and it is a shame that many people don't discover that because of a 'full stack' default. I would trust the ingenuity of folks who use open source and go with the existing JSP default :-)

**Comment by NottyCode** [comment]
@alexmulholland that is almost an argument for just going with servlet, or nothing.

**Comment by alexmulholland** [comment]
@NottyCode Yes :) servlet may be a better choice than JSP.  I wouldn't go with no features though.

**Comment by kwsutter** [comment]
I can see both ways -- either providing a "complete" stack to allow most apps to work out of the box, or providing a "minimalist" stack to show that we can grow as needed.  Definitely don't go with javaee-7.0 as the default since that requires additional configuration to be usable.  I guess I would go with servlet or jsp as the default since it would most directly compete against the Tomcat's of the world.  And, then with the proper comment block in the template, we can direct them to the full list of features available to them.

**Comment by ewhoch** [comment]
Would we be open to anything more radical? We can minify a server in a few seconds, is there a reason not to have something like a landing page with a few common image types at the top (zero, minimal, everything), allow fine-grained selection below it, and make it a dynamic system where we build them on request (and cache for future request).

**Comment by aguibert** [comment]
Closing this issue since it looks like a resolution was reached months ago.
