### ISSUE TITLE
Derby JDBC Driver - breaking change

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#16951]
When trying to upgrade to the latest Derby JDBC driver for testing we get the following error:

```
CWNEN1006E: The server was unable to obtain an object for the jdbc/dbRotation binding with the javax.sql.DataSource type. 
The exception message was: java.sql.SQLNonTransientException: 
DSRA4000E: No implementations of org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource40 are found for dataSource[default-0] with library dbRotationLib. 
The name or location of JDBC driver JAR files might be incorrect or inaccessible. 
Searched in: [/Users/kyleaure/git/open-liberty/dev/build.image/wlp/usr/shared/resources/jdbc/derby.jar]. 
Searched under packages: [org.apache.derby.jdbc]. 
```

The location of the Connection implementation classes has changed:
```
10.11.1.1 => 10.15.2.0
org.apache.derby.jdbc.* => org.apache.derby.impl.jdbc.*
```

We will have to figure out what driver version this changed in and make an update to the helper.

**Comment by KyleAure** [comment]
FYI @mswatosh

**Comment by mswatosh** [comment]
I believe this change was part of switching derby to use the Java Module System, for 10.15, but that version no longer supports java 8, so we can't use it as our default testing version. Since we no longer support java 7, it's possible we could move up to derby 10.14. 

I opened Issue #16968 to update the JDBC 4.3 tests to use derby 10.15, since those run on java 9+.

**Comment by KyleAure** [comment]
Close in favor of #16968
