### ISSUE TITLE
Investigate ELFactoryWrapperForCDI for Expression Language 4.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#17223]
The ELFactoryWrapperForCDI class resides in the io.openliberty.jakarta.expressionLanguage-4.0 project. I'd like to see if this is still necessary for CDI/EL integration or if something else can be done here?

**Comment by pnicolucci** [comment]
@volosied  have you had any time to investigate this one?

**Comment by volosied** [comment]
Not yet.  Thank you for reminding me about this one. I will look at this the following week.

**Comment by volosied** [comment]
Useful links:

ELFactoryWrapperForCDI: https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/io.openliberty.jakarta.expressionLanguage.4.0/src/com/ibm/wsspi/el/ELFactoryWrapperForCDI.java

CDI WrappedELExpressionFactory Impl: https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.cdi.web/src/com/ibm/ws/cdi/web/impl/el/WrappedELExpressionFactory.java

JSP References:  

- Service Reference: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java#L96 

- Reference: Set https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java#L137-L139

- https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java#L157

**Comment by volosied** [comment]
Current thoughts -

**Option 1)**  Delete  the ELFactoryWrapperForCDI interface and find some other solution here.   

I think we could do with just the implementation class, as suggested below?

- Per the [spec (Table 112.7)](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html): `The name of the interface that this service is registered under. This name must be the fully qualified name of a Java class. For example, org.osgi.service.eventadmin.EventHandler. The specified Java class should be an interface rather than a class, however specifying a class is supported. `

The current files look like so: 

 Within OSGI-INF/com.ibm.ws.cdi.web.el.WrappedELExpressionFactory.xml : 

```
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="com.ibm.ws.cdi.web.el.WrappedELExpressionFactory" immediate="true">
  <property name="service.vendor" type="String" value="IBM"/>
  <service>
    <provide interface="com.ibm.wsspi.el.ELFactoryWrapperForCDI"/>
  </service>
  <implementation class="com.ibm.ws.cdi.web.impl.el.WrappedELExpressionFactory"/>
</scr:component>
```

 Within com.ibm.ws.jsp.jar/OSGI-INF/com.ibm.ws.jsp.webcontainerext.JSPExtensionFactory.xml :

`<reference name="ExpressionFactoryService" cardinality="0..1" interface="com.ibm.wsspi.el.ELFactoryWrapperForCDI" bind="setExpressionFactoryService" unbind="unsetExpressionFactoryService" policy-option="greedy"/>`

I would need to confirm with an OSGI SME, though for the impl class approach only.  However,  we would be changing this reference in `com.ibm.ws.jsp` and that would affect multiple features (jsp-2.2, jsp-2.3, el-2.2, el-3.0, etc) , and there might be unintended consequences.  I would still try, but  I'm thinking it's better to go with option 2. 

**Option 2)** Keep ELFactoryWrapperForCDI. 

- We have this class duplicated in 3 API EL locations
   - 2.2, 3.0, and 4.0
   - Create a new bundle for this common EL class, and we could have cleaner bundles 
	- Move to another bundle?  Possible Candidates are
		- com.ibm.ws.cdi.web 
		- com.ibm.ws.jsp
		- com.ibm.ws.webcontainer
       - Another item to think about is when the related bundles (such as com.ibm.ws.cdi.web.jakarta containing the impl) are loaded ( with cdi & servlet): See the following auto feature: https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-servlet5.0.feature#L2-L7
