### ISSUE TITLE
401 stutus returned without any error messages in server logs

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#17613]
I have an RS config that is not generating a failure message when the status returned is 401.
```
	<openidConnectClient
		id="SignES384Encryptnone"
		scope="openid profile"
		clientId="client01"
		clientSecret="{xor}LDo8LTor"
		mapIdentityToRegistryUser="true"
		httpsRequired="false"
		redirectToRPHostAndPort="http://localhost:${bvt.prop.security_3_HTTP_default}"
		authFilterRef="authFilterES384none"
		signatureAlgorithm="ES384"
		trustStoreRef="trust_allSigAlg"
		trustAliasName="es384"
		sslRef="ssl_allSigAlg"
	>
	</openidConnectClient>		
```

The following lines were missing: 
```
		inboundPropagation="required"
		issuerIdentifier="client01"
		audiences="client01"
```

The jwt was not valid because of the issuer and audience, but, the only way to determine that was to dig through the trace (if you had it enabled)

We need something logged in messages.log to indicate why we're getting the 401.
I don't think this has anything to do with JWE or the new signature algorithms.

**Comment by c00crane** [comment]
[noMsg.zip](https://github.com/OpenLiberty/open-liberty/files/6688875/noMsg.zip)

**Comment by jimmy1wu** [comment]
fixed in https://github.com/OpenLiberty/open-liberty/pull/18386

401 occurred because removing those 3 lines sets the `inboundPropagation` value to `none`, which requires an auth and token endpoint (or discovery endpoint) to be set. error messages have been added to these cases.

putting back the `inboundPropagation="required"` will show the appropriate error messages for the issuer and audience.
