### ISSUE TITLE
Openliberty leaks memory when @ConfigProperty is called in a loop forever

### ISSUE THREAD

**Issue by vignesh-arjunan** [OpenLiberty/open-liberty#17665]
```java
@Startup
@Singleton
public class MyStartupBean {

     @Resource
     private ManagedExecutorService mes;

     @Inject
     @ConfigProperty(name = "myProperty")
     private Provider<Integer> myProperty;
   
    @PostConstruct
    public void init() {
        System.out.println("in init");
        mes.execute(() -> {
            while(true) {
                int myInt = myProperty.get();
                //Thread.sleep(100);
            }
        });
    }
}
```

too many org.jboss.weld.contexts.CreationalContextImpl objects in the heap until we run out of memory

**Comment by tevans78** [comment]
@vignesh-arjunan Which version of MP Config are you using?

**Comment by vignesh-arjunan** [comment]
mpConfig-1.3

**Comment by tevans78** [comment]
@vignesh-arjunan This is actually working as designed from a CDI point of view; Each time you call `Provider.get()` a new instance of a `@Dependent` scoped bean is created. Dependent scoped beans are retained until the bean they are dependent on is destroyed (your EJB in this case).

Instead of using `Provider` you could use `Instance` which would allow you to manually destroy the instances. e.g.
```java
@Startup
@Singleton
public class MyStartupBean {

     @Resource
     private ManagedExecutorService mes;

     @Inject
     @ConfigProperty(name = "myProperty")
     private Instance<Integer> myProperty;
   
    @PostConstruct
    public void init() {
        log.info("in init");
        mes.execute(() -> {
            while(true) {
                Integer myInt = myProperty.get();
                try{
                    Thread.sleep(100);
                }
                finally{
                   myProperty.destroy(myInt);
                }
            }
        });
    }
}
```
I can see how you might think things should work a bit differently but I don't think we can change it while remaining spec compliant... both the MicroProfile Config and CDI specs

**Comment by vignesh-arjunan** [comment]
@tevans78 Thanks for the explanation !!!
