### ISSUE TITLE
Investigate error handling with invalid part 1 element of a JWE

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#17733]
Investigate runtime behavior when the first element of a JWE is some random string.
Review comment "OidcClientEncryptionTests_JWE_Part1_isInvalid test should be expecting a CWWKS1725E message instead of CWWKS6056E."  needs to be investigated.
Issue delivering FAT with suspect expectation is [17720](https://github.com/OpenLiberty/open-liberty/pull/17720).
The real question is what error message should be issued when the first element of a JWE is something like "123456789012345".

**Comment by ayoho** [comment]
I believe I was mistaken in my comment in the PR (https://github.com/OpenLiberty/open-liberty/pull/17720#discussion_r661639494). I suspect that I thought these tests were going through inbound propagation scenarios, however they're going through the normal OIDC login flow and testing encrypted ID tokens. That flow wouldn't encounter the CWWKS1725E message since that's only emitted during inbound propagation. The error message that's being emitted now is appropriate, so I'm going to close this issue.
