### ISSUE TITLE
During criu restore process file descriptor info left on disk by JVM at checkpoint time

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#17812]
To correctly handle chekpoint/restore in detached docker container, we will coordinate with the jdk process stdout/stderr info in a known loaction and pass into the restore command.

see 
https://github.com/eclipse-openj9/openj9/issues/13150

**Comment by tjwatson** [comment]
While we may still want to have the JVM handle the stdout/stderr handles it is not blocking us for Liberty checkpoint/restore.  With PR #18334 a Liberty checkpoint process will always write to the console log instead of stdout/stderr.  The `server` script then pipes the content of the file back to the console for foreground `run` actions when launching a restore.  This avoids the issues with the file descriptor issues for stdout/stdin.  It also solves some issues for running a container that restores a checkpoint server while in interactive mode or detached mode.

**Comment by tjwatson** [comment]
I'm going to close this issue as we addressed it with a different solution in #18334
