### ISSUE TITLE
LDAP IdentityStore doesn't build search filter from callerNameAttribute if callerSearchFilter doesn't contain %s descriptor

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#1837]
The LdapIdentityStore should build a caller query from the callerNameAttribute, callerSearchFilter and the caller name if the callerSearchFilter does not contain a String.format(...) descriptor (%s).

**Comment by ryanesch** [comment]
This is intentional. The callerNameAttribute is used for direct binding and to determine what is returned as callerName in the CredentialValidationResult. I understand using callerNameAttribute to build the filter (as this is what was done originally), but in that case, the callerNameAttribute will mean two different things depending on if we have %s in the filter.

**Comment by ryanesch** [comment]
Made the requested changes: https://github.com/OpenLiberty/open-liberty/pull/1885
