### ISSUE TITLE
RuntimeCodebase cannot be located on collocated call

### ISSUE THREAD

**Issue by joe-chacko** [OpenLiberty/open-liberty#18503]
**Describe the bug**  
When invoking a Remote EJB in the same server, the call be routed internally (collocated) instead of going via the network.

If the calling app and the called app have different versions of the same class, some negotiation is required between them. This negotiation happens using the RuntimeCodebase object.

The bug here is that the RuntimeCodebase is not available for collocated calls.

**Steps to Reproduce**  
Run the `org.apache.yoko.FullValueDescriptorTest$Collocated` test case from Yoko against an earlier version of Yoko.

**Expected behavior**  
The versioned object should be transmitted successfully between the collocated client and server code.

**Diagnostic information:**  
 - OpenLiberty Version: [20.0.0.12]
 - Affected feature(s) [ejbRemote-3.2, enterpriseBeansRemote-4.0]
 - Java Version: [Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)]
 - server.xml configuration (WITHOUT sensitive information like passwords) [none]
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by joe-chacko** [comment]
The first fix needs a bit more tweaking in Yoko to avoid an unprivileged call.

**Comment by ngmr** [comment]
Some tests hit a security exception when this fix went in.
This was the result of an unprivileged call to a secure method which now occurs on a different codepath in those tests.

I'll create a new issue for addressing the unprivileged call issue because:

1. It is not directly related to this issue, merely uncovered by its change in internal testing (of another Liberty component)
2. This issue has already been marked as released in 21.0.0.10, and I don't want to risk throwing that system into confusion

**Comment by mbroz2** [comment]
@joe-chacko please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
