### ISSUE TITLE
JakartaEE: Transformer: JakartaEE10 Issues

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#18908]
This story covers the transformer improvements that are not required for Jakarta EE 9 being made available with Open Liberty, but should be addressed for EE10 or even before EE 10 is made available whenever we determine the issues can be addressed.

**Comment by tbitonti** [comment]
As of 04-01-2022, the eclipse transformer issues were reviewed and prioritized relative to the current use from open-liberty for Jakarta EE 10.

As function is available, a new open-liberty issue must be created to bring in that function.  For example, see issue #20472.

Key properties are the priority labels (priority-ol, priority-tr, bug), and the assignee (BJH, TFB, or unassigned).

* "priority-ol" issues are a priority for current JakartaEE10 work.
* "priority-tr" issues are a priority for ongoing transformer work.
* "bug" issues are prioritized slightly below "priority-ol" and "priority-tr", unless used together with one of these labels.

Issues assigned to BJH (BJ Hargrave) are assigned specifically to them.  Issues assigned to TFB (Thomas F Bitonti) may be reassigned within open-liberty.

Query: All Open Issues https://github.com/eclipse/transformer/issues?page=2&q=is%3Aissue+is%3Aopen

https://github.com/eclipse/transformer/issues/247: Add Bnd Analyzer plugin for transforming during a Bnd operation
  -- enhancement priority-ol tool:bnd 
  -- BJH

https://github.com/eclipse/transformer/issues/228: Plugin goal to transform dependencies
  -- tool:maven 
  -- BJH

https://github.com/eclipse/transformer/issues/186: JavaActionImpl does not handle "--direct" replacement
  -- bug 
  -- TFB

https://github.com/eclipse/transformer/issues/185: --per-class-constant does not work as advertised
  -- bug 
  -- TFB

https://github.com/eclipse/transformer/issues/179: Better documentation for using command line documentation
  -- PII 
  -- TFB

https://github.com/eclipse/transformer/issues/177: Review location of child properties files for text updates
  -- priority-ol question 
  -- TFB

https://github.com/eclipse/transformer/issues/176: Review static string class update data to include all currently known JavaEE to Jakarta cases
  -- priority-ol rules-data
  -- TFB

_https://github.com/eclipse/transformer/issues/175: Add class update case for updating package versions_
  -- enhancement priority-ol 
  -- BJH
  -- Fixed by 0.4.0

https://github.com/eclipse/transformer/issues/174: Allow different version updates for different manifest attributes
  -- enhancement priority-ol
  -- TFB

https://github.com/eclipse/transformer/issues/167: Transformer as a gradle plugin
  -- enhancement tool:gradle 
  -- BJH

https://github.com/eclipse/transformer/issues/166: Complete implementation of reversable transformations
  -- enhancement 
  -- unassigned / future

https://github.com/eclipse/transformer/issues/165: Tool does not update pom.xml for dependencies
  -- enhancement 
  -- unassigned / future

https://github.com/eclipse/transformer/issues/139: Allow the transformed artifact to have it's own maven ID and runtime dependencies
  -- enhancement priority-ol tool:maven 
  -- BJH

https://github.com/eclipse/transformer/issues/133: Use property instead of classifier to define an alternative artifactId for the transformed archive
  -- enhancement priority-ol tool:maven
  -- BJH

https://github.com/eclipse/transformer/issues/131: Fix extension when transforming sources and javadoc jar
  -- bug tool:maven 
  -- unassigned/ future

https://github.com/eclipse/transformer/issues/130: Migrate URL in Javadoc using the Maven plugin enhancement
  -- rules-data
  -- TFB

https://github.com/eclipse/transformer/issues/129: Request to update Usage section documentation
  -- PII
  -- TFB

https://github.com/eclipse/transformer/issues/119: Ignore duplicate input archive entries
  -- enhancement
  -- TFB

https://github.com/eclipse/transformer/issues/101: Meaningful failure message for jakarta transformation
  -- bug PII priority-tr 
  -- TFB

https://github.com/eclipse/transformer/issues/99: Intercept Class.forName and similar calls to perform package renaming dynamically
  -- enhancement 
  -- unassigned / future

https://github.com/eclipse/transformer/issues/77: Regular expression text substitution for javadoc transformation enhancement
  -- enhancement 
  -- unassigned / future

https://github.com/eclipse/transformer/issues/73: Create transforms for batch XML (and other XMLs using updated Jakarta EE 9 XSDs?)
  -- enhancement
  -- unassigned/ future

https://github.com/eclipse/transformer/issues/66: Create brew formula for transformer cli
  -- enhancement 
  -- BJH

https://github.com/eclipse/transformer/issues/53: Incorrect transformation of annotation value.
  -- bug priority-ol 
  -- TFB

https://github.com/eclipse/transformer/issues/46: SwitchMap and SWITCH_TABLE references should be updated
  -- enhancement
  -- unassigned/ future

https://github.com/eclipse/transformer/issues/23: Support updating bean validation constraint mappings. 
  -- enhancement 
  -- TFB

https://github.com/eclipse/transformer/issues/20: Output rules for Export/Import package
  -- enhancement priority-ol
  -- TFB

https://github.com/eclipse/transformer/issues/16: Add JSP Transformation step
  -- enhancement rules-data
  -- TFB

https://github.com/eclipse/transformer/issues/2: Preserve manifest formatting: Attribute ordering and comments 
  -- bug
  -- TFB

**Comment by tbitonti** [comment]
Closing.  The tracked issues are now badly out-of-date.  If needed, a new issue should be created to track current transformer issues.
