### ISSUE TITLE
Jakarta EE 10: DD: Deployment descriptor parser updates

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#18997]
For Jakarta EE 10, the EE 10 deployment descriptors need to be merged with resource definition annotations.  The deployment descriptor and annotation processing code needs to be updated in order to handle this new requirement.

@njr-11 identified this issue and talked with the kernel team and @tbitonti was identified as the person to work on this issue.  As such I am assigning this story to him.

**Comment by tbitonti** [comment]
This issue relates to resource definition additions.  So far, these have arisen from updates to the Jakarta EE 10 Concurrency update (ref issue #18228).

At this time, DDModel updates are complete, as far as is required by Concurrency.  Annotation handling is also complete.  The remaining work is to update the DD parsing code to handle the changes.

This will require updating the DD parsing code to handle any new schema versions and namespaces, as these must be updated to enable parsing of the new resource definitions.

**Comment by tbitonti** [comment]
Specification project:
https://github.com/eclipse-ee4j/jakartaee-schemas
Currently in motion, but should be mostly complete now.  Specifications should be complete sometime in Feb.

**Comment by tbitonti** [comment]
As of 11-Jan-2022, these schemas are available:

application_10.xsd
application-client_10.xsd
connector_2_0.xsd
ejb-jar_4_0.xsd
jakartaee_10.xsd
jakartaee_web_services_2_0.xsd
jakartaee_web_services_client_2_0.xsd
jsp_3_1.xsd
permissions_10.xsd
web-app_6_0.xsd
web-common_6_0.xsd
web-facelettaglibrary_3_0.xsd
web-facesconfig_3_0.xsd
web-fragment_6_0.xsd
web-jsptaglibrary_3_1.xsd
web-partialresponse_3_0.xsd

**Comment by tbitonti** [comment]
Part 1: Issue #19764
Part 2: Issue #19765 
Part 3: Issue #19774

**Comment by tbitonti** [comment]
For the **12-Jan-2022 Jakarta EE 10 Scrum**:

For the Jakarta EE 10 descriptor parsing, this epic story is being used:
https://github.com/OpenLiberty/open-liberty/issues/18997
"Jakarta EE 10: DD: Deployment descriptor parser updates"

That currently has three child issues.  More will likely be created for completing the parse code for each of the descriptor types.

https://github.com/OpenLiberty/open-liberty/issues/19764
"Jakarta EE 10: DD: Tolerate new schema versions"
- **Closed**; delivered.

https://github.com/OpenLiberty/open-liberty/issues/19765
"Jakarta EE 10: DD: Parse new resource definition elements"
- **Closed**; This placeholder is no longer needed.

https://github.com/OpenLiberty/open-liberty/issues/19774
"Jakarta EE 10: DD: Parse new resource definition elements by Connector (ra.xml)"
- **Closed**; there are no new non-version updates to the connector schema.
- https://jakarta.ee/xml/ns/jakartaee/connector_2_1.xsd
- https://jakarta.ee/xml/ns/jakartaee/connector_2_0.xsd

The goal is to be able to (1) tolerate descriptors which use the new schema versions (but not which have any added elements for those new versions), then (2) handle parsing of the four resource definition elements.

There is an extra issue for connector / ra.xml because it uses a non-standard parser implementation.

The four new elements arise in the common Jakarta EE 10 schema "jakartaee_10.xsd", and are present in the widely used "JNDIEnvironmentRefs":

    ContextService
    ManagedExecutor
    ManagedScheduledExecutor
    ManagedThreadFactory

The issue 19764 is coded and I'm beginning to build/test the changes.  When that is working, I'll start on 19765.

Outside of the current scope is parsing of other added elements.  Once 19765 we should regroup and figure out the next steps. Or, I can just continue through the remaining schema updates.  I would partition the update by descriptor (app, app-client, web, webservices, permissions, connector).  I don't see an EJB update, so that is not in the list.

There are several schemas which are not handled by the DD parsing layer, and which I don't have a plan for:

jakartaee_web_services_client_2_0.xsd
jsp_3_1.xsd
web-facelettaglibrary_3_0.xsd
web-jsptaglibrary_3_1.xsd
web-partialresponse_3_0.xsd

There is a problem of not having all updated schemas on jakartaee-schemas: Not all of the schemas were updated with a new version number.  An issue was opened for this:
"Missing schema version updates"
https://github.com/eclipse-ee4j/jakartaee-schemas/issues/32
I can workaround this locally until the corrections are made.
