### ISSUE TITLE
GA BLOG - Configurable Response Headers in Open Liberty

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#19262]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this newly released feature/function of Open Liberty. For this post to be included in the GA issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
   
   Short feature name (eg websockets-1.0): 

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by pnicolucci** [comment]
@mrsaldana I think you can use the Beta blog as a starting point: https://github.com/OpenLiberty/open-liberty/issues/18702

**Comment by mrsaldana** [comment]
1. Which Liberty feature(s) does your update relate to?

Human-readable name (eg WebSockets feature): **Configurable Response Headers**

Short feature name (eg websockets-1.0): N/A - Does not require a feature declaration in `server.xml`. It is configured by declaring a `<headers>` element within a desired `<httpEndpoint>`.

2. Who is the target persona? Who do you expect to use the update? **Application developers and administrators of Liberty servers**

3. Write a paragraph to summarize the update:  

### Configurable Response Headers

You can now configure Open Liberty to modify response headers.  The available configuration options allow for headers to be appended, for existing headers to be overwritten, for missing headers to be added, and for undesired headers to be removed from all responses being serviced by an HTTP endpoint. This configuration offers more granular control over response headers, which offers a solution to modifying headers without the need to change existing applications, filters, or otherwise. 

### Setting the `<headers>` element 

To use configurable response headers, begin by defining a new element called `<headers>` in the `server.xml`.  You can configure this for individual HTTP endpoints or for all endpoints at once. 

Configuring for individual HTTP endpoints:

```
<httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" >
	 
       <headers>
            <add>foo:bar</add>
            <add>foo:bar2</add>
            <set>customHeader:customValue</set>
            <setIfMissing>X-Forwarded-Proto:https</setIfMissing>
            <remove>Via</remove>
       </headers>
   		
</httpEndpoint>
```

Configuring for all HTTP endpoints:

```
 <httpEndpoint id="defaultHttpEndpoint"
                         httpPort="9080"
                         httpsPort="9443"
                         headersRef="myHeadersID">
     </httpEndpoint>
 
     <httpEndpoint id="otherHttpEndpoint"
                         httpPort="9081"
                         httpsPort="9444"
                         headersRef="myHeadersID">
    </httpEndpoint> 
     
     <headers id="myHeadersID">
            <add>foo:bar</add>
            <add>foo:bar2</add>
            <set>customHeader:customValue</set>
            <setIfMissing>X-Forwarded-Proto:https</setIfMissing>
            <remove>Via</remove>
     </headers>  
```

 The `add` attribute allows multiple headers with the same name to be added to a response, similar to the HttpServletResponse's `addHeader` API. Similarly, the `set` attribute is analogous to the `setHeader` API, which sets a response header to the given name and value. This overwrites existing headers that share the same name. The `setIfMissing` attribute will only set the configured headers if they are not already present on the response. Lastly, the `remove` attribute will remove any response headers whose name matches a name defined by the configuration. 

Each header entry for the `add`, `set`, and `setIfMissing` attributes can be provided as a standalone header name. Optionally, a header value can be added by appending the colon `:` character after every header name. Note, however, that the `remove` attribute only expects header names and not a header name:value pair.
 
### Configuration Options

As seen in the example above, one way to configure the `<headers>` element is to declare each individual header within it own `add`, `set`, `setIfMissing`, or `remove` attribute. In addition to this configuration, headers can be provided as a comma delimited list. 

The following server.xml configuration declares individual headers within the desired configuration attributes: 

```
<headers>
            <add>foo:bar</add>
            <add>foo:bar2</add>
            <set>customHeader:customValue</set>
            <setIfMissing>X-Forwarded-Proto:https</setIfMissing>
            <remove>Via</remove>
</headers>
```

This configuration can also be declared as comma delimited lists, such as: 

```
<headers add="foo:bar, foo:bar2" set="customHeader:customValue" setIfMissing="X-Forwarded-Proto:https" remove="Via"/>
```

### Misconfigurations

There are three warning messages relating to misconfigurations for this feature. Note that if a configuration value is considered to be misconfigured, it will not be utilized. Furthermore, if the misconfigured value had a non-empty header name, any further configurations with this same name will also be ignored.

The first warning message, `CWWKT0042W`, will be logged whenever a header name is left empty. While header values are completely optional, the configuration does expect a non-empty header name. 

The `add` configuration allows for multiple headers with the same name to be configured. However, it would be ambiguous to repeat a header name in any other configuration attribute. For instance, consider the `set` attribute option, which is meant to overwrite an existing header that shared the declared header name. If the `set` configuration contained two headers with the same name, it would be unclear which of the two values should be chosen. Similarly, if the same header name is present in two or more configurations, the same ambiguity is true. As such, and excluding repetitions in the `add` configuration, whenever a header name is found to be used more than once,  the warning message `CWWKT0043W` will be logged. 

The third warning message, `CWWKT0044W`, is logged if a header that has already been flagged as a duplicate by the `CWWKT0043W` warning message, continues to be utilized by further configurations. 

**Warning Message Descriptions:** 

`CWWKT0042W` : An empty header name was found when the 'set` configuration was parsed. This value is ignored.

`CWWKT0043W` : A duplicate header name was found in the [foo] header using the `set` configuration. All configurations for the [foo] header are ignored. Any header that is defined by the remove, add, set, or setIfMissing configurations must be unique across all configurations.

`CWWKT0044W` : The [foo] header, which is marked as a duplicate header name, was found in the `set` configuration. The [foo] header is ignored. Any header that is defined by the `set` configuration must contain unique header names.

### Summary

Open Liberty now provides a way to control response headers for a given HTTP endpoint. These can be appended, configured to overwrite, to only be added if not already present, or completely removed from all responses. Try it out for yourself!

**Comment by mrsaldana** [comment]
Blog included here: https://openliberty.io/blog/2021/11/26/jakarta-ee-9.1.html
