### ISSUE TITLE
mpOpenApi 2.0 cache fails intermittently, which increases startup time.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#19375]
I have a test case where I have 10 apps and I am running in the default "openapi mode" where only 1 of them will be processed by mpOpenAPI.

At server start, 1 of the 10 apps is selected as the default and generates a model and gets put into the cache (if it's not there already and has not been "changed"). This also happens during a server stop, and sometimes it does it multiple times, 1 to 3 apps may be added to the cache during a stop. I am guessing as the "default app" gets stopped, a new app is made the "default app" so it becomes the one openapi cares about and gets processed. Should this be happening during a stop?

However, sometimes, the isCacheUpToDate is false  here:
https://github.com/OpenLiberty/open-liberty/blob/3cc24d590ff5305ee82cded977ab9cce814873be/dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/cache/CacheEntry.java#L198

It looks like the properties differ during a server start compared to later at a server stop (see privatePropertiesEnable below). So, if an app gets processed during a different step than it was prior, the props will differ, and it will be marked as a cache miss and get regenerated (which adds to startup time if it is during a server start)

Start
```
{privatePropertiesEnable=false, getDefaultProduces=Optional.empty, allowNakedPathParameter=Optional.empty, getSchemas=, getDefaultConsumes=Optional.empty, scanExcludeClasses=, sortedPropertiesEnable=false, arrayReferencesEnable=true, scanPackages=, scanDependenciesDisable=false, scanExcludePackages=(\Qjava.lang\E), scanClasses=, scanDisable=false, servers=, propertyNamingStrategy=IDENTITY, applicationPathDisable=false, scanDependenciesJars=}
```
 
Stop
```
{privatePropertiesEnable=true, getDefaultProduces=Optional.empty, allowNakedPathParameter=Optional.empty, getSchemas=, getDefaultConsumes=Optional.empty, scanExcludeClasses=, sortedPropertiesEnable=false, arrayReferencesEnable=true, scanPackages=, scanDependenciesDisable=false, scanExcludePackages=(\Qjava.lang\E), scanClasses=, scanDisable=false, servers=, propertyNamingStrategy=IDENTITY, applicationPathDisable=false, scanDependenciesJars=}
```

Guessing this was introduced with this (Pull 17761 - by default privatePropertiesEnable=false).
https://github.com/Azquelt/open-liberty/blob/65071eafa9c641e3b0e786a15ac2894bc4034b3a/dev/io.openliberty.microprofile.openapi.2.0.internal/resources/OSGI-INF/wlp/defaultInstances.xml
 
If I set mp.openapi.extensions.smallrye.private-properties.enable=true, the mismatch goes away.
 
So, when/why does it get changed to true after startup?

**Comment by Azquelt** [comment]
From what you're saying `privatePropertiesEnable` is `false` at startup, but becomes `true` later? It should be `true` all the time (unless the user has configured it otherwise). Thanks for finding that, it's likely to cause other bugs.

As you found, we default the property to true using a defaultInstances.xml. I assume that config is not processing that variable in time for us to use it at startup, which is worrying. (I wonder if this happens for all variables defined in server.xml, or just ones in defaultInstances.xml).

> I am guessing as the "default app" gets stopped, a new app is made the "default app" so it becomes the one openapi cares about and gets processed. Should this be happening during a stop?

I could see that happening. We probably need to detect whether the server is shutting down (if it isn't, we should process the next app, if it is then we don't want to bother). I think this behaviour also exists in mpOpenApi-1.x.

**Comment by Azquelt** [comment]
From what you're saying `privatePropertiesEnable` is `false` on startup but then `true` at shutdown? It should be `false` all the time, set by our `defaultInstances.xml`. 

That's kind of weird that it changes, I guess config must be unloading the config from our `defaultInstances.xml` earlier in the shutdown process.

> I am guessing as the "default app" gets stopped, a new app is made the "default app" so it becomes the one openapi cares about and gets processed. Should this be happening during a stop?

I can see why that's happening and I think that behaviour has been around since mpOpenApi-1.x. If an app is removed while the server is running, we do need to process the new "default app", but during shutdown we should suppress that.

**Comment by Azquelt** [comment]
@jdmcclur I have a fix for the scanning of apps during shutdown. Could you check the personal build on #19387 and see if it resolves the issue?

**Comment by jdmcclur** [comment]
@Azquelt LGTM - The behavior is now what I would expect.

**Comment by Azquelt** [comment]
Thanks!
