### ISSUE TITLE
PI93226-ConcurrentModificationException during application startup

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#1952]
The java.util.ConcurrentModificationException might occur during application startup.

Example of the exception:
E SRVE0266E: Error occured while initializing servlets: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1448)
at java.util.HashMap$ValueIterator.next(HashMap.java:1477)
at com.ibm.ws.webcontainer.webapp.WebApp.sortNamesByStartUpWeight(WebApp.java:3808)
at com.ibm.ws.webcontainer.webapp.WebApp.createServletWrappers(WebApp.java:1393)
at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinish(WebApp.java:1132)
at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1052)
.............

The problem occurs when setting the WebContainer custom property 
deferServletLoad = "false"  (default is "true")

and there are lot of JSP files in the application.

The problem does not occur under the default setting of deferServletLoad = "true".

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/2175

**Comment by ewhoch** [comment]
This issue doesn't make sense without any context. What is PI93226? What's the failure? How do I come across it? What's a stack look like? This issue is basically empty and references artifacts that aren't public. What type of application startup? It's crucial we make sensible and contained descriptions of problems so that outside users that come across them have something to go over.

**Comment by pmd1nh** [comment]
new PR 
https://github.com/OpenLiberty/open-liberty/pull/2264

**Comment by pmd1nh** [comment]
cancel previous PR and use the new PR instead
https://github.com/OpenLiberty/open-liberty/pull/2336
