### ISSUE TITLE
Is Openliberty affected by cve-2021-44228

### ISSUE THREAD

**Issue by jkleinlercher** [OpenLiberty/open-liberty#19620]
Since cve-2021-44228 gets very famous I would like to know if Openliberty is also affected by cve-2021-44228.
Thanks in advance!

**Comment by NottyCode** [comment]
Open Liberty is not vulernable to CVE-2021-44228 because it does not include Log4J. 

Open Liberty does nothing to protect applications that contain log4j2 from this vulnerability. If running on recent versions of Java 8 or 11 the JVM protects against some of the worst exploits, but that protection is not complete as, a result the Open Liberty team recommend running the latest version of Java and update any applications running on Liberty to use Apache Log4j 2.15.
