### ISSUE TITLE
Investigate why CDI12ExtensionTest.testHelloWorldExtensionServlet does not work on EE10

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19900]
It seems that with CDI 4.0, if the application extension does not get scanned properly for beans if the beans.xml either contains no version information (CDI v1.0) or has bean discovery mode set to annotated (CDI v1.1+). If the discovery mode is set to ALL then CDI 4.0 is happy.

https://github.com/OpenLiberty/open-liberty/blob/66284ce3c6684229f07abb4272bc46b55aab5e13/dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionTest.java#L87

**Comment by Azquelt** [comment]
I think this is because the servlet has observer methods but is not annotated with a bean defining annotation.

The test does pass if I add `@ApplicationScoped` to `HelloWorldExtensionTestServlet`

**Comment by Azquelt** [comment]
The failure on 4.0 is due to the change in behaviour when using a CDI 1.0 beans.xml. On 3.0 this results in bean-discovery-mode=all, whereas on 4.0 it results in bean-discovery-mode=annotated.

We could fix the test by either adding a beans.xml explicitly setting bean-discovery-mode=all, or adding a bean defining annotation to `HelloWorldExtensionTestServlet`.
