### ISSUE TITLE
Feedback: support on secondary repositories

### ISSUE THREAD

**Issue by faandg** [OpenLiberty/open-liberty#19961]
Hi,

Just some feedback from a concerned citizen using Liberty on Openshift.

The level of support on this repository is pretty awesome and quick.
You have dedicated teams to quickly divide issues and respond to them.
However if we want to use a docker image
https://github.com/OpenLiberty/ci.docker/issues
Or deploy on openshift
https://github.com/OpenLiberty/open-liberty-operator/issues
These repositories barely get any support. There are a lot less issues but they are equally relevant.
I have a feeling the people from IBM working on those repositories do so best effort next to other jobs.

Would it be possible to discuss internally whether you can provide them with additional support and thus, accelerate the handling of issues and new features?

Example of an issue I have right now:
* fix pack 22.0.0.1 has been released a couple of weeks ago
* the docker image for it does not yet exist so I cannot build it ([although some work has been done](https://github.com/OpenLiberty/ci.docker/commit/2b360b2a301d19d6d500237f3d098ebacb017196))
* I don't feel like opening an issue for it on the ci.docker repository because I probably won't get a reply anyway

Same goes for the operator repository, slow or no responses.

**Comment by leochr** [comment]
@faandg Thanks for raising your concerns. We'll try to address them in a timely manner. 

Regarding the 22.0.0.1 images, please pull the images from IBM Container Registry `icr.io/appcafe/open-liberty`. It's documented [here](https://github.com/OpenLiberty/ci.docker/blob/master/docs/icr-images.md). Same tags as Docker Hub tags. 

Example image: `icr.io/appcafe/open-liberty:22.0.0.1-kernel-slim-java11-openj9-ubi`

Our recommendation is to use ICR instead of Docker Hub, since ICR doesn't impose rate limits on image pulls. Images as well the as the registry are managed by IBM. Images can be pulled from ICR without authentication. Only images with Universal Base Image (UBI) as the Operating System are available in ICR at the moment.

@crpotter The [manifest issue](https://github.ibm.com/was-docker/build-liberty-images-ubi/issues/133#issuecomment-39915640) I reported for version-less tag, now seem to affect 22.0.0.1 images as well. The images for each arch are there, but manifest is missing. When I tried a few days ago, I believe it worked fine though for 22.0.0.1 images. Could you please look into addressing it? Thank you.

**Comment by faandg** [comment]
@leochr thanks for the information.
I did read it a while ago but assumed you would also still publish to Dockerhub.
Turns out we were unable to fetch our usual tag because it was missing (22.0.0.1-kernel-java11-openj9-ubi).
I see you have meanwhile added it, thanks for that.

You're doing excellent work. Please make sure you get the help you need for handling the pending tickets.

In case anyone else is wondering how to leverage ibmcloud cr to fetch the list of images from `icr.io`, here it is
```ibmcloud login
ibmcloud plugin install container-registry
ibmcloud cr region-set global
ibmcloud cr login
```

**Comment by leochr** [comment]
@faandg Thank you. We are trying to get additional help. We are continuing to publish to both Docker Hub and `icr.io`. At this point, we haven't decided to stop publishing to Dockerhub. We'll communicate if that becomes the case. I believe you meant 22.0.0.1-kernel-slim-java11-openj9-ubi (with `slim` in the tag).

**Comment by faandg** [comment]
@leochr we use both the OL and the [WL](https://hub.docker.com/r/ibmcom/websphere-liberty/tags) images. OL has the `kernel-slim` tag and WL just has the `kernel` tag.
Is there a specific difference?

**Comment by leochr** [comment]
@faandg Both tags serve the same purpose: providing the bare minimum server with only the kernel features

OL's `kernel-slim` has a separate script (features.sh) to handle downloading features. WL has this step included in configure.sh.

**Comment by faandg** [comment]
@leochr do you have any plans to make the same change for WL images (include feature.sh)?
It sounds like it might actually solve one of my other issues https://github.com/WASdev/ci.docker/issues/400#issuecomment-1028840887
In any case, you can follow up on that particular issue.

This issue was originally created for support on secondary repositories. If you feel sufficient awareness has been raised you can close this ticket. If not, you can keep it open for follow-up actions if you like.

**Comment by leochr** [comment]
@faandg Yes, there is a plan to create features.sh for WL images (tracking [issue](https://github.com/WASdev/ci.docker/issues/382)), but its primary motivation is to separate the feature downloading process from configure.sh (which warms up the server and generates caches). Regarding https://github.com/WASdev/ci.docker/issues/400#issuecomment-1028840887, I'll follow up with internal team to see if it's an option/possible to switch to featureUtility.

I'll close this issue and will follow up on issues in secondary repositories.
