### ISSUE TITLE
Develop OpenAPI documents / models for testing the parser and validator.

### ISSUE THREAD

**Issue by a-saf** [OpenLiberty/open-liberty#2008]
This is a child issue of #1534 

In order to get good test coverage for verifying that the parser and validator work correctly we're going to need test documents which cover the various constructs of the OpenAPI spec. Will need a good mix of valid and invalid documents for testing the validator.

We should consider contributing the OpenAPI test documents to github.com/microservices-api and create a new repo for these sample documents.

NOTE: Please make sure there is at least one FAT test that switches on the validation.

**Comment by leochr** [comment]
@janamanoharan please get started on this issue (we would need this for the Hackathon this Friday). It’s for creating application that results in validator error messages. Look at the unit tests we have for the validators, we need to replicate those scenarios using static document and/or models. Because those unit tests invoke the validator directly, so they wouldn’t catch any issues with the model walker. This issue will ensure that the model is correctly walked and the error messages are shown. Focus on the application first, then we can worry about the tests.

**Comment by leochr** [comment]
@janamanoharan @a-saf Just to clarify, this doesn't have to be an app with annotations. In fact I think it's easier to make it a static yaml/json file. Also it doesn't have to be one app that covers all scenarios. It could be multiple apps covering different validation scenarios. As a whole they should cover all validation scenarios.

**Comment by janamanoharan** [comment]
Annotations:
- [x] Info
- [x] Contact
- [x] License
- [x] ServerVariable(s)
- [x] Server(s)
- [x] Components - no validation
- [x] Path
- [ ] PathItem
- [x] Operation
- [x] ExternalDocumentation
- [x] Parameter
- [x] RequestBody
- [ ] MediaType
- [ ]  Encoding
- [ ] APIResponse(s)
- [ ] Callback
- [ ] Example(s)
- [ ] Link(s)
- [ ] Header(s)
- [ ] Tag(s)
- [ ] Ref
- [ ] Schema
- [ ] XML
- [ ] Security Scheme
- [ ] Security Requirement
- [ ] OAuth Flow(s)

**Comment by mrglavas** [comment]
@janamanoharan @a-saf Is this work item complete? Please close if it's done.

**Comment by leochr** [comment]
Closing since it was completed.
