### ISSUE TITLE
False artifact io.openliberty.jaxrs30 in mvn repository

### ISSUE THREAD

**Issue by AryonaOut** [OpenLiberty/open-liberty#20277]
**Describe the bug**  
The artifact in the maven repository (https://mvnrepository.com/artifact/io.openliberty.api/io.openliberty.jaxrs30/1.0.61) is still using javax.* packages whereas the bundled library wlp/dev/api/ibm/io.openliberty.jaxrs30_1.0.61.jar is using jakarta.* packages

**Steps to Reproduce**  
Switch to Jakarta EE and compile against io.openliberty.jaxrs30

**Expected behavior**  
https://repo1.maven.org/maven2/io/openliberty/api/io.openliberty.jaxrs30/1.0.61/io.openliberty.jaxrs30-1.0.61.jar should use the compliant jakarta.* packages

**Additional context**  
Not sure if this maven-jar is using javax.* on purpose, in my understanding jaxrs30 is a feature for Jakarta EE

**Comment by jhanders34** [comment]
This issue was discovered initially from a [stack overflow question](https://stackoverflow.com/questions/71112630/openliberty-jakartaee-9-access-transactionmanager).  The logic for figuring out what it publish in maven is outside of the open liberty repository and was updated last week for this issue to be corrected in 22.0.0.4 if it gets into the GM build.  The issue was that the untransformed version of the API bundles were getting picked up in the publish logic instead of the transformed one.  This is what has been corrected.

**Comment by jhanders34** [comment]
The fix for this is included in 22.0.0.3
