### ISSUE TITLE
Servlet 6.0: Clarify the decoding and normalization of URI paths.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20414]
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/18`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

**Comment by pmd1nh** [comment]
Wiki page URIs ...

https://github.com/jakartaee/servlet/wiki/HTTP-URIs-and-Servlet-API-methods

**Comment by idlewis** [comment]
The default behaviour of collapsing empty path segments is an issue for the WebServiceStats mbean that is part of the Performance Monitoring feature. The docs for the mbean are here https://openliberty.io/docs/latest/jmx-metrics-list.html#web-service-stats
We publish an mbean for each JAX-WS service, where the object name for the mbean is:
`org.apache.cxf:bus.id=<bus.name>,type=Performance.Counter.Server,service="<NameSpace><ServiceName>",port="<PortName>"`
The name space we use for web services in our tests is: `http://jaxws.samples.ibm.com.jmx/`
To query this mbean via the restConnector feature, a user would send a request to
`https://localhost:9443/IBMJMXConnectorREST/mbeans/{mbean object name}`
As the object name contains a double '/', this will get collapsed to a single '/' and so the object name will no longer match, and the query will fail

**Comment by pmd1nh** [comment]
RESTful WS TCK for 3.1 (EE 10) fails with the current URI path change in Servlet.

ee.jakarta.tck.ws.rs.ee.rs.core.uriinfo.JAXRSClientIT#getNormalizedUriTest

https://github.com/jakartaee/rest/blob/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/core/uriinfo/URIInfoTest.java#L228


Caused by: java.io.IOException: CWWWC0005I: The request URI has invalid or improperly encoded characters: [/jaxrs_ee_core_uriinfo_web/resource/%50%51%52%30%39%70%71%72/%7e%2d%2E%5f] . URI has encoded dot [%2E] character
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.verifyEncodedCharacter(WebAppFilterManager.java:1627)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAp
