### ISSUE TITLE
Expression Language 5.0: Clarify expected behaviour when matching expressions to methods based on parameter types

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20454]
Spec issue: `https://github.com/jakartaee/expression-language/issues/159`

See "A.1. Changes between 5.0 and 4.0" here: https://github.com/jakartaee/expression-language/blob/master/spec/src/main/asciidoc/ELSpec.adoc

**Comment by isaacrivriv** [comment]
After some investigation, don’t think this warrants a test since it is just a clarification to the spec. Didn’t see any source code changes going in or any additional tests added for this and we already have some varargs tests in Open Liberty to ensure the functionality is working as expected see [here](https://github.com/OpenLiberty/open-liberty/blob/d8dc2423fe20f597af21f22dfa8be3aebe94cabe/dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/src/com/ibm/ws/el30/fat/varargstest/EL30VarargsMethodMatchingServlet.java). 

Only saw something related [here](https://github.com/jakartaee/expression-language/issues/173) with the glassfish impl but we are using the tomcat implementation which already behaved as expected so I believe no additional work is required for this.

**Comment by isaacrivriv** [comment]
Nothing else to do here. Closing it up.
