### ISSUE TITLE
Expression Language 5.0: Avoid a NullPointerException when passing null for varargs.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20460]
Spec issue: `https://github.com/jakartaee/expression-language/issues/183`

See "A.1. Changes between 5.0 and 4.0" here: https://github.com/jakartaee/expression-language/blob/master/spec/src/main/asciidoc/ELSpec.adoc

**Comment by isaacrivriv** [comment]
This issue is specific to Eclipse's API. Tomcat's API already included a null check [here](https://github.com/apache/tomcat/blob/main/java/jakarta/el/Util.java#L254) which was added a while back. Technically it would only be able to be hit if calling the method directly and passing null as the params variable. Inside the source, the [method](https://github.com/jakartaee/expression-language/blob/d57c7a429d5ed2625f0e7b93ec810cdf50658dbf/api/src/main/java/jakarta/el/ELUtil.java#L628) is called only [here](https://github.com/jakartaee/expression-language/blob/d57c7a429d5ed2625f0e7b93ec810cdf50658dbf/api/src/main/java/jakarta/el/ELUtil.java#L213) and [here](https://github.com/jakartaee/expression-language/blob/d57c7a429d5ed2625f0e7b93ec810cdf50658dbf/api/src/main/java/jakarta/el/ELUtil.java#L188) which are safeguarded by parsing parameters passed to the method from the resolved method itself so the null value won't actually be hit. Even if not strictly necessary, discussed with @volosied (Thanks Vlad!) and decided to add some tests by passing null values in varargs expressions.
