### ISSUE TITLE
WebSocket 2.1: Remove the restriction that, in a Jakarta web container environment, endpoints can only registered during the deployment of the web application. Also add a new method, ServerContainer.upgradeHttpToWebSocket() that allows a web application to programmatically dispatch a request to a WebSocket endpoint.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20584]
Spec issue: `https://github.com/jakartaee/websocket/issues/211`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
I believe this is already implemented in our websocket code.  https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/external/ServerContainerExt.java#L289-L303

More information can be found by looking at the RTC Delivery Task 178813. Basically, it looked like Tomcat implemented this feature back in 2013 in [Bug 55314](https://bz.apache.org/bugzilla/show_bug.cgi?id=55314).  Which Liberty also did 2 years later to import support for third party code (i.e Spring).

I think we just need to use the new ServerContainer.upgradeHttpToWebSocket() method name. 

_____

Update June 22

It's a bit more complicated than just changing the name. We make this method availble to the applications via com.ibm.websphere.wsoc.WsWsocServerContainer#upgrade. See bundle `com.ibm.websphere.appserver.api.wsoc`. 

Additionally, I'd like to override the method, but that may make it more complicated since we would then need to split and refactor the main wsoc bundle.

**Comment by volosied** [comment]
Draft Branch for this Issue -- https://github.com/volosied/open-liberty/tree/jun24-websocket-dev

**Comment by pnicolucci** [comment]
We should `@Deprecated` the [WsWsocServerContainer.doUpgrade](https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.wsoc_1.0-javadoc/com/ibm/websphere/wsoc/WsWsocServerContainer.html)

We should plan to remove the IBM specific API in EE11 (whatever the next version of WebSocket is at that time).

**Comment by volosied** [comment]
We also need to remove this restriction: 

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/external/ServerContainerExt.java#L49-L54

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/external/ServerContainerExt.java#L167
