### ISSUE TITLE
WebSocket 2.1: Provide an API for client-side TLS configuration

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20583]
Spec issue: `https://github.com/jakartaee/websocket/issues/210`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
The API changed so that DefaultClientEndpointConfig now can store a SSLContext (created via  the ClientEndpointConfig$Builder).

I've found Tomcat's commit here useful as a reference: https://github.com/apache/tomcat/commit/e03da0f2245af6381fd5081ef5f7436a740b8dec

Liberty has it's own configurations for setting up SSL, and I don't see a simple way to pass a custom SSLContext to the `com.ibm.ws.channel.ssl` code.

I believe this may be the most challenging websocket change  for us to implement.  However, I'm also wondering if we are required to?  Liberty already provides ways to setup SSL.  I'm not sure what we should do?. We'll just need to work with Channel and Security teams to discuss this and see how we can implement this properly.  (Update: Already Posted in #was-security)

Other Useful Notes / Links:

Here's a stack trace for the WebSocketContainerExt.connectToServer call as it goes into the SSLChannel: 

```SSLChannel.getSSLContextForLink(VirtualConnection, String, String, String, Boolean, SSLConnectionLink) line: 469	
SSLChannel.getSSLContextForOutboundLink(SSLConnectionLink, VirtualConnection, Object) line: 321	
SSLConnectionLink.connect(Object) line: 1023	
HttpOutboundLink(OutboundProtocolLink).connect(Object) line: 130	
HttpOutboundLink.connect(Object) line: 241	
OutboundVirtualConnectionImpl.connect(Object) line: 76	
HttpRequestor.connect() line: 90	
ClientConnector.connectClass(Object, URI, ClientEndpointConfig, WebSocketContainer) line: 76	
ClientConnector.connectAnnotatedClass(Object, URI, WebSocketContainer) line: 61	
WebSocketContainerExt.connectToServer(Object, URI) line: 97	
WsocTestRunner.runTest() line: 104	
WsocTest.runWsocTest(Object, String, ClientEndpointConfig, int, int) line: 104	
WsocTest.runEchoTest(Object, String, Object[], int) line: 66	
WsocTest.runEchoTest(Object, String, Object[]) line: 62	
SecurityTest.testAnnotatedSecureSuccess() line: 37
```



https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannel.java#L467-L485

JSSEHelper API (note: lots of getters, no relevant setters here) 
https://www.ibm.com/docs/en/was-liberty/core?topic=SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.ssl_1.4-javadoc/com/ibm/websphere/ssl/JSSEHelper.html

**Comment by volosied** [comment]
some initial investigation was done here: https://github.com/volosied/open-liberty/commits/wsoc-2.1-dev 

and here: https://github.com/volosied/open-liberty/commits/wsoc-ssl
