### ISSUE TITLE
WebSocket 2.1: API reorganization

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20588]
> Removed the copy of the jakarta.websocket.* classes from the jakarta.websocket-api jar and replaced the copy with a dependency on the jakarta.websocket-client-api jar.

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
Basically, there are now two API jars instead of one. 
- [jakarta.websocket-api/](https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/websocket/jakarta.websocket-api/)
- [jakarta.websocket-client-api/](https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/websocket/jakarta.websocket-client-api/)


We can create two new bundles or just group them together in a single liberty bundle.  

Due to the feature files specifying the coordinates for each dependency, I will make two bundles and list them both in the wsoc 2.1 feature file.

**Comment by volosied** [comment]
Current Bundles in the private feature: 
https://github.com/OpenLiberty/open-liberty/blob/c6dc0397419f22293671a32be49aa829f016ec32/dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.1.feature#L2-L7

Jared said to keep this as it as we may decide to create a private (client?) websocket feature to be included in the jakartaeeClient-10.0 feature
