### ISSUE TITLE
CDI 4.0 with 1.0 beans.xml schema + emptyBeansXMLExplicitBeanArchive property

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#21020]
It seems that a 1.0 version schema beans.xml along with `<cdi emptyBeansXMLExplicitBeanArchive="true"/>` was not working while I was working on updating JPA FATs which use CDI.  The only way I could get the JPA FAT to work was to update it to switch to use a 1.1 schema beans.xml with EE10+ scenarios, with the `bean-discovery-mode="all"` property.

**Comment by tevans78** [comment]
Not a release bug because CDI 4.0 is not GA

**Comment by tevans78** [comment]
Confirmed that since the CDI 1.0 beans.xml file was not actually empty, the backwards compatibility flag had no effect. At the moment we have no intention of changing this as the CDI 4.0 spec only requires an backwards compatibility option for an _empty_ beans.xml file. The better solution is to update the beans.xml to a later version and explicitly set the discovery mode.
