### ISSUE TITLE
Checkpoint: ensure Liberty messaging (JMS) works with checkpoint and restore

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#21211]
Investigation is needed. Determine if any issues exist due to interactions between checkpoint/restore and use of the Liberty embedded JMS messaging provider. This might involve aspects of transactions, security, or remote communications.

**Comment by tjwatson** [comment]
JMS support will not be initially supported for #16384 Liberty checkpoint feature.

**Comment by tjwatson** [comment]
Closing since Embedding Messaging behavior with InstantOn is already partially verified under epic Jakarta Embedded Messaging #28238.  To date we discovered a blocking problem with the `messagingSecurity` feature.  When resolving that problem we will add tests to the FAT suite that exercise secure connections between messaging clients and servers. And if necessary, we can exercise more complex transactional message delivery scenarios.
