### ISSUE TITLE
Corrections needed for messages

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#2124]
Document the issues you find with messages. Describe which part of the message you found confusing (and a suggestion for the message would also be good).

**Comment by mrglavas** [comment]
In testing the SecurityScheme validator I found the following ambiguous warning message: "[WARNING ] CWWKO1651W: Validation of the OpenAPI document produced the following warning. Message: One or more fields defined are not applicable to a SecurityScheme instance of type "openIdConnect", Location: #/components/securitySchemes/openIdConnectWithScheme". It would be more helpful if the message listed the names of the fields that are not applicable. The code is currently checking if one of many fields is not null, but doesn't capture which of them were not null.

**Comment by mrglavas** [comment]
In testing the OAuthFlowsValidator I found the following warning message that is missing a location: "[WARNING ] CWWKO1651W: Validation of the OpenAPI document produced the following warning. Message: The "authorizationUrl" field with the "https://example.com/api/oauth/dialog" value is not applicable for "password OAuthFlow", Location: null". I checked the code and can see that the location is not being passed in at any of the places this message is reported. For consistency with other messages, it would also be good to change the name of message key from "nonApplicableField" to "oAuthNonApplicableField" so that it's clear which validation component it is associated with.

**Comment by leochr** [comment]
Reference message:
CWWKO1650E: Validation of the OpenAPI document produced the following error. Message: The "#/components/schemas/Pet" value is an invalid reference for "com.ibm.ws.microprofile.openapi.impl.model.media.SchemaImpl", Location: #/paths/~1bookings~1{id}/put/requestBody/content/application~1json/schema

The message should just be The "#/components/schemas/Pet" value is an invalid reference

**Comment by a-saf** [comment]
Reference validator throws a misleading error when a model has a proper $ref but null components, triggers "referenceNull" validation message.

**Comment by leochr** [comment]
Addressed all of the above documented issues with messages.
