### ISSUE TITLE
Feature Test Summary for Jakarta Pages 3.1

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21284]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* 

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by isaacrivriv** [comment]
# WebSocket 2.1: #18745

**Repeated tests**: The bucket io.openliberty.wsoc.internal_fat has been enabled for repeat on EE10. Bucket com.ibm.ws.wsoc_fat on WS-CD-Open with dependencies on features and bundles in WS-CD-Open have been transformed to run with EE10. All tests have been set to repeat on EE10 including cdi-4.0 integration.

**New tests**: A new FAT bucket io.openliberty.wsoc.2.1.internal_fat has been added with specific tests for WebSocket 2.1. This functionality includes:

- WebSocket 2.1 removed restriction that endpoints can only be registered during the deployment of the web application. Test was added to confirm  this behavior.
- WebSocket 2.1 added API for client-side TLS configuration. Tests were added to verify this new TLS configuration.
- WebSocket 2.1 clarified zero or negative value disables the session idle timeout. Tests were added to verify this.
- WebSocket 2.1 clarified that once the container has identified a MessageHandler for a message, the MessageHandler is used for the entirety of the message irrespective of any subsequent changes to the MessageHandlers configured for the Session. No automated tests were added due to the time dependant nature of the feature. Manually confirmed.
WebSocket 2.1 clarified the expected behaviour for Session.getRequestURI full URI should be returned. Tests was added to confirm this.
- WebSocket 2.1 added new method, ServerContainer.upgradeHttpToWebSocket() that allows a web application to programmatically dispatch a request to a WebSocket endpoint. Added test to verify new method functionality.
- WebSocket 2.1 clarified the expected handling of user properties. Tests were added to verify clarification.
- WebSocket 2.1 added a getter for the default platform configurator. No new method, just method that was exposed publicly. Manually tested method could be accessed.

**Manual tests**: Two verifications/changes were done manually.
- Manually verified MessageHandler clarification due to the testing being time dependent. This was verified by creating a breakpoint in Eclipse to allow a Message Handler to be removed as a new request came in.
- Verified new default platform configurator getter manually due to no new functionality. This was just an access modifier change in an already defined method for a method call for CDI beans.

**Confidence**: 5 All feature tests have been passing with no EE10 failures since enabling the feature.

**Comment by isaacrivriv** [comment]
# Jakarta Pages 3.1: [#18737](https://github.com/OpenLiberty/open-liberty/issues/18737)

**Repeated tests**: The bucket [com.ibm.ws](http://com.ibm.ws/).jsp.2.3 has been enabled for repeat on EE10. An additional bucket in WS-CD-Open `com.ibm.ws.jsp_fat_lWAS` has been transformed for running on EE10 as well.

**New tests**: A new FAT bucket io.openliberty.pages.3.1.internal_fat has been added with specific tests for Pages 3.1
- Pages 3.1 deprecated methods that override ELResolver.getFeatureDescriptors() as that method has been deprecated as of Expression Language 5.0 the equivalent EE10 feature for Expression Language. No specific pages test added for this but this is tested within Expression Language 5.0.
- Pages 3.1 deprecated the jsp:plugin action and related actions as the associated HTML elements are no longer supported by any major browser. A test was added to verify that having this action is a no-op for pages-3.1 and up and that an appropriate log message appears in the trace.
- Pages 3.1 deprecated the isThreadSafe page directive attribute as the related Servlet API interface SingleThreadModel has been removed as of the Servlet 6.0 specification. Test has been added to verify that trying to use the directive results in a server warning CWWJS0003W.
- Pages 3.1 clarified that the EL environment within a JSP has a set of default imports consistent with the default imports for the scripting environment. Refactor the ScopedAttributeELResolver to remove the special handling for imports and unresolved variables. Tests were added to verify imports are appropriately available to the Expression Language scripting environment.
- Pages 3.1 clarified the meaning of ‘scope’ in the context of scripting variables associated with custom actions. No tests added as this was just a spec clarification with no functional changes.
- Pages 3.1 Added an option to raise a PropertyNotFoundException when an EL expression contains an unknown identifier. Tests were added to verify if a PropertyNotFoundException is thrown when the option is set.

**Manual tests**: None.

**Confidence**: 4 All feature tests have been passing with no EE10 failures since enabling the feature. The com.ibm.ws.jsp_fat bucket in WS-CD-Open contains additional Pages tests, but this bucket has not been transformed due to framework conflicts.

**Comment by ayoho** [comment]
LGTM 👍
