### ISSUE TITLE
Feature Test Summary for Faces 4.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21304]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* 

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by isaacrivriv** [comment]
# Jakarta Faces 4.0 and Faces Container 4.0: #18731

## Faces 4.0
**Repeated tests**: The bucket `com.ibm.ws.jsf.2.2_fat` and `com.ibm.ws.jsf.2.3_fat` have been enabled for repeat on EE10 for the Faces 4.0 feature. An additional bucket in WS-CD-Open `com.ibm.ws.jsf_fat_lWAS` has been transformed for running on EE10 as well.
**New tests**: A new FAT bucket `io.openliberty.org.apache.myfaces.4.0_fat` has been added with specific tests for Faces 4.0. The following are changes made in Faces 4.0

- _Attributes_: Faces 4.0 introduced various new attributes for different functionalities
  - New attribute <h:inputFile multiple=“…”> to support multiple file selection included in Faces 4.0. Tests were added for this attribute in conjunction with and without async with single and multiple files.
  - New attribute <h:inputFile accept=“...“> to support specific file types included in Faces 4.0. Tests were added for this attribute for cases with a single file type such as .mp3 and with MIME type string like audio/* as well as with the newly added multiple attribute as well.
  - New attribute <h:inputText type=“...“> which was available via passthrough attribute: pt:type=“email”, Now supported via the spec, type=“email”, type=“url” , etc. Tests were added for this attribute’s default, non-default and discommended types as well.
  - New attribute <f:websocket onerror=“...“> added for Faces 4.0 which allows for a JavaScript listener for any errors that occur. Tests were added to verify that listener is invoked when error occurs
  - New layout=“list” for <h:selectManyCheckbox> and <h:selectOneRadio> added which generates `<ul>` elements instead of `<table>`. Tests were added to verify attribute functionality in both <h:selectManyCheckbox> and <h:selectOneRadio>.
  - Skip type attribute from \<link> and \<script> when doctype is HTML5 due to warnings/errors for unsupported defaults. Tests were added to verify attribute is rendered with outputScript prior to HTML 5 but not rendered with HTML5.

- _Tags_: Faces 4.0 introduced two new tags for functionality regarding item groups
  - New tag <f:selectItemGroups> to avoids workaround with <f:selectItems> with multiple <optgroup> elements under \<option>. Tests were added to verify functionality with Bean defaults and static declarations in xhtml.
  - New tag <f:selectItemGroup> used to declare a single \<optgroup>. Tests were added to verify functionality with Bean defaults in xhtml.

- _Methods_: Faces 4.0 introduced two new methods
  - New method UIViewRoot#getDoctype() to identify the declared DOCTYPE of a view added in Faces 4.0. Test added with HTML 5 DOCTYPE calling a bean method that verifies the Doctype using the new API.
  - New method FacesContext#getLifecycle() added for simplicity in Faces 4.0. Test to verify getLifecycle method has been added.

- _Annotations_: Faces 4.0 introduced two new annotations
  - New annotation @ClientWindowScoped introduced which is a more specific bean scope. The Faces Window API differentiates windows/tabs and beans with this annotation will continue to live as long as the client id jfwidrequest parameter is reused across pages. Tests were added to verify functionality in flows, when refreshing views and with the jakarta.faces.NUMBER_OF_CLIENT_WINDOWS configuration.
  - New annotation literals for all @Qualifiers (such as FacesBehavior, FacesConverter, FacesDataModel, etc.) added which was needed for CDI API methods which accept an Annotation as an argument. With this, developers no longer need to create AnnotationLiteral instances manually. Tests were added to verify annotations were properly used.

- _Other changes_
  - Faces 4.0 introduced a new API to programmatically create Facelets (all via Java) instead of using XML. Tests were added for verifying functionality creating Facelets from Java classes with CDI beans.
  - Faces 4.0 added a new context param jakarta.faces.AUTOMATIC_EXTENSIONLESS_MAPPING for enabling automatic extensionless mapping so bar.xhtml can be access simply via \<url>/bar. Tests were added to verify this functionality with FacesServlet defined in web.xml and created programatically.
  - Improve <f:ajax> behavior in composite components since some components weren’t processed in the ajax calls. The behavior was correctly implemented in MyFaces, and only affected the Jakarta Faces API and tests were added for the tag with attributes execute=“@this” and render=“@this” within nested composite components.
  - Faces 4.0 made updates to make UIComponent#subscribeToEvent() more convenient. Previously, it allowed duplicates to exist, so a workaround was needed to avoid it. Tests were added to verify functionality as listed in specification.
  - Faces 4.0 added support for custom cookie attributes such as SameSite inExternalContext#addResponseCookie(). Tests were added to verify using the new API adding attributes like HttpOnly and SameSite to custom cookies.
  - Faces 4.0 renamed “http://xmlns.jcp.org/jsf/” URIs to “jakarta.faces.” URNs. Renames have been made across our test code to match new URNs and tests were added to verify actual usage of URNs.
  - Faces 4.0 renamed “JSF” to “Faces” all across the code (i.e. jsf.js -> faces.js). No specific tests but changes to our test code have been done for this rename.
  - Faces 4.0 removed all JSP support (Originally deprecated in JSF 2.0). Faces 4.0 and FacesContainer 4.0 features have removed the Pages feature, tests with JSPs and deprecated/removed functionality have been skipped and tests with JSPs but with current functionality have been updated to use xhtmls or others with the exception of some cases which are still under work.
  - Faces 4.0 removed native Managed Beans (ManagedBean annotation and related; Originally deprecated in JSF 2.3). Features have been updated to pull in CDI 4.0 by default and tests have been updated to skip ManagedBean specific functionality and update ManagedBeans to CDI beans for other functionality testing.
  - Faces 4.0 removed MethodBinding, ValueBinding and related. These were extensions of EL from javax.faces.el.* during JSF 1.0 development. Since there are a set of TCK signature tests that execute to ensure the API is correct and the changes were to remove classes and no functional behavior was introduced, no tests were added for this change.
  - Faces 4.0 removed CURRENT_COMPONENT constants from UIComponent class. Originally deprecated in JSF 2.1 in favor of UIComponent#getCurrentComponent() andUIComponent#getCurrentCompositeComponent() for getting the currentcomponent object. No tests were added for this since it is a removal from the UIComponent class.
  - Faces 4.0 removed deprecated methods of StateManager class. This change and similar changes to the API would be caught by the TCK signature tests because of this we verified the changes were correct but did not add tests.
  - Faces 4.0 removed entire ResourceResolver class. Originally deprecated in JSF 2.2 in favor of ResourceHandler#createViewResource(). Used to obtains URL to a facelet. No tests added for verifying removal of class since TCK signature tests would ensure the API is correct.

**Manual tests**: Due to JavaScript changes with the last release of MyFaces-4.0.0-RC5, tests using htmlunit tool for browser automation started failing due to incompatibilities with the tool being outdated. Manually the tests work and due to time constraints, we decided to skip failing tests and are using #24387 to manually test these skipped tests and automate them later on. This can eventually be done with a new version of htmlunit or by changing to using another browser with the Selenium tool but we will continue using 24387 for our progress with automating these tests again.

**Confidence**: 4. Feature tests have been passing with no major EE10 failures since enabling the feature. However, some tests were skipped from automation and are now manually tested. This is due to last minute contributions made to the MyFaces opensource which conflicted with the currently used tools for web browser automation (htmlunit). Our confidence is 4 because even though there are some tests skipped from automation, we have not run into issues with them reproducing them locally, therefore the functionality is still working as expected. Additionally, the com.ibm.ws.jsf_fat bucket in WS-CD-Open contains additional Faces tests, but this bucket has not been transformed due to framework conflicts.

## FacesContainer 4.0
**Repeated tests**: The bucket com.ibm.ws.jsfContainer_fat_2.3 has been enabled for repeat on EE10 for the FacesContainer 4.0 feature.

**New tests**: No new tests.

**Manual tests**: Not right now, still some more tests to enable to run.

**Confidence**: 4. Feature tests have been passing with no EE10 failures since enabling the feature but some tests are still not enabled to run on EE10 and we are working on enabling them.

**Comment by ayoho** [comment]
LGTM 👍
