### ISSUE TITLE
MicroProfile JWT with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21310]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by anjumfatima90** [comment]
1. The `testRolesEndpoint()` test verifies that the endpoints can be accessed correctly on restore. 
2. The `testUpdatedClockSkewOnRestore()` test updates the clockSkew after the checkpoint in order to decrease the expiration time of the JWT token. The test verifies that the authentication fails and the endpoint cannot be accessed on restore since the token was expired. The server is logged with error messages `"CWWKS5523E", "CWWKS5524E", "CWWKS6031E"`. 
3. The `testUpdatedAudienceOnRestore()` test updates the audience after the checkpoint and verifies that the authentication fails and the endpoint cannot be accessed since the updated audience is not listed under the trusted audience in the JWT configuration. The server is logged with error messages `"CWWKS5523E", "CWWKS5524E", "CWWKS6031E"`.

Note: The tests doesn't cover all the config properties mentioned [here](https://openliberty.io/docs/latest/reference/config/mpJwt.html).
