### ISSUE TITLE
MicroProfile Metrics with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21311]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by anjumfatima90** [comment]
The added tests checks if `/metrics` endpoint is available on https port. Since by default the mpMetrics config property `authentication` is set to true. 
The tests updates the config property `authentication` to false before the restore and verifies if the change is positively reflected during restore. After setting the property to false, the `/metrics` endpoint should be available on http port.

Note: The tests cover all the congig properties mentioned [here](https://openliberty.io/docs/latest/reference/config/mpMetrics.html).
