### ISSUE TITLE
WebProfile jsf / faces with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21327]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by tjwatson** [comment]
This is done, right Dave?

**Comment by dazavala** [comment]
The main concern about Checkpoint support for Faces is ManagedBean scoping (injection): Managed beans must be available to the application, with the expected state, when restoring a server without requiring the application to restart.  A secondary concern is whether `@CustomScoped` managed beans execute before checkpoint or during restore.

The initial verification for Jakarta Faces is provided by the following tests in the `io.openliberty.checkpoint_fat`:

The `FacesBeanTest` verifies that both CDI and JSF managed beans are available to the application upon restoring a checkpointed server, where the beans consume an EJB or JNDI resource. The application uses facelets -- xhtml files and managed beans -- to verify bean injection behavior. All managed beans are `@ApplicationScoped`, and `"eager=true"` for JSF beans, to verify beans instances created during checkpoint-at-application startup are available upon restore.

The` FacesTest` provides a more complex sample of a facelet client UI that interacts with a backend server which uses Jakarta Persistence with derby, and provides a restful service. The client UI is comprised of facelets that use @SessionScoped and @ViewScoped CDI managed beans; the test verifies the facelets (client UI) and the backend server function upon restoring the client JVM checkpointed `at-application`.   

The suite does not verify @CustomScoped JSF managed beans.  Note that the existing JSF/Faces FAT suites also do not verify @CustomScoped JSF managed beans, likely because the annotation is superceded by CDI custom scopes as a matter of preferred practice. Implementing a custom-scoped JSF managed bean is a complex, fringe development case. To verify custom scoping the test should use a managed bean with a CDI custom scope. 

Lastly, Jakarta Faces-4.0 (JakartaEE 10) introduced a couple changes that impact testing:

1. The @ManagedBean scope annotations (<managed-bean> XML configuration) were deprecated in Faces-2.3 and removed from the API in Faces-4.0. Test applications for Faces-4.0 must use the corresponding CDI annotations.

2. The Faces runtime no longer supports JSPs. The test application must use facelets to verify Faces behavior.
