### ISSUE TITLE
WebSocket 2.1: Review testZeroTimeOut and re-enable

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22022]
https://github.com/OpenLiberty/open-liberty/pull/22021/files 

The test was disabled in the EE10 test bucket as it was failing. Initial thought is this is due to infrastructure slowness.

Also: https://github.com/OpenLiberty/open-liberty/pull/22343

**Comment by volosied** [comment]
We can close this test since we still have coverage via testSSCZeroTimeOut.

It's the same test as testZeroTimeOut, but with Liberty as the client (rather than Jetty).

https://github.com/OpenLiberty/open-liberty/blob/08201219d6c6484d7b39e28f804cc47aefcdb6f3/dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java#L200-L206
