### ISSUE TITLE
Unit test failure in com.ibm.ws.crypto.ltpakeyutil on Oracle JDK

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#2219]
```
$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

Doing a top level `./gradlew build` fails with the following:
```
:com.ibm.ws.crypto.ltpakeyutil:test

com.ibm.ws.crypto.ltpakeyutil.LTPACryptoTest > testSignCorrect FAILED
    java.security.NoSuchAlgorithmException at LTPACryptoTest.java:68

com.ibm.ws.crypto.ltpakeyutil.LTPACryptoTest > testSignCorrectWithCacheOverFlow FAILED
    java.security.NoSuchAlgorithmException at LTPACryptoTest.java:99

24 tests completed, 2 failed
:com.ibm.ws.crypto.ltpakeyutil:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.ws.crypto.ltpakeyutil:test'.
> There were failing tests. See the report at: file:///C:/dev/proj/open-liberty/dev/com.ibm.ws.crypto.ltpakeyutil/build/libs/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

Relevant stack traces:
```
java.security.NoSuchAlgorithmException: no such algorithm: RSA for provider SunJCE
	at sun.security.jca.GetInstance.getService(GetInstance.java:87)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.KeyFactory.getInstance(KeyFactory.java:211)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.signISO9796(LTPACrypto.java:229)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACryptoTest.testSignCorrect(LTPACryptoTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

java.security.NoSuchAlgorithmException: no such algorithm: RSA for provider SunJCE
	at sun.security.jca.GetInstance.getService(GetInstance.java:87)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.KeyFactory.getInstance(KeyFactory.java:211)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACrypto.signISO9796(LTPACrypto.java:229)
	at com.ibm.ws.crypto.ltpakeyutil.LTPACryptoTest.testSignCorrectWithCacheOverFlow(LTPACryptoTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by una-tapa** [comment]
Thanks for finding the issue.  This is caused by following PR that incorrectly assumes that all the algorithms used in the ltpa package are in SunJCE provider. 

https://github.com/OpenLiberty/open-liberty/pull/2067/files

The fix will specify providers for each algorithm according to 
https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html

Unittest failure is seen in the reported package (com.ibm.ws.crypto.ltpakeyutil)  as well as com.ibm.ws.security.token.ltpa.  

==========================
com.ibm.ws.security.token.ltpa.internal.LTPAToken2FactoryTest > testValidateTokenBytes FAILED
13:40:23.971 [DEBUG] [TestEventLogger]     com.ibm.websphere.security.auth.InvalidTokenException
13:40:23.971 [DEBUG] [TestEventLogger]         at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.getBytes(LTPAToken2.java:323)
13:40:23.971 [DEBUG] [TestEventLogger]         at com.ibm.ws.security.token.ltpa.internal.LTPAToken2FactoryTest.testValidateTokenBytes(LTPAToken2FactoryTest.java:164)

 -- System.err -------------------------------------------------
13:40:23.941 [DEBUG] [TestEventLogger]     evaluate encountered unexpected exception: null
13:40:23.941 [DEBUG] [TestEventLogger]     java.lang.NullPointerException
13:40:23.941 [DEBUG] [TestEventLogger]          at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.sign(LTPAToken2.java:235)
13:40:23.942 [DEBUG] [TestEventLogger]          at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.sign(LTPAToken2.java:228)
13:40:23.942 [DEBUG] [TestEventLogger]          at com.ibm.ws.security.token.ltpa.internal.LTPAToken2.getBytes(LTPAToken2.java:320)
13:40:23.942 [DEBUG] [TestEventLogger]          at com.ibm.ws.security.token.ltpa.internal.LTPAToken2FactoryTest.testValidateTokenBytes(LTPAToken2FactoryTest.java:164)
13:40:23.942 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:40:23.942 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
========================
