### ISSUE TITLE
Faces 4.0: review third party packages as MyFaces has changed package contents

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22204]
1) bnd.bnd contains `io.openliberty.org.apache.myfaces.4.0;version=project` which is the difference between `project` and `latest`.
2) review and update packages in bnd.bnd and `faces-4.0` feature.
3) Is the following buildpath necessary as well as 1) above? `org.apache.myfaces.core:myfaces-impl;version=${Implementation-Version}`
4) Create Third Party tests in Faces 4.0

**Comment by volosied** [comment]
From BJ Hargrave: 
```
version=project means the project’s bin folder (where the compiled classes live). version=latest means the project’s built jar. You almost always want version=latest
```




As for the two dependencies, I don't think both are necessary. I compared the original jar to different build paths:

```
io.openliberty.org.apache.myfaces.4.0;version=latest, \
org.apache.myfaces.core:myfaces-impl;version=${Implementation-Version},\
```
Same as original.  No differences found. 

_____
```
io.openliberty.org.apache.myfaces.4.0;version=latest
```
Class files weren't included in this build path.  Import-Packages was missing classes; Export-Packages was missing.  
_____
```
 org.apache.myfaces.core:myfaces-impl;version=${Implementation-Version}
 ```
 
 Classes were included, but the manifest was slightly different.  There was an extra version added (see left). 
 
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/5934310/191362645-c63a8935-2013-4ffe-9685-14eefccc284a.png">

**Comment by volosied** [comment]
I think we should go with `-buildpath: org.apache.myfaces.core:myfaces-impl;version=${Implementation-Version}`.

**Comment by volosied** [comment]
We will need to update the feature file for third party exports: 
https://github.com/OpenLiberty/open-liberty/blob/b81fdd48d843e6838c7414221bf5bdbec0232b27/dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/io.openliberty.faces-4.0.feature#L29-L33


Also I will discuss with Paul about exporting the 4.0 api package: `org.apache.myfaces.core.api.shared.*`

**Comment by volosied** [comment]
2 was done in https://github.com/OpenLiberty/open-liberty/pull/23078

**Comment by volosied** [comment]
Ignore my earlier sept 20, 2022 comment about 

```
 io.openliberty.org.apache.myfaces.4.0;version=project, \  
 org.apache.myfaces.core:myfaces-impl;version=${Implementation-Version}
```

` io.openliberty.org.apache.myfaces.4.0;version=project, \  ` is probably there just because we can place all our overlays in the ` io.openliberty.org.apache.myfaces.4.0` project and then have those pulled in the third party bundle. 

Third Party Labels look right ( but they could use some reorganization):
https://github.com/OpenLiberty/open-liberty/blob/d3cbd16e5e85286d58106a8fb0a25b7e04d6dece/dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/io.openliberty.faces-4.0.feature#L31-L35

As for the included class files, there are differences between 4.0 and our earlier third party bundles. However, they changes are due to refactoring.   Otherwise, the only main difference is the location of the MyfacesConfig class. 

3.0 Classes:
org/apache/myfaces/renderkit/html/EarlyFlushHtmlResponseWriterImpl.class  
org/apache/myfaces/renderkit/html/HtmlAjaxBehaviorRenderer.class  
org/apache/myfaces/renderkit/html/HtmlBodyRenderer.class  
org/apache/myfaces/renderkit/html/HtmlButtonRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCheckboxRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCompositeComponentRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCompositeFacetRenderer.class  
org/apache/myfaces/renderkit/html/HtmlDoctypeRenderer.class  
org/apache/myfaces/renderkit/html/HtmlFormRenderer.class  
org/apache/myfaces/renderkit/html/HtmlFormatRenderer.class  
org/apache/myfaces/renderkit/html/HtmlGridRenderer.class  
org/apache/myfaces/renderkit/html/HtmlGroupRenderer.class  
org/apache/myfaces/renderkit/html/HtmlHeadRenderer.class  
org/apache/myfaces/renderkit/html/HtmlHiddenRenderer.class  
org/apache/myfaces/renderkit/html/HtmlImageRenderer.class  
org/apache/myfaces/renderkit/html/HtmlInputFileRenderer.class  
org/apache/myfaces/renderkit/html/HtmlLabelRenderer.class  
org/apache/myfaces/renderkit/html/HtmlLinkRenderer.class  
org/apache/myfaces/renderkit/html/HtmlListboxRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMenuRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMessageRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMessagesRenderer.class  
org/apache/myfaces/renderkit/html/HtmlOutcomeTargetButtonRenderer.class  
org/apache/myfaces/renderkit/html/HtmlRadioRenderer.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl$LazyRendererWrapper.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl$MyFacesResponseStream.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl.class  
org/apache/myfaces/renderkit/html/HtmlResponseStateManager.class  
org/apache/myfaces/renderkit/html/HtmlScriptRenderer.class  
org/apache/myfaces/renderkit/html/HtmlSecretRenderer.class  
org/apache/myfaces/renderkit/html/HtmlStylesheetRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTableRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTextRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTextareaRenderer.class  

org/apache/myfaces/shared/config/MyfacesConfig.class  

org/apache/myfaces/shared/renderkit/ClientBehaviorEvents.class  
org/apache/myfaces/shared/renderkit/ContentTypeUtils.class  
org/apache/myfaces/shared/renderkit/JSFAttr.class  
org/apache/myfaces/shared/renderkit/RendererUtils$1.class  
org/apache/myfaces/shared/renderkit/RendererUtils$PassThroughAsStringConverter.class  
org/apache/myfaces/shared/renderkit/RendererUtils.class  
org/apache/myfaces/shared/renderkit/_SharedRendererUtils.class  

org/apache/myfaces/shared/renderkit/html/CommonEventConstants.class  
org/apache/myfaces/shared/renderkit/html/CommonEventUtils.class  
org/apache/myfaces/shared/renderkit/html/CommonPropertyConstants.class  
org/apache/myfaces/shared/renderkit/html/CommonPropertyUtils.class  
org/apache/myfaces/shared/renderkit/html/HTML.class  
org/apache/myfaces/shared/renderkit/html/HtmlBodyRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlButtonRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlCheckboxRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlFormRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlGridRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlGroupRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlImageRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlInputFileRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlJavaScriptUtils.class  
org/apache/myfaces/shared/renderkit/html/HtmlLinkRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlListboxRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlMenuRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlMessageRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlMessagesRendererBase$MessagesIterator.class  
org/apache/myfaces/shared/renderkit/html/HtmlMessagesRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlOutcomeTargetButtonRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlRadioRendererBase$GetSelectItemListCallback.class  
org/apache/myfaces/shared/renderkit/html/HtmlRadioRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlRenderer.class  
org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils$LinkParameter.class  
org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils$ScriptContext.class  
org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils$SelectOneGroupSetSubmittedValueCallback.class  
org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils.class  
org/apache/myfaces/shared/renderkit/html/HtmlResponseWriterImpl.class  
org/apache/myfaces/shared/renderkit/html/HtmlSecretRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlSelectableRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlTableRendererBase$Styles.class  
org/apache/myfaces/shared/renderkit/html/HtmlTableRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlTextRendererBase.class  
org/apache/myfaces/shared/renderkit/html/HtmlTextareaRendererBase.class  
org/apache/myfaces/shared/renderkit/html/JavascriptContext.class  

org/apache/myfaces/shared/renderkit/html/util/FormInfo.class  
org/apache/myfaces/shared/renderkit/html/util/HTMLEncoder.class  
org/apache/myfaces/shared/renderkit/html/util/HttpPartWrapper.class  
org/apache/myfaces/shared/renderkit/html/util/JavascriptUtils.class  
org/apache/myfaces/shared/renderkit/html/util/OutcomeTargetUtils.class  
org/apache/myfaces/shared/renderkit/html/util/ResourceUtils.class  
org/apache/myfaces/shared/renderkit/html/util/SelectItemInfo.class  
org/apache/myfaces/shared/renderkit/html/util/SelectItemsUtils.class  
org/apache/myfaces/shared/renderkit/html/util/SharedStringBuilder.class  
org/apache/myfaces/shared/renderkit/html/util/UnicodeEncoder.class  

4.0 Classes: 
org/apache/myfaces/config/webparameters/MyfacesConfig.class  

org/apache/myfaces/renderkit/ClientBehaviorEvents.class  
org/apache/myfaces/renderkit/ContentTypeUtils.class  
**org/apache/myfaces/renderkit/ErrorPageWriter$ErrorPageBean.class  
org/apache/myfaces/renderkit/ErrorPageWriter$ExtendedComponentTreeVisitCallback.class  
org/apache/myfaces/renderkit/ErrorPageWriter.class  
org/apache/myfaces/renderkit/LazyRenderKit.class  
org/apache/myfaces/renderkit/MyfacesResponseStateManager.class  
org/apache/myfaces/renderkit/RenderKitFactoryImpl.class**  
org/apache/myfaces/renderkit/RendererUtils$PassThroughAsStringConverter.class  
org/apache/myfaces/renderkit/RendererUtils.class  

org/apache/myfaces/renderkit/html/EarlyFlushHtmlResponseWriterImpl.class  
org/apache/myfaces/renderkit/html/HtmlAjaxBehaviorRenderer.class  
org/apache/myfaces/renderkit/html/HtmlBodyRenderer.class  
org/apache/myfaces/renderkit/html/HtmlButtonRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCheckboxRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCompositeComponentRenderer.class  
org/apache/myfaces/renderkit/html/HtmlCompositeFacetRenderer.class  
org/apache/myfaces/renderkit/html/HtmlDoctypeRenderer.class  
org/apache/myfaces/renderkit/html/HtmlFormRenderer.class  
org/apache/myfaces/renderkit/html/HtmlFormatRenderer.class  
org/apache/myfaces/renderkit/html/HtmlGridRenderer.class  
org/apache/myfaces/renderkit/html/HtmlGroupRenderer.class  
org/apache/myfaces/renderkit/html/HtmlHeadRenderer.class  
org/apache/myfaces/renderkit/html/HtmlHiddenRenderer.class  
org/apache/myfaces/renderkit/html/HtmlImageRenderer.class  
org/apache/myfaces/renderkit/html/HtmlInputFileRenderer.class  
org/apache/myfaces/renderkit/html/HtmlLabelRenderer.class  
org/apache/myfaces/renderkit/html/HtmlLinkRenderer.class  
org/apache/myfaces/renderkit/html/HtmlListboxRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMenuRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMessageRenderer.class  
org/apache/myfaces/renderkit/html/HtmlMessagesRenderer.class  
org/apache/myfaces/renderkit/html/HtmlOutcomeTargetButtonRenderer.class  
org/apache/myfaces/renderkit/html/HtmlRadioRenderer.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl$LazyRendererWrapper.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl$MyFacesResponseStream.class  
org/apache/myfaces/renderkit/html/HtmlRenderKitImpl.class  
org/apache/myfaces/renderkit/html/HtmlResponseStateManager.class  
org/apache/myfaces/renderkit/html/HtmlResponseWriterImpl.class  
org/apache/myfaces/renderkit/html/HtmlScriptRenderer.class  
org/apache/myfaces/renderkit/html/HtmlSecretRenderer.class  
org/apache/myfaces/renderkit/html/HtmlStylesheetRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTableRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTextRenderer.class  
org/apache/myfaces/renderkit/html/HtmlTextareaRenderer.class  

org/apache/myfaces/renderkit/html/base/HtmlBodyRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlButtonRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlCheckboxRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlFormRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlGridRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlGroupRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlImageRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlInputFileRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlLinkRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlListboxRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlMenuRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlMessageRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlMessagesRendererBase$MessagesIterator.class  
org/apache/myfaces/renderkit/html/base/HtmlMessagesRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlOutcomeTargetButtonRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase$GetSelectItemListCallback.class  
org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlRenderer.class  
org/apache/myfaces/renderkit/html/base/HtmlSecretRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlSelectableRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlTableRendererBase$Styles.class  
org/apache/myfaces/renderkit/html/base/HtmlTableRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlTextRendererBase.class  
org/apache/myfaces/renderkit/html/base/HtmlTextareaRendererBase.class  

org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.class  
org/apache/myfaces/renderkit/html/util/ClientBehaviorRendererUtils.class  
org/apache/myfaces/renderkit/html/util/CommonHtmlAttributesUtil.class  
org/apache/myfaces/renderkit/html/util/CommonHtmlEventsUtil.class  
org/apache/myfaces/renderkit/html/util/ComponentAttrs.class  
org/apache/myfaces/renderkit/html/util/HTML.class  
org/apache/myfaces/renderkit/html/util/HTMLEncoder.class  
org/apache/myfaces/renderkit/html/util/HtmlJavaScriptUtils.class  
org/apache/myfaces/renderkit/html/util/HtmlRendererUtils$SelectOneGroupSetSubmittedValueCallback.class  
org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.class  
org/apache/myfaces/renderkit/html/util/HttpPartWrapper.class  
org/apache/myfaces/renderkit/html/util/JavascriptContext.class  
org/apache/myfaces/renderkit/html/util/JavascriptUtils.class  
org/apache/myfaces/renderkit/html/util/OutcomeTargetUtils.class  
org/apache/myfaces/renderkit/html/util/ResourceUtils.class  
org/apache/myfaces/renderkit/html/util/SelectItemInfo.class  
org/apache/myfaces/renderkit/html/util/SelectItemsUtils.class  
org/apache/myfaces/renderkit/html/util/UnicodeEncoder.class

**Comment by volosied** [comment]
Closing -- there are some differences as mentioned due to merging of the impl and shared folders.  Paul and I don't see any problem with these changes.  I think the third party api is good to go!
