### ISSUE TITLE
Cannot start Jenkins 2.346.3 with Java 17 when using AD authentication

### ISSUE THREAD

**Issue by FireBurn** [OpenLiberty/open-liberty#22361]
**Describe the bug**  

When using AD authentication on Jenkins with OpenLiberty 22.0.0.9 running on Java 17 I see the following message:

0000002f com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalAccessException: class com.ibm.ws.jndi.internal.WASInitialContextFactoryBuilder cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to unnamed module @3ce42ee7 com.ibm.ws.jndi.internal.WASInitialContextFactoryBuilder 58" at ffdc_22.08.31_18.04.56.0.log

FFDC attached:
[ffdc_22.08.31_18.04.56.0.log](https://github.com/OpenLiberty/open-liberty/files/9468336/ffdc_22.08.31_18.04.56.0.log)

This doesn't happen with Java 11

**Steps to Reproduce**  

Start Jenkins with Java17

**Expected behavior**  

The app to start successfully

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.9
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: 17.0.4
 - server.xml configuration (WITHOUT sensitive information like passwords) [server.xml.txt](https://github.com/OpenLiberty/open-liberty/files/9468383/server.xml.txt)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  

I fixed the issue by adding:

```
--add-exports
jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED
```

to:

`${wlp.install.dir}/lib/platform/java/java9.options`

**Comment by gjwatts** [comment]
@FireBurn Mike, Thank you for taking the time to bring this to our attention and even provide a fix!

**Comment by FireBurn** [comment]
Do I need to do anything else for the PR? I've signed the CLA

**Comment by jwalcorn** [comment]
Note we're seeing this too in Stock Trader, even though we're not using AD or Jenkins.  The real trigger is using Liberty with Java 17.  Any chance of getting 22.0.0.9 respun with this (non-code, just a configuration file) fix, since the Liberty Java 17 image now in DockerHub is broken without this?  Otherwise, we're waiting till the end of the year (22.0.0.12) for an LTS release that works on Java 17.  Right now we have to drop back to Java 11, though I've considered a hack of updating my Dockerfile to add a COPY of this `java9.options` file into the image right after my FROM line that starts with the Java 17 flavor of Liberty.  fyi @NottyCode
