### ISSUE TITLE
A race condition of transaction timeout could leave an indout transaction at RM side

### ISSUE THREAD

**Issue by e30532** [OpenLiberty/open-liberty#22434]
When a transaction timeout happens, there is a race condition where the XA resoruce is disassociated from the transaction before the actual abort. Thus, the abort processing doesn't cleanup the pending transaction at RM side.

Liberty 21.0.0.11
JDBC driver Name: Microsoft JDBC Driver 7.2 for SQL Server

For the full context..
Reference: TS010378986

**Comment by jmstephensgit** [comment]
Some information pulled from the reference: TS010378986 from 8/26/2022 7:42 AM to help in the fix.

"There is a test in PoolManager.release to check if MCWrapper.isMCAborted

The WSRdbManagedConnection.impl has an aborted boolean - that should have been set to true (on the same thread) after calling the real connection's abort method (which will execute on the Executor thread) and before the call to PoolManager.release().

NOTE the MCWrapper has its own aborted flag - that should have been set to true in roughly the same place.

These booleans are not volatile nor atomic nor accessed in synch blocks, yet the trace indicates that the path taken through the PoolManager.release() code is that taken as if aborted was false. 

NOTE the objects are being used on multiple threads simultaneously however and there's also synch blocks that are entered and exited in the J2C code (particularly the PoolManager) that will act as JMM 'memory barriers'.

In summary...

1) the transaction service IS calling XAResource.end/rollback

2) it shouldn't matter that J2C doesn't call the real connection for those operations (on the main transaction execution thread) once the connection has been aborted (including if there is an outstanding attempt to abort)

3) there was a race condition between the Executor thread and the Timeout Alarm thread BUT there was J2C code to cater for that but there appears to be a thread-safely/visibility issue there.

4) My contention is that the J2C code executing in the timeout thread should NOT be calling (and was intended NOT to call) XAResource.end on the XAResource associated with the aborted/aborting connection."

At minimum, the booleans should be changed to AtomicBooleans.   Since we are aborting, in addition to the AtomicBoolean change, the interation between J2C and the adapter code should be reviewed for added synchronization.

**Comment by e30532** [comment]
@jmstephensgit Do you have any update on this?

**Comment by jmstephensgit** [comment]
Delivered under pull,  https://github.com/OpenLiberty/open-liberty/pull/22687.
