### ISSUE TITLE
Resolve Java 2 Security issues in mpTelemetry-1.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#22689]
The TCK is only passing by giving the app all J2S permissions in the server.xml; that shouldn’t really be there and it ought to be failing in the Full FAT J2S builds...

https://github.com/OpenLiberty/open-liberty/blob/30413b4b7e78f81c874d5058e26d61dd2b654cfa/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/servers/Telemetry10TCKServer/server.xml#L21

**Comment by Azquelt** [comment]
We think we've resolved the J2S issues by eagerly initializing parts of open telemetry.

The FATs are passing with J2S enabled but we still need to enable J2S for the TCK FAT.

**Comment by Azquelt** [comment]
The FATs are not passing with J2S enabled, there is a whole list of permissions granted to the test application that should not be: [permissions.xml](https://github.com/OpenLiberty/open-liberty/blob/b3539b9369e49b67d2da2a7645f3f1d023c1d702/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/permissions.xml#L7-L25)

**Comment by Azquelt** [comment]
We have fixed up the existing FAT tests so that they no longer have improper permissions and they are no longer failing in the J2S Full FAT build. We have also removed permissions from the TCK FAT as far as possible (though arquillian runs some code on the server which requires reflection so quite a few permissions are still required).

That's all we can do for now. As we add more FAT tests, we may see more J2S failures but we will address those as they arise.

All the known problems are fixed so I'm closing this issue.
