### ISSUE TITLE
WebProfile jpa / persistence with checkpoint

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#22973]
Writeup of discussions with @dazey3 and @jgrassel 

Work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

JPA needs to support startup under a checkpoint command. For apps using a database, the dataSource configuration is typically not known at server checkpoint time but is provided at server restore time. 

- The goal is to allow JPA to come up without any DS config (db name, db port, etc) present at checkpoint time, and respond correctly to the DS config present at restore time, without restarting the app.

- Allow JPA to complete as much usable work as feasible prior to checkpoint to save that cost at restore.

Currently JPA does not respond to dynamic update of datasource config. There is work underway to fix that by the JPA team, however the general soution to restart the app, will not be suitable for a checkpoint scenario where the restore performance is key.

The solution of delaying the DataSource component until restore time does allow JPA to work with checkpoint, but causes issues elsewhere. 

Using java:comp/env references was suggested as a possible limiting workaround but remains to be tested.

**Comment by dazey3** [comment]
JPA Container performs a datasource lookup during the persistence unit processing and application start. The persistence provider needs to register a class transformer during application start, so we have to create an EntityManagerFactory instance at that time. 

However, the JPA Container does already have an existing functionality that delays EntityManagerFactory creation, without disrupting class transformer registration. If the application defines a datasource in the component naming context (`java:comp/env`), then the JPA Container creates a mock DataSource instance. That mock DataSource is passed to the JPA Provider during EntityManagerFactory creation. This EntityManagerFactory is ONLY being created to transform persistence classes; something that the JPA Provider doesn't need a valid datasource connection for. Later, when the application is finally used, the "mock" EntityManagerFactory instance is thrown out, along with the "mock" datasource, and a new EntityManagerFactory is created, and EntityManager's provided for injection references. 

In order to add the required InstantOn support to JPA Container, we plan on taking advantage of this existing `java:comp/env` support so that Checkpoint can enable JPA Container to delay EntityManagerFactory creation until later. 

The first part of this support will be the delivery of a feature to expose the JPA Container configuration of delaying EntityManagerFactory creation until application usage. To configure this, a user would enable the property via the jpa server.xml configuration:
```xml
    <jpa delayEntityManagerFactoryCreate="true"/>
```
The default would be false; unless a persistence unit uses a `java:comp/env` datasource. 

The second part of this support will be for Checkpoint/InstantOn to take advantage of this configuration within the JPA Container, depending on the configured Checkpoint setting.
