### ISSUE TITLE
Update mvn in the build

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23198]
We are currently using Apache Maven verison 2.2.1 which is pretty old. Want to move up to the latest stable version. However, a pre-req to this is to make sure that all configured repositories are using `https` rather than `http`.

**Comment by tevans78** [comment]
Turns out that we are using multiple versions of maven for different purposes. The version that runs TCKs has now been updated to 3.8.6. However, there is a checked in version 2.2.1 which is used for building Liberty artifacts. That should be updated too but is less urgent and more complicated because of some other dependencies.

**Comment by tevans78** [comment]
We (the MicroProfile squad) are not going to do any more work on this. The version of Maven used by the TCKs is now completely disconnected from the other versions used in the build. Whe updates are made to the other parts of the build, they will be done by another team.
