### ISSUE TITLE
mpMetrics-5.0 produces FFDC when dynamically changing authentication from true to false

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#23314]
This issue does not happen with previous versions of mpMetrics only with `mpMetrics-5.0`.

When launching the server with `<mpMetrics authentication="true"/>` and then while the server is up change the setting to `false` then the following FFDC is produced and I assume stuff is broken:

[ffdc_22.11.10_08.51.36.0.log](https://github.com/OpenLiberty/open-liberty/files/9981993/ffdc_22.11.10_08.51.36.0.log)

Here is a server configuration to reproduce.

[mpMetrics.zip](https://github.com/OpenLiberty/open-liberty/files/9982130/mpMetrics.zip)

**Comment by Channyboy** [comment]
First addressed as part of https://github.com/OpenLiberty/open-liberty/pull/23348
Updated as part of : https://github.com/OpenLiberty/open-liberty/pull/23693

This issue occurs due to the `SmallryeMetricsCDIMetadata` re-activating when it detects a config change to the metrics feature.
This reloads the Smallrye and micrometer related libraries (which are loaded as part of the bundle add-on classloader). This causes a class path issue for code access. 

The metrics config currently only contains the `authentication` and `libraryRef` attribute.
These are not expected to change during runtime. Only the `authentication` attribute can be changed dynamically during runtime and the `libraryRef` requires a server restart. Note that the `authentication` attribute is handled separately by the `MetricConfig` service component.

The updated solution includes a `@Modified` annotation to `SmallryeMetricsCDIMetadata` which provides an `info` message regarding the need to restart if the `libraryRef` attribute was changed.
