### ISSUE TITLE
InstantOn with IBM Cloud

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#23517]
There are two services we are targeting:
* [IBM Kubernetes Service](https://www.ibm.com/cloud/kubernetes-service) (IKS)
* [IBM Cloud Code Engine](https://www.ibm.com/cloud/code-engine/) (ICCE)

**Comment by jgawor** [comment]
### IKS

I used the default selections to create a `Standard` cluster on classic infrastructure. Selected Kubernetes version v1.24 to ensure `containerd` container engine.

Node information:
```
$ kubectl get node -o wide
NAME            STATUS   ROLES    AGE   VERSION       INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
10.166.113.15   Ready    <none>   30m   v1.24.8+IKS   10.166.113.15   xxx.xx.x.xx   Ubuntu 18.04.6 LTS   4.15.0-197-generic   containerd://1.6.10

```

Deployed [deployment.yaml](https://github.com/jgawor/guide-getting-started/blob/instanton/finish/deployment.yaml) and noticed the following restore failure:
```
$ kubectl logs open-liberty-instanton-64cbb855db-sc6vr
CRIU needs to have the CAP_SYS_ADMIN or the CAP_CHECKPOINT_RESTORE capability: 
setcap cap_checkpoint_restore+eip criu
(00.000000) Effective capability 40 missing
(00.000000) Effective capability 21 missing
CWWKE0957I: Restoring the checkpoint server process failed. Check the /logs/checkpoint/restore.log log to determine why the checkpoint process was not restored. Launching the server without using the checkpoint image.
```

**Status**: The nodes are running an older kernel version so unprivileged restore **does not work**. Kernel 5.9 or higher is needed. Privileged restore does work.
 
## ICCE

ICCE runs on top of shared (multi-tenant) IKS cluster and uses [Knative for application scaling](https://cloud.ibm.com/docs/codeengine?topic=codeengine-knative). ICCE exposes partial Kubernetes API but does not allow enabling additional Linux capabilities to the Knative service. 

**Status**: InstantOn does not work because of a) the dependency on IKS and proper kernel version and 2) no way to enable additional Linux capabilities.

**Comment by jgawor** [comment]
IKS is now offering worker nodes with Ubuntu 20 (instead of 18) - see https://cloud.ibm.com/docs/containers?topic=containers-ubuntu-migrate. The new worker nodes appear to be running with kernel 5.4.
```
$ kubectl get node -o wide
NAME            STATUS   ROLES    AGE   VERSION       INTERNAL-IP     EXTERNAL-IP    OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
10.113.81.148   Ready    <none>   11m   v1.24.9+IKS   10.113.81.148   xxx.x.xxx.xx   Ubuntu 20.04.5 LTS   5.4.0-135-generic   containerd://1.6.12
```

**Status**: Kernel is updated but still not 5.9 or higher.

**Comment by tjwatson** [comment]
> IKS is now offering worker nodes with Ubuntu 20 (instead of 18) - see https://cloud.ibm.com/docs/containers?topic=containers-ubuntu-migrate. The new worker nodes appear to be running with kernel 5.4.

CAP_CHECKPOINT_RESTORE was not added until kernel 5.9

**Comment by jgawor** [comment]
@tjwatson yes. just documenting some progress on IKS front.

**Comment by jgawor** [comment]
Provisioned a IKS cluster today with Ubuntu 20 nodes. Only minor updates notes:
```
$ kubectl get node -o wide
NAME            STATUS   ROLES    AGE   VERSION       INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
10.166.113.15   Ready    <none>   19m   v1.24.9+IKS   10.166.113.15   169.48.5.87   Ubuntu 20.04.5 LTS   5.4.0-137-generic   containerd://1.6.15
```

**Comment by tjwatson** [comment]
Does IKS have the ability to provision the Ubuntu enablement stack (https://ubuntu.com/kernel/lifecycle)

Locally that is done with:

```
sudo apt-get install --install-recommends linux-generic-hwe-20.04
```
That gets you a 5.15 level kernel.

**Comment by tjwatson** [comment]
I don't believe there is anything else left to track here.  For new issues/enhancements for cloud we should use a new Epic.
