### ISSUE TITLE
Review Faces 4.0 API Imports

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#23554]
Need to review if all the imports are necessary, particularly `com.ibm.ws.managedobject, \` : 

https://github.com/OpenLiberty/open-liberty/blob/2eccf697cb732eac5290fc873f36627b31945483/dev/io.openliberty.jakarta.faces.4.0/bnd.bnd#L27-L31

**Comment by tevans78** [comment]
I think that JSF 2.2 needed these dynamic imports and they were just blindly copied forwards into JSF 2.3, Faces 3.0 and Faces 4.0. If not needed then they should be removed from all API bundles, not just 4.0.

**Comment by isaacrivriv** [comment]
After some investigation, these packages are still needed due to faces-4 still using a custom InjectionProvider [WASCDIAnnotationInjectionProvider](https://github.com/OpenLiberty/open-liberty/blob/3116a7f081a8b6ceecc6f9fc1ccd088a3b85d892/dev/io.openliberty.faces.4.0.internal/src/io/openliberty/faces40/internal/cdi/WASCDIAnnotationInjectionProvider.java). I opened up #24202 to investigate if we can use the default provider for this but this is something we can do after GA. Closing and following up there.
