### ISSUE TITLE
Investigate java.lang.ClassNotFoundException in Faces-4.0

### ISSUE THREAD

**Issue by isaacrivriv** [OpenLiberty/open-liberty#23610]
Enabling EE10 in tests, found an exception using faces-4.0 with an xhtml with the line `application implicit object test: <h:outputText id="out1" value="#{application.servletContextName}"/> ` . When accessing **application.servletContextName** hit the following exception.

> Exception thrown by application class 'jakarta.faces.webapp.FacesServlet.service:255'
> jakarta.servlet.ServletException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade
> at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:255)
> at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
> at [internal classes]
> Caused by: java.lang.NoClassDefFoundError: com.ibm.wsspi.webcontainer.facade.ServletContextFacade
> at .apply(Unknown Source)
> at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:75)
> at [internal classes]
> at jakarta.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:339)
> at jakarta.faces.component.UIOutput.getValue(UIOutput.java:69)
> at org.apache.myfaces.renderkit.RendererUtils.getValue(RendererUtils.java:331)
> at org.apache.myfaces.renderkit.RendererUtils.getStringValue(RendererUtils.java:173)
> at org.apache.myfaces.renderkit.html.base.HtmlTextRendererBase.renderOutput(HtmlTextRendererBase.java:132)
> at org.apache.myfaces.renderkit.html.base.HtmlTextRendererBase.encodeEnd(HtmlTextRendererBase.java:122)
> at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:634)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:523)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1778)
> ... 1 more
> Caused by: java.lang.ClassNotFoundException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade cannot be found by com.ibm.ws.webcontainer.servlet.4.0.jakarta_1.0.72.202212020909
> ... 20 more

**Comment by isaacrivriv** [comment]
After some investigation, @volosied found that it is due to the use of Lambda invocations in faces whereas before reflection was used. The error can be reproduced with the following code and can be fixed by adding the package import to the bnd of the servlet-4 bundle. Not sure why the issue pops up with lambda invocations but not reflection, would need to investigate further

```java
package com.test.servlet;

import java.io.IOException;
import java.lang.invoke.CallSite;
import java.lang.invoke.LambdaMetafactory;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import java.util.function.Function;

import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Test Servlet that just prints a message in the Response.
 *
 */
@WebServlet("/TestServlet")
public class TestServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        //WORKING
        ServletContext context = request.getServletContext();
        System.out.println(context);
        System.out.println(context.getServletContextName());


        // FAILING
        try {
            Method privateLookupIn = MethodHandles.class.getMethod("privateLookupIn", Class.class,
                    MethodHandles.Lookup.class);

            MethodHandles.Lookup lookup = (MethodHandles.Lookup) privateLookupIn.invoke(null, context.getClass(),
                    MethodHandles.lookup());

            Method readMethod = context.getClass().getMethod("getServletContextName", null);
            MethodHandle handle = lookup.unreflect(readMethod);
            CallSite callSite = LambdaMetafactory.metafactory(lookup,
                    "apply",
                    MethodType.methodType(Function.class),
                    MethodType.methodType(Object.class, Object.class),
                    handle,
                    handle.type());
            ((Function<Object, Object>) callSite.getTarget().invokeExact()).apply(context);
        } catch (ClassNotFoundException noClassException) {
            System.out.println(noClassException.getMessage());
        } catch (Throwable e) {
            System.out.println("SOMETHING WENT WRONG" + e.getMessage());
        }

    }
}
```

**Comment by tjwatson** [comment]
> ```java
>             MethodHandles.Lookup lookup = (MethodHandles.Lookup) privateLookupIn.invoke(null, context.getClass(),
>                    MethodHandles.lookup());
> 
>             Method readMethod = context.getClass().getMethod("getServletContextName", null);
> ```

I suspect the issue is the lines above.  There the context variable is of type `jakarta.servlet.ServletContext`, but the actual class for the context implementation is `com.ibm.wsspi.webcontainer.facade.ServletContextFacade` which is what is returned by `context.getClass()`.  So the `Method readMethod` ends up being the actual `getServletContextName` method from the implementation class, not the `jakarta.servlet.ServletContext` interface.

What if you change `context.getClass()` to `ServletContext.class`? instead?

**Comment by isaacrivriv** [comment]
Thanks for looking into it @tjwatson! I'll try that out soon and comment back what I find.

**Comment by isaacrivriv** [comment]
Made the change and still hit the same error. This is the stack trace I hit with the changes with the reproducer, its the same as the original
```
java.lang.NoClassDefFoundError: com.ibm.wsspi.webcontainer.facade.ServletContextFacade
at <unknown class>.apply(Unknown Source)
at testservlet40.servlets.TestServlet.doGet(TestServlet.java:54)
at <unknown class>.service(HttpServlet.java:527)
at <unknown class>.service(HttpServlet.java:614)
at <unknown class>.service(ServletWrapper.java:1258)
at <unknown class>.handleRequest(ServletWrapper.java:746)
at <unknown class>.handleRequest(ServletWrapper.java:443)
at <unknown class>.invokeFilters(WebAppFilterManager.java:1294)
at <unknown class>.handleRequest(WebApp.java:5078)
at <unknown class>.handleRequest(DynamicVirtualHost.java:316)
at <unknown class>.handleRequest(WebContainer.java:1007)
at <unknown class>.run(DynamicVirtualHost.java:281)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1246)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
at <unknown class>.handleDiscrimination(HttpInboundLink.java:567)
at <unknown class>.handleNewRequest(HttpInboundLink.java:501)
at <unknown class>.processRequest(HttpInboundLink.java:361)
at <unknown class>.ready(HttpInboundLink.java:328)
at <unknown class>.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
at <unknown class>.complete(NewConnectionInitialReadCallback.java:75)
at <unknown class>.requestComplete(WorkQueueManager.java:514)
at <unknown class>.attemptIO(WorkQueueManager.java:584)
at <unknown class>.workerRun(WorkQueueManager.java:968)
at <unknown class>.run(WorkQueueManager.java:1057)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: 
 java.lang.ClassNotFoundException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade cannot be found by io.openliberty.jakarta.servlet.6.0_1.0.73.202301051012
at <unknown class>.generateException(BundleLoader.java:541)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1086)
... 29 more
```

**Comment by tjwatson** [comment]
Lambdas will eventually want to have a variable that is the type expected.  Somehow I think the lambda getting generated here has a function that is taking a `ServletContextFacade` instead of the expected `ServletContext`.  We may need some help from the JVM team to understand the shape of the lambda that is getting generated here.

**Comment by volosied** [comment]
I’ve been reviewing this problem, looking at it from various angles, and I think I have a slightly better understanding of the issue.  The relevant parts are this: 

Firstly, if we rework the code a bit and print out the objects, we'll get: 
```

Function<Object, Object> lambdaFunction = (Function<Object, Object>) callSite.getTarget().invokeExact()
System.out.println(lambdaFunction); 
// -> com.ibm.ws.webcontainer40.facade.ServletContextFacade40$$Lambda$448/0x0000000800a61c40@feaea41

System.out.println(lambdaFunction.getClass().getClassLoader()); 
// -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@b06ec66[com.ibm.ws.webcontainer.servlet.4.0.jakarta:1.0.74.202302171341(id=79)]
```

This lambda function looks like an extension of the ServletContextFacade40, and it throws java.lang.ClassNotFoundException if we call apply (with any argument value). 

Then, I stumbled upon this property jdk.internal.lambda.dumpProxyClasses (more can be found here: https://bugs.openjdk.org/browse/JDK-8023524)

So I dumped (via the property above) the generated lambda function (see attached [facade.zip](https://github.com/OpenLiberty/open-liberty/files/10832915/facade.zip) )

And using JD-GUI and javap  , I’ve been able to see what this function / inner classfile? (ServletContextFacade40$$Lambda$338.class)  actually looks like: 
```
{
  public java.lang.Object apply(java.lang.Object);
    descriptor: (Ljava/lang/Object;)Ljava/lang/Object;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: aload_1
         1: checkcast     #15                 // class com/ibm/wsspi/webcontainer/facade/ServletContextFacade
         4: invokevirtual #19                 // Method com/ibm/wsspi/webcontainer/facade/ServletContextFacade.getServletContextName:()Ljava/lang/String;
         7: areturn
    RuntimeVisibleAnnotations:
      0: #13()
        java.lang.invoke.LambdaForm$Hidden
}
```

I’ve also included the GD-GUI screenshot. 
![image](https://user-images.githubusercontent.com/5934310/221391437-7c093213-aee5-4553-9d5c-c97cdd1fa5bf.png)


With this information, we see that the lambda function is just an class file (innerClass ? / proxy class - need to look more into these) of the ServletContextFacade40 (as suspected before). However, as indicated by lines 1 and 4, the code references ServletContextFacade directly.  Since ServletContextFacade40 is within the com.ibm.ws.webcontainer.servlet.4.0.jakarta _bundle_ then the bundle classloader is used. But since the bundle doesn’t contain an import for that class, it fails and we get: 
java.lang.ClassNotFoundException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade cannot be found by com.ibm.ws.webcontainer.servlet.4.0.jakarta_1.0.74.202302171341

As mentioned already, we've verified the classloader of the `lambdaFunction` to be the bundle classloader. 

Another comment  (in issue JDK-8302154) also mentions:
```
A lambda proxy class is the implementation of the lambda/method reference in class C and it's logical part of class C and therefore it has a strong relationship with the class loader. 
```

I don't really see  any harm in adding the import proposed in #23859, and the explanation makes sense above of why an CNFE occurs.  Reflection doesn't generate any code with with the lambda meta factory, but rather invokes the method on the instance.   The more I think about it, the more this lambda inner class makes sense as the lambda meta factory look up were designed for performance, so the lambda is a direct reference to the method.  

- https://wttech.blog/blog/2020/method-handles-and-lambda-metafactory/ 
- https://blogs.oracle.com/javamagazine/post/behind-the-scenes-how-do-lambda-expressions-really-work-in-java
- https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/LambdaMetafactory.html

Maybe an mail to the java-dev mailing list would give us additional details ( and whether the inheritance / multiple bundles was an oversight).
