### ISSUE TITLE
JDBCDriverService; issue with Boolean parameters

### ISSUE THREAD

**Issue by christophs78** [OpenLiberty/open-liberty#23782]
**Describe the bug**  
SQL Server JDBC driver offers parameter encrypt. We define this parameter in server.xml

```xml
<dataSource id="jdbc/XXXds" isolationLevel="TRANSACTION_READ_COMMITTED" jndiName="jdbc/XXXds">
   <jdbcDriver libraryRef="MSJDBCLib" />
   <connectionManager maxPoolSize="10" minPoolSize="2" />
   <properties.microsoft.sqlserver databaseName="A" password="B" portNumber="1234" serverName="C" user="D" encrypt="true" trustServerCertificate="true" />
</dataSource>
```

Since SQL Server JDBC Driver 11.1.0 this fails with:

> com.ibm.ws.jdbc.internal.JDBCDriverService W DSRA8021W: Warning: error setting 'encrypt'=true: java.lang.IllegalArgumentException: argument type mismatch
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
> at java.lang.reflect.Method.invoke(Method.java:508)
> at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:308)
> at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:262)
> at java.security.AccessController.doPrivileged(AccessController.java:747)
> at com.ibm.ws.jdbc.internal.JDBCDriverService.create(JDBCDriverService.java:262)
> at com.ibm.ws.jdbc.internal.JDBCDriverService.createConnectionPoolDataSource(JDBCDriverService.java:563)
> …
> at com.ibm.ws.jndi.internal.WSContext.lookup(WSContext.java:309)
> at com.ibm.ws.jndi.WSContextBase.lookup(WSContextBase.java:61)
> …
> at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:157)

(Full stacktrace will be attached too.)

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.13/wlp-1.0.72.cl221320221205-1900
 - Affected feature(s) [e.g. jndi-1.0]
 - Java Version: OpenJDK 64-Bit Server VM, version 1.8.0_352-b08

**Additional context**  
Microsoft introduced two setEncrypt-methods with https://github.com/microsoft/mssql-jdbc/commit/887cf6f1665b08cdd61df7f3f8c35153ce397011#diff-1e1c2cdd7b88137971bc707b0e5f7b7596a0762eb182447caf36dae07fc54c46. One with a String-parameter and one with a boolean-parameter.

OpenLiberty set´s this parameter via reflections on the datasource. (https://github.com/OpenLiberty/open-liberty/blob/b454b42929fbae0004985a06f9f75fcb5b4a6a89/dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java#L308)

Before this OpenLiberty tries to convert the Parameter to the expected type:
https://github.com/OpenLiberty/open-liberty/blob/b454b42929fbae0004985a06f9f75fcb5b4a6a89/dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java#L1117

JDBCDriverService#coerceType currently only handles conversation to Long, Integer and Short. IMO conversation to Boolean should be added.

**Comment by christophs78** [comment]
[messages.log](https://github.com/OpenLiberty/open-liberty/files/10337085/messages.log) (including full stacktrace)

**Comment by njr-11** [comment]
@christophs78 Thank you for spotting this and for your excellent analysis.  It appears that the Microsoft JDBC driver made a breaking change here, switching a property from boolean to string so that it could accept [additional values](https://github.com/microsoft/mssql-jdbc/blob/8f5f9dacd646385aa08eb9047d56361756cd3a76/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L153).  Liberty's `properties.microsoft.sqlserver` configuration will need a further update to support the additional values.  In the mean time, it should certainly be possible to convert the "true" and "false" values to boolean, which seems like something Liberty ought to be able to do in general regardless.

**Comment by njr-11** [comment]
After investigating this a bit more, I think it's the other way around where the value is coming in as the boolean type per the properties.microsoft.sqlserver config and doesn't convert to String to match the bean PropertyDescriptor for the Microsoft data source class. I attached a pull to add the conversion and linked to another issue for updating to the latest set of properties for the JDBC driver, but in the mean time, it might be possible to work around the issue by using the `<properties>` element rather than `<properties.microsoft.sqlserver>`.

**Comment by christophs78** [comment]
Thanks for digging into this issue in this timely manner! I agree to your conclusion.
