### ISSUE TITLE
InstantOn on OCP

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/open-liberty#23945]
There are a few different issues that affect using InstantOn (in unprivileged mode) on OCP.
 1. The worker nodes on the latest version of OCP available at this moment (`4.12 rc.8`) are running `runc` version `1.1.2`. That `runc` version does not contain a fix that enables running InstantOn in an unprivileged mode on older kernel versions. The `runc` version `1.1.3` version does contain the fix but OCP may not pick up that version until OCP `4.13`. With the updated `runc` version, running InstantOn in an unprivileged mode should be possible. However, it will require mounting the `/proc/sys/kernel/ns_last_pid` file from the host node to the container. That is not a desirable option and will require loosening up the SCC. 
 1. The worker nodes on the latest version of OCP available at this moment (`4.12 rc.8`) are running  an older kernel version `4.18.0-372.40.1.el8_6` that does not support the `clone3` system call. The kernel upgrade is preferable to the first option but will probably require more time to accomplish. 
 1. It is a best practice for workloads on OCP to run with arbitrary user ids. However, CRIU does not support restoring a process to an user id different from the user id used at checkpoint time. OCP can be instructed to use a specific user id (e.g. `1001`) at runtime but that does not quite follow the recommended security guidelines for OCP.

**Comment by vijaysun-omr** [comment]
I wonder why RHCOS based on RHEL9 (and perhaps RHEL9 itself) is not yet supported as OS versions on OCP worker nodes even though it has been many months since RHEL9 was released. If Red Hat has plans to allow RHCOS9 / RHEL9 worker nodes, that may be another way to get a new enough kernel in an OCP environment. Maybe their plans in that area can be clarified if you have some Red Hat contact that can provide some input internally.

**Comment by tjwatson** [comment]
I think we are done here.  InstantOn has been supported with OCP for a while now.
