### ISSUE TITLE
SAML SSO might be using wrong NotOnOrAfter for invalidating the Subject

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#24024]
I'm writing this up based on a slack conversation that I had with Aruna today.

Investigate:

<hr/>

According to the SAML SSO profile http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf

**4.1.4.3 `<Response>` Message Processing Rules**
Verify that the `NotOnOrAfter` attribute in any bearer `<SubjectConfirmationData>` has not passed, subject to allowable clock skew between the providers
If an `<AuthnStatement>` used to establish a security context for the principal contains a `SessionNotOnOrAfter` attribute, the security context SHOULD be discarded once this time is reached, unless the service provider reestablishes the principal's identity by repeating the use of this profile.

The only thing about `<Conditions>` is in:

**4.1.4.2 `<Response`> Usage**

Other conditions (and other `<Audience>` elements) MAY be included as requested by the service provider or at the discretion of the identity provider. (Of course, all such conditions MUST be understood by and accepted by the service provider in order for the assertion to be considered valid.) The identity provider is NOT obligated to honor the requested set of `<Conditions>` in the `<AuthnRequest>`, if any.

<hr/>

There is information about Conditions in the SAML 2.0 token profile:
https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf

**2.5.1 Element <Conditions>**
`NotOnOrAfter` [Optional]
Specifies the time instant at which the assertion has expired.

<hr/>

So technically..."_the assertion has expired_" -vs- "_you cannot use a subject that was established using the assertion_" is a fine line.

According to the SAML token profile spec, the "can't use the subject" part, you should be using `SessionNotOnOrAfter`, right?
 You might go after the `Conditions` if `SessionNotOnOrAfter` doesn't exist although the `Conditions/NotOnOrAfter` technically only applies to consuming the Assertion.  However, I don't think all IdP's give you the option to set `SessionNotOnOrAfter`, so that makes sense.

<hr/>

This is the best explanation that I could find: https://stackoverflow.com/questions/29508906/notonorafter-in-subjectconfirmationdata-and-conditions-and-sessionnotonorafter

> _`SessionNotOnOrAfter` is something completely different that is not directly related to the lifetime of the assertion or the subject. It is a parameter the idp can use to control how long an SP session may be. Please note that this parameter is defined that it SHOULD be handled by an SP according to the SAML2Core spec, but far from all SP implementations do. An example of an implementation that does is as usual Shibboleth, that always will respect the occurrence of this parameter. When using Single Logout, this parameter is more critical, as it synchronizes the timeout of the session on both the SP and the Idp, to ensure that an SP does not issue a logout request for a session no longer known to the Idp._

<hr/>

Here is our current code for calculating the Subject timeout in the SAML SSO scenario:

```
Saml20Token saml20Token = SamlCommonUtil.getSaml20TokenFromSubject(subject, true);
if (saml20Token != null) {
  DateTime expiredDate = new DateTime(saml20Token.getSamlExpires().getTime() - reAuthnCushionMilliseconds);
  bValid = expiredDate.isAfterNow();
  if (bValid) {
    // existing checking even before we implement reAuthnOnAssertionExpire
    // check the SpCookieSessionNotOnOrAfter
    Hashtable<String, ?> hashtable = subjectHelper.getHashtableFromSubject(subject, new String[] { Constants.SP_COOKIE_AND_SESSION_NOT_ON_OR_AFTER });
    if (hashtable == null) {
      bValid = false;
    } else {
       long lSessionNotOnOrAfter = (Long) hashtable.get(Constants.SP_COOKIE_AND_SESSION_NOT_ON_OR_AFTER); // millisecond
        // subtract the reAuthnCushion to make the expiredDateTime earlier
        DateTime sessionNotOnOrAfter = new DateTime(lSessionNotOnOrAfter - reAuthnCushionMilliseconds);
         if (!sessionNotOnOrAfter.isAfterNow()) { // cookie expired
           bValid = false;
          }
    } 
}
```

**Comment by arunavemulapalli** [comment]
I see that we are processing SAML Response/Assertion and validating them per the rules specified in the [spec](http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf) 


-  verify the **NotOnOrAfter** in  \<SubjectConfirmationData>
-  verify the **NotOnOrAfter** in \<Conditions>
-  verify the **SessionNotOnOrAfter** in the \<AuthnStatement>


We take the **NotOnOrAfter** in \<Conditions> as the token expiration (this is per SAML assertion [spec](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf))
We set the **SessionNotOnOrAfter** to the Subject (take it from \<AuthnStatement> if available, otherwise use the config property **sessionNotOnOrAfter**) 

When we are doing the subject validation - 

We check the token expiration (ONLY if the config property **reAuthnOnAssertionExpire** is true and we re-authenticate if the token expires)
We always check the SessionNotOnOrAfter that we set in the Subject (unless the above is false)

This is what we have documented (and it matches with what the runtime does) - 

_Optional: You can configure an SP authentication session and cookie. After SAML assertion is verified and processed, the Liberty SAML SP maintains an authenticated session between the browser and the SP without using an LTPA cookie. The authenticated session timeout is set to SessionNotOnOrAfter in the <saml:AuthnStatement> if presented, or to sessionNotOnOrAfter as configured in the server.xml file, with the default being 120 minutes. The session cookie name is automatically generated, and you can customize the cookie name by using the attribute spCookieName to specify the wanted name.
If you want the Liberty SP to create an LTPA cookie from the SAML assertion and use the LTPA cookie for subsequent authentication requests, you can add the configuration disableLtpaCookie=false. If you want to share the LTPA cookie with other servers, you must add the configuration attribute allowCustomCacheKey="false"._

@teddyjtorres - fyi
