### ISSUE TITLE
Add JAX-RS sub-resource support to the MP Open API reader

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#2417]
swagger-core RC4 supports reading JAX-RS sub-resource. Add this support to Open Liberty.

**Comment by mrglavas** [comment]
Planning to document as a limitation.

**Comment by kdaham** [comment]
Any updates on this?

**Comment by kdaham** [comment]
swagger-core seems to handle sub-resources pretty ok, but deploying the same root/subresource in openliberty does not really show the resources defined in the sub.

**Comment by Azquelt** [comment]
This limitation is no longer present in `mpOpenApi-2.0`.

The return type of a sub-resource locator method is used to generate OpenAPI documentation. This may cause incorrect results if the method actually returns a sub-class of its return type which has different annotations.

No documentation is generated if the method returns a class rather than an object.
