### ISSUE TITLE
Liberty does not process server configuration when config timestamp is earlier than liberty base image build time

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#25442]
Use Open Liberty Open Liberty 23.0.0.6 image
_stg.icr.io/cp/olc/open-liberty:full-java11-openj9-ubi@sha256:1f191a58f4c534212aee94004140040870123b2cd231bb41d7af2f05c7450f56_
or
_stg.icr.io/cp/olc/open-liberty:full-java17-openj9-ubi@sha256:1801f95af0041f8e45bfaca4c4e8dc8bb6a1ac312851c015aaa9bdaa0e757199_

Do InstantOn checkpoint and it failed with messages:

```
[2/2] STEP 10/10: RUN checkpoint.sh $CHECKPOINT
Performing checkpoint --at=beforeappstart
Launching defaultServer (Open Liberty 23.0.0.6/wlp-1.0.78.cl230620230606-1101) on Eclipse OpenJ9 VM, version 11.0.19+7 (en_US)
.............
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: CWWKC0456E: A checkpoint cannot be taken because the following features configured in the server.xml file are not supported for checkpoint: [javaee-8.0, batch-1.0, jms-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, appClientSupport-1.0, mdb-3.2, jca-1.7, jacc-1.5, ejbHome-3.2, wasJmsClient-2.0, jcaInboundSecurity-1.0, ejbRemote-3.2, ejbPersistentTimer-3.2, ejb-3.2, jaxws-2.2, j2eeManagement-1.1, javaMail-1.6]
[AUDIT   ] CWWKF0012I: The server installed the following features: [appClientSupport-1.0, appSecurity-2.0, appSecurity-3.0, batch-1.0, beanValidation-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, el-3.0, j2eeManagement-1.1, jacc-1.5, jaspic-1.1, javaMail-1.6, javaee-8.0, jaxb-2.2, jaxrs-2.1, jaxrsClient-2.1, jaxws-2.2, jca-1.7, jcaInboundSecurity-1.0, jdbc-4.2, jms-2.0, jndi-1.0, jpa-2.2, jpaContainer-2.2, jsf-2.3, jsonb-1.0, jsonp-1.1, jsp-2.3, managedBeans-1.0, mdb-3.2, servlet-4.0, ssl-1.0, wasJmsClient-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, webProfile-8.0, websocket-1.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 5.578 seconds.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (00000054) called the method java.lang.System.exit: 
	at java.base/java.lang.System.exit(System.java:495)
	at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:266)
	at java.base/java.lang.Thread.run(Thread.java:839)
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 7.681 seconds.
Error: building at STEP "RUN checkpoint.sh $CHECKPOINT": while running runtime: exit status 72
!!!--- Failed at beforeappstart checkpoint ---!!!
```

The current workaround is to remove workarea `rm -rf /output/workarea` in the Containerfile

**Comment by tjwatson** [comment]
The root cause of this issue is the copy of the config from another application image like this:

```
COPY --from=application --chown=1001:0 /config /config
```

That other application image has config that is dated earlier than the date the Open Liberty container images were built.  During the Open Liberty container image builds there are some generated XML files that get placed in:

```
config/configDropins/defaults/open-default-port.xml
config/configDropins/defaults/keystore.xml
```
These files will get a timestamp at the time the Liberty container images are built. Then these files are processed when the Liberty container image builds generate the caches (e.g. shared classes cache and the liberty workarea).  Liberty config then records last read timestamp according to the latest timestamp of all the config files.  This timestamp is used to quickly determine if Liberty config should reprocess config on restart.

The issue here is all the config files the application container is copying in are less than the timestamp of the generated XML files above from the liberty container image builds.  So when liberty is started up with the application configuration it runs into this code:

https://github.com/OpenLiberty/open-liberty/blob/0ae47cbb7674ccf56f41e37a9184f697b0e8d64c/dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java#L180-L191

That always returns the highest timestamp which is the timestamp from the generated XML so Liberty config thinks nothing has changed and never processes the application's configured `server.xml` file.

**Comment by tjwatson** [comment]
A workaround is to touch the `/config/server.xml` file before running the `configure.sh` script:

```
RUN bash -c "echo $CHECKPOINT" \
  && touch /config/server.xml

RUN configure.sh
```

**Comment by tam512** [comment]
We just tried to rebuild the non-checkpoint app image so it has newer timestamp and rerun check point but it still fails when not having the workaround (_touch /config/server.xml_)

The reason to  reuse the /config from an existing application image which does not have instanton checkpoint is because it has the test applications, server.xml, options.jvm, db jar files 
so we have these in the Containerfile

```
FROM $HYCSVT/ebuy/ebuy-ee10:wl-jdk11-java17 as application
.........
COPY --from=application --chown=1001:0 /config /config
```

**Comment by tam512** [comment]
verified in Liberty 23.0.0.10 images
