### ISSUE TITLE
Back Channel Logout - logout endpoint cleans up wrong client

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#25526]
If I login using a client from provider: bcl_mainPath_confClient, and then invoke https://localhost:8920/oidc/endpoint/OidcConfigSample_http_httpsRequired_true/logout
(notice it’s a different provider), BUT, I used the webclient from my original request.
I get a message about a successful logout and some of the cookies get cleaned up.  The access_token is still valid, but, some things are getting cleaned up when the logout should just fail.

[wrongProvider.zip](https://github.com/OpenLiberty/open-liberty/files/11805206/wrongProvider.zip)

**Comment by ayoho** [comment]
I believe this is caused by my changes in https://github.com/OpenLiberty/open-liberty/pull/24811 when I was trying to fix the issuer checking. Since the OP doesn’t have an `issuerIdentifier` attribute configured, the issuer check passes. That’s why the logout proceeds even though this provider wasn’t the one that issued the token.

I’d probably put the logic back in that I took out to base the issuer check off the request URL if `issuerIdentifier` isn't configured, but make the check smarter to allow for either "providers" or "endpoint" in the URL.

**Comment by jimmy1wu** [comment]
fixed in https://github.com/OpenLiberty/open-liberty/pull/26296

@c00crane please verify when you can.
