### ISSUE TITLE
mpOpenTracing-1.0 @Traced annotation doesn't work

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/open-liberty#2566]
A JAXRS endpoint (or vanilla class or method which is part of a web service flow) annotated with `@Traced` should control whether or not an OpenTracing span is created. Tracing with `*=info:com.ibm.ws.opentracing*=all:com.ibm.ws.microprofile.opentracing*=all` should produce:

    [07/03/18 16:29:14:560 EST] 00000039 id=686b287e com.ibm.ws.opentracing.cdi.TracedInterceptor                 > execute Entry

**Comment by kwsutter** [comment]
@kgibm Not sure I understand the impact to customers.  The title sounds very ominous, but I can't believe that @Traced is broke completely.  Otherwise, how could we pass basic FATs?  So, can you explain under what conditions @Traced works and under what conditions @Traced doesn't work?  Just trying to figure out how critical this Issue is with regards to 18.0.0.1 and whether an iFix is needed or not...

**Comment by kwsutter** [comment]
Okay.  I just spoke with @kgibm and we do need an ifix for this situation for 18.0.0.1.  This is being worked as we speak and should be available shortly after 18.0.0.1 becomes available.

**Comment by gmarcy** [comment]
fixes delivered to 18.0.0.1_RC and integration
