### ISSUE TITLE
Liberty 23.0.0.8 - 5% Performance Throughput Regression on JaxRS PingClientAsync2Sync_2.1 scenario

### ISSUE THREAD

**Issue by eramos2** [OpenLiberty/open-liberty#26026]
**Describe the bug**  
There is a 5% throughput regression in the JaxRS PingClientAsync2Sync_2.1 scenario, seen between Liberty builds `230720230710-1201` and `230820230807-0401` (23.0.0.8 GA).

There seems to be a ~6% difference on 23008 profle under the `finalzeMessage` call when compared to 23007 `J:org/apache/cxf/jaxrs/client/WebClient.finalizeMessage(Ljava/lang/String;Ljavax/ws/rs/core/MultivaluedMap;Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/reflect/Type;[Ljava/lang/annotation/Annotation;Ljava/lang/Class;Ljava/lang/reflect/Type;Lorg/apache/cxf/message/Exchange;Ljava/util/Map;)Lorg/apache/cxf/message/Message;`

Steps to Reproduce
Measure throughput (req/sec) in 230720230710-1201  build
Measure throughput (req/sec) in 230820230807-0401 (23.0.0.8 GA) build
Compare the Difference in throughput between builds

**Diagnostic information:**  
OpenLiberty Version:
`23.0.0.8 (wlp-1.0.80.cl230820230807-0401)`
Affected feature(s):
`jaxrs-2.1`
Java Version:
`8.0.8.6 - pxa6480sr8fp6-20230601_01(SR8 FP6)`

**Comment by jhanders34** [comment]
PR #25447 updated to a new version of CXF.  https://github.com/apache/cxf/pull/935 introduced a Rfc3986UriValidator class that uses Regular Expression in order to validate a URI.  Using regular expressions when you already have the Uri object just to look at the host name is way too much overhead.  Will create a PR to reduce that overhead in an overlay of the changes that were done in that PR.
