### ISSUE TITLE
Restore is not working if using persistent storage with mountPath /output

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#26258]
When using [Persistence](https://github.com/application-stacks/runtime-component-operator/blob/main/doc/user-guide-v1beta2.adoc#persistence) in OpenLibertyApplication yaml with the following configurations (I use [NFS](https://docs.openshift.com/container-platform/4.13/storage/persistent_storage/persistent-storage-nfs.html) in this case) , InstantOn restore is not working. 
```
spec:
.......
  statefulSet:
    storage:
      size: 5Gi
      mountPath: "/output"
```
There is no error, but I do not see  /logs/checkpoint/restore.log file
```
% ls -l checkpoint 
total 1160
-rw-r--r--  1 tam  staff  586557 Sep 12 16:27 checkpoint.log
-rw-r--r--  1 tam  staff      51 Sep 12 16:27 stats-dump
```
There is no `CWWKC0452I: The Liberty server process resumed operation from a checkpoint....` in messages.log  and server start time indicate there is no instanton (_The defaultServer server started in 8.359 seconds_)

The /output directory also contains `resources` and `workarea` directories. Maybe persisting those impacts/interferes with InstantOn

**Comment by vijaysun-omr** [comment]
I assume this is a problem seen on X86 and Power, i.e. it is not platform dependent ?

**Comment by tjwatson** [comment]
The current design of InstantOn will not allow output to be mounted outside of the container.  There are a few reasons for this:

1. The output location (workarea/checkpoint/image) contains the checkpoint process image that is necessary to be able to restore the process.
2. The output location (workarea) contains various liberty caches that are associated with the checkpointed process.

With that in mind it is not possible for us to allow you to mount something external for the output location because that would override the required content of the stored output location in the image to allow us to restore.

Closing this as a wontfix
