### ISSUE TITLE
Review asynchronous execution in Reactive Streams 3.0

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#26352]
Was: ~Replace ExecutorService in ReactiveStreams30 with ManagedExecutorService~

https://github.com/OpenLiberty/open-liberty/blob/51c0e42e906390c31db6bd58a8579010bf7dfc79/dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/LibertyReactiveStreamsEngineImpl.java#L56 should accept a ManagedExecutorService instead of a standard ExecutorService

**Comment by Azquelt** [comment]
If doing this, we should also remove the use of `WSContextService` - `ManagedExecutorService` should do the job of propagating the context for us.

**Comment by Azquelt** [comment]
Had a discussion with the concurrency folks who pointed out some issues with the way we were doing this:

- Using ManagedExecutorService requires a dependency on the concurrent-x.x feature, which we're not sure should be required here
- The user can create and configure any number of ManagedExecutorServices, we need to know which one to use
- If we're using ManagedExecutorService, we should allow the user to configure which ManagedExecutorService we use. 
  - While using the default one is fine in most cases, we don't want to back users into a corner where they want to configure the service one way for one feature and another way for another feature but can't.

For now I've reverted back to using `WSContextService`, but we need to decide whether async is really required here, and if it is we need to add configuration to allow the user to pick the context service they want to use.

**Comment by Azquelt** [comment]
Looking over the Reactive Streams spec, it's not clear to me that we should be doing anything async in our reactive streams implementation.

In general, reactive streams don't care what thread they're running on and therefore shouldn't do blocking operations.

For example, with a stream like this:
```java
        CompletionStage<List<Integer>> result = ReactiveStreams.of(1, 2, 3, 4, 5)
                        .collect(Collectors.toList())
                        .run()
```
The whole stream will run immediately when `run()` is called because `ReactiveStreams.of()` emits values immediately in response to demand being signalled and there are no asynchronous stages.

However, a stream like this is different:
```java
        CompletionStage<List<Integer>> result = ReactiveStreams.of(1, 2, 3, 4, 5)
                        .flatMapCompletionStage(i -> CompletableFuture.supplyAsync(() -> computeSomethingComplex(i), managedExecutor))
                        .collect(Collectors.toList())
                        .run()
```

When `run()` is called, each stage subscribes to its input, but when the first number is emitted, the flatMapCompletionStage() will submit a task to the `managedExecutor` and then return. The later stages will then run as part of this submitted task.

Imagine a different scenario, where we have a `Publisher` publishing integers received from a Kafka topic:

```java
        CompletionStage<List<Integer>> result = kafkaPubisher
                        .limit(5)
                        .collect(Collectors.toList())
                        .run()
```

Here, when `run()` is called, each stage subscribes to its input stage. The Kafka publisher may emit items immediately if it's already received some from the kafka broker, but if there aren't any, it should return and then emit items on another thread when they do arrive.

A second question is if we need any dependency on the `concurrent-x.x` feature. If we don't do any async ourselves, then obviously concurrent can be removed as a dependency but even if it remains, it probably shouldn't be a hard dependency.

**Comment by Azquelt** [comment]
Currently, we are doing the initial subscription for a new reactive stream in an async task. I think this is only useful when the input to a stream is a fixed list and the stream includes blocking or long-running steps.

**Comment by Azquelt** [comment]
In addition, running anything asynchronously prevents access to CDI request scoped beans, so maybe it's preferable to only do things asynchronously if the user requests it.

The only way I can see in the RSO API to do something asynchronously is by using `.flatMapCompletionStage()` which calls a function which returns a completion stage. This can be used to start an asynchronous task using a `ManagedExecutorService` (directly in EE10 or via CompletableFuture.supplyAsync in earlier versions).

Having the user call `ManagedExecutorService` directly both means that it's explicit and obvious that something is going to run asynchronously and that the user can provide a specific `ManagedExecutorService` if they need to.

**Comment by Azquelt** [comment]
Fix was reverted - likely just needs `concurrent` feature added to TCK FAT.

Personal build should run with an appropriate set of FAT projects in full mode.
