### ISSUE TITLE
Servlet 6.1: Clarify the behaviour of HttpServletMapping.getMatchValue().

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26489]
`https://github.com/jakartaee/servlet/issues/316`

**Comment by pmd1nh** [comment]
`https://github.com/jakartaee/servlet/pull/497/files`

Return the portion of the URI path that caused this request to be matched. If the {@link #getMappingMatch} value is
 {@code CONTEXT_ROOT} or {@code DEFAULT}, this method must return the empty string. If the {@link #getMappingMatch}
 value is {@code EXACT}, this method must return the portion of the path that matched the servlet, omitting any
 leading slash. If the {@link #getMappingMatch} value is {@code EXTENSION} or {@code PATH}, this method must return
 the value that matched the '*' `excluding any leading '/'`. See the class javadoc for examples.

`public String getMatchValue();`

**Comment by pmd1nh** [comment]
<p>
  Following are some illustrative examples for various combinations of mappings. Consider the following Servlet
  declaration:
  </p>
 
 <pre>  <code>
  &lt;servlet&gt;
      &lt;servlet-name&gt;MyServlet&lt;/servlet-name&gt;
      &lt;servlet-class&gt;MyServlet&lt;/servlet-class&gt;
  &lt;/servlet&gt;
  &lt;servlet-mapping&gt;
      &lt;servlet-name&gt;MyServlet&lt;/servlet-name&gt;
      &lt;url-pattern&gt;/MyServlet&lt;/url-pattern&gt;
      &lt;url-pattern&gt;""&lt;/url-pattern&gt;
      &lt;url-pattern&gt;*.extension&lt;/url-pattern&gt;
      &lt;url-pattern&gt;/path/*&lt;/url-pattern&gt;
  &lt;/servlet-mapping&gt;
  </code>
  </pre>
 
  <p>
  The expected values of the properties for various incoming URI path values are as shown in this table. The
  {@code servletName} column is omitted as its value is always {@code MyServlet}.
  </p>
  
  
URI Path (in quotes) | matchValue | pattern | mappingMatch
-- | -- | -- | --
"" | "" | "" | CONTEXT_ROOT
"/index.html" | "" | / | DEFAULT
"MyServlet/index.html" | "" | / | DEFAULT
"/MyServlet" | MyServlet | /MyServlet | EXACT
"MyServlet/foo" | "" | / | DEFAULT
"/foo.extension" | foo | *.extension | EXTENSION
"/bar/foo.extension" | bar/foo | *.extension | EXTENSION
"/path/foo" | foo | /path/* | PATH
"/path/foo/bar" | foo/bar | /path/* | PATH

**Comment by pmd1nh** [comment]
Need to update the PATH mappingMatch for the last example.

`"/path/foo/bar" 	foo/bar 	/path/* 	PATH`

Currently, the matchValue is just `bar` . It needs to be `foo/bar`

**Comment by pmd1nh** [comment]
current example (up to Servlet 6.0)

<div class="block"><p>
 The expected values of the properties for various incoming URI path values are as shown in this table. The
 <code>servletName</code> column is omitted as its value is always <code>MyServlet</code>.
 </p>
 
 
URI Path (in quotes) | matchValue | pattern | mappingMatch
-- | -- | -- | --
"" | "" | "" | CONTEXT_ROOT
"/index.html" | "" | / | DEFAULT
"/MyServlet" | MyServlet | /MyServlet | EXACT
"/foo.extension" | foo | *.extension | EXTENSION
"/path/foo" | foo | /path/* | PATH

</div>
<dl>
<dt><span class="simpleTagLabel">Since:</span></dt>
<dd>Servlet 4.0</dd>
</dl>
