### ISSUE TITLE
Servlet 6.1: Remove sensitive HTTP headers from responses to TRACE requests.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26498]
`https://github.com/jakartaee/servlet/issues/469`

**Comment by pmd1nh** [comment]
By default, Liberty rejects any TRACE request which served by the default doTrace() with
`Error 403: Illegal request. Default implementation of TRACE not allowed.`

In order to test the doTrace() removal of sensitive headers, a WebContainer property is needed:

`<webContainer com.ibm.ws.webcontainer.DefaultTraceRequestBehavior="true"/>`
