### ISSUE TITLE
Implement 3 attempts for getInputValues to avoid StaleElementReferenceException

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#26836]
Implement 3 attempts for getInputValues to avoid StaleElementReferenceException -- See Closed Liberty PR 30384

_Originally posted by @volosied in https://github.com/OpenLiberty/open-liberty/issues/26234#issuecomment-1795085729_

**Comment by tssmith04** [comment]
This fix was already implemented into Selenium util at some point. When we consolidated all of the Selenium util files into one internal package (#28687) all of the buckets are accounted for with the fix. So I'm closing this issue since the fix has already been added everywhere necessary (io.openliberty.faces.fat.selenium.util.internal).
