### ISSUE TITLE
JTA: Transactional-Interceptor wraps RuntimeExceptions

### ISSUE THREAD

**Issue by peterzberg** [OpenLiberty/open-liberty#26937]
**Describe the bug**  
The  @Transactional-Interceptor wrapps the runtime exception into an jakarta.transaction.TransactionalException

In my opinion this behaviour got introduced with https://github.com/OpenLiberty/open-liberty/commit/d80a04896fcf586db04c65f1bbc50a61514309dd#diff-77d43d7ddfdc7a9365b3a1dea77c78ca603a4cd8bfffa68edbecfaa922c72c55

This may influence other featues like restfulWS (see steps to reproduce).

**Steps to Reproduce**  
```
@RequestScoped
@Path("/sample")
public class SampleSource {

    @GET
    @Transactional
    public String sample(){
        throw new WebApplicationException("not in my house", Response.Status.BAD_REQUEST);
    }

}
```
Server returns status code 500

**Expected behavior**  
In this case I would expect the runtime exception being passed to jaxws and a status code of 400 presented to the caller

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.10
- Affected feature(s): JTA
- Java Version: 17.0.8+7

**Additional context**

**Comment by jonhawkes** [comment]
Accepted. Seems I was a bit over zealous in my exception wrapping when addressing [issue 26171](https://github.com/OpenLiberty/open-liberty/issues/26171)

**Comment by rosczja** [comment]
Hello @jonhawkes , thanks for trying to fix this, but looking at the source I think it still is not working correctly for RuntimeException. 

Your solution first checks if the thrown exception is declared on the method and afterwards you check if it is a RuntimeException.

I think this needs to be the other way around, because usually you do not declare RuntimeException on the method, which I would have to do now to make it work with your solution if I am not mistaken.

Please be so kind to recheck. Thanks.
