### ISSUE TITLE
mpMetrics-5.0 Feature Returns Response in ISO-8859-1 Instead of UTF-8 when Accessing /metrics Endpoint

### ISSUE THREAD

**Issue by takakiyo** [OpenLiberty/open-liberty#27093]
**Describe the bug**  
When enabling the `mpMetrics-5.0` feature in Open Liberty to support MicroProfile Metrics 5.0, there is an issue with the character encoding of the response returned from the `/metrics` endpoint. Instead of responding with the expected UTF-8 encoding, the server erroneously returns the response in ISO-8859-1 encoding. As a consequence of this encoding issue, non-ASCII characters included in the `# HELP` section of the response are becoming garbled. `mpMetrics-4.0` and `mpMetrics-3.0` respond with UTF-8 correctly.

```
< HTTP/2 200 
< access-control-allow-origin: *
< access-control-allow-credentials: true
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
< access-control-max-age: 1209600
< access-control-allow-headers: origin, content-type, accept, authorization
< content-type: text/plain;charset=ISO-8859-1
< content-language: ja-JP
< set-cookie: LtpaToken2=XXXX; Path=/; Secure; HttpOnly
< set-cookie: JSESSIONID=XXXX; Path=/; Secure; HttpOnly
< date: Tue, 05 Dec 2023 03:15:26 GMT
< expires: Thu, 01 Dec 1994 16:00:00 GMT
< cache-control: no-cache="set-cookie, set-cookie2"
< 
```

**Steps to Reproduce**  
``` xml
<featureManager>
    <feature>mpMetrics-5.0</feature>
    <feature>transportSecurity-1.0</feature>
</featureManager>
```

**Expected behavior**  
`mpMetrics-4.0` feature responds with `text/plain; charset=utf-8` content type.

```
< HTTP/2 200 
< content-type: text/plain; charset=utf-8
< content-language: ja-JP
< set-cookie: LtpaToken2=XXXX; Path=/; Secure; HttpOnly
< set-cookie: JSESSIONID=XXXX; Path=/; Secure; HttpOnly
< date: Tue, 05 Dec 2023 03:04:15 GMT
< expires: Thu, 01 Dec 1994 16:00:00 GMT
< cache-control: no-cache="set-cookie, set-cookie2"
< 
```

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.11/wlp-1.0.83.cl231120231030-1102
 - Affected feature(s): mpMetrics-5.0
 - Java Version: Eclipse OpenJ9 VM バージョン 17.0.8.1+1 (ja_JP)

**Additional context**  
none

**Comment by una-tapa** [comment]
While @takakiyo was translating the OpenLiberty 23.0.0.11 article to contribute to the Japanese blog, he was also trying the mpMetrics function. He noticed the difference in the output between `mpMetrics-5.0` (garbled) and `mpMetrics-4.0, mpMetrics-3.0` (readable).  

He decided to keep the mpMetrics-5.0 output in English in the blog.  Once this issue is resolved, I plan to ask @takakiyo to help get us the output so we can update the blog with the localized output. This issue is going to affect other language. 
 
The blog is in the process of being published :  https://github.com/OpenLiberty/blogs/pull/3461

**Comment by una-tapa** [comment]
This is just FYI - @dmuelle.  The current blog content is correct. We would like your help updating the blog when `mpMetrics-5.0` output is localized.  I am planning to submit a new PR for your review.
