### ISSUE TITLE
Catch Kafka errors in Reactive Messaging liberty-kafka tests

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#27120]
Certain errors within kafka appear in the logs as Errors which are not detected by our `server.stopServer();` meaning we might be missing kafka errors in our tests.

As an example https://github.com/OpenLiberty/open-liberty/blob/50bb060817d53abb31167796a398df2935e4554e/dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/mtls/mutliple/multipleapp/KafkaMtlsMultipleAppsTest.java

If the Producers `client.id` is not set on one of the `outgoing` channels, then we get kafka errors relating to conflicting client.ids, but these are not reported in the test report and as such the test currently has a check in the logs after the test run to see if any have occurred so that we can fail the test.

We need to either add a way for stopServer() to catch these types of events, or do a custom process that can be reused in all the kafka tests that will be able to capture all existing issues and the kafka errors and report those in the test report.

**Comment by benjamin-confino** [comment]
I examined this and while we could easily modify LibertyServer to check for Kafka errors on shutdown, that would mean every FAT test that stops a server will go regexing through logs. The performance cost does not bear considering. 

There are other options, like letting you call a method on LibertyServer to input the regex for Kafka errors rather than hardcoding it in. But since the current solution is one line, would that be any better?
