### ISSUE TITLE
MP Fault Tolerance: Use RunWith(FATRunner) in faulttolerance.cdi_fat and cdi_fat_metrics suites

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2737]
Need to make sure to use the FATRunner and "standard" FAT framework where possible to ensure that functions such as RepeatTests work propertly and that tests marked as FULL mode only run in full mode

**Comment by hutchig** [comment]
So far all I have found in FT related fat test buckets is: 
@RunWith(Suite.class) in the suite folders and
@RunWith(FATRunner.class) in the test folders
which I think is what is correct.

However I am now looking for counter examples where one or other of these is missing.

**Comment by hutchig** [comment]
So the issue is - there are a numer of non TCK tests in: 
/libertyGit/open-liberty/dev/com.ibm.ws.microprofile.config_fat
/libertyGit/open-liberty/dev/com.ibm.ws.config_fat
$ find . -name "*Test.java"  | xargs cat | grep RunWith
/libertyGit/open-liberty/dev/com.ibm.ws.config_fat
$ find . -name "*Test.java"  
./test-bundles/test.config.extensions.schema.generator/src/test/config/extensions/schema/generator/GeneratorTest.java
./test-bundles/test.config.extensions/src/test/config/extensions/ExtensionsTest.java
./fat/src/test/server/config/MetatypeProviderTest.java
./fat/src/test/server/config/DropinsTest.java
./fat/src/test/server/config/ProductExtensionsTest.java
./fat/src/test/server/config/ConfigValidatorTest.java
./fat/src/test/server/config/FeaturelistGeneratorMBeanTest.java
./fat/src/test/server/config/WSConfigurationHelperTest.java
./fat/src/test/server/config/SchemaGeneratorMBeanTest.java
./fat/src/test/server/config/ConfigExtensionsTest.java
./fat/src/test/server/config/ServerXMLConfigurationMBeanTest.java
./fat/src/test/server/config/ServerConfigTest.java
./fat/src/test/server/config/ChildAliasTest.java

**Comment by hutchig** [comment]
Also
/libertyGit/open-liberty/dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics
./fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/CDIFallbackTest.java
