### ISSUE TITLE
TCK test results in the TCK Report have null instead of timestamp for MP Reactive Messaging 3.0

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/open-liberty#27438]
After running `io.openliberty.microprofile.reactive.messaging30.internal_fat_tck` the generated test suite results should contain a timestamp at the end like so:
```
Test suite: org.eclipse.microprofile.reactive.messaging.tck.SimpleIncomingTest 2024-01-24T13:17:34 GMT
```

but instead it is:
```
Test suite: org.eclipse.microprofile.reactive.messaging.tck.SimpleIncomingTest null
```

The timestamp is added to the test suite results in [/fattest.simplicity/src/componenttest/topology/utils/tck/TestSuiteXmlParser.java](https://github.com/OpenLiberty/open-liberty/blob/2e2869d7e0f56072e84b356a9be9f8adb5fcd1c4/dev/fattest.simplicity/src/componenttest/topology/utils/tck/TestSuiteXmlParser.java#L4) and then those are passed to [/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java](https://github.com/OpenLiberty/open-liberty/blob/2e2869d7e0f56072e84b356a9be9f8adb5fcd1c4/dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java#L85)

**Comment by abutch3r** [comment]
The adoc generation is not at fault for this - The issue is that the Junit XML results files except the overall parent for some reason do not have a `timestamp` attribute. this leads to the timestamp value being `null` we would need to understand why we only have one results file with the timestamp and the rest do not have it injected within the files.

I have tried removing the repeat rule to see if that was the case, given RM30 is a bit different to other TCKs as it is not tied to one MP version - it can be used with any MP version that supports the `jakarta.*` namesapce. However, the removal did not change the output. so we still need to determine why the individual tests report as they do

**Comment by ryan-storey** [comment]
This seems to be caused by using junit rather than using testng/issue within our codebase. All but 5 or so of our TCKs use testng however all of the junit ones that I have tested give the same output, whereas the buckets that use testng behave as we would expect. 
See the jakarta json-b and rest 3.1 TCKs which also use JUnit - they also print null

**Comment by ryan-storey** [comment]
https://github.com/junit-team/junit5/issues/3078
Looking at various issues on junit5 repo, it is possible to print timestamps, how we would enable this, I'm not sure (note: they are run with gradle whereas we use maven)
