### ISSUE TITLE
io.smallrye.graphql.entry.http.GraphQLServerWebSocket java.lang.NoClassDefFoundError: org.jboss.logging.Logger

### ISSUE THREAD

**Issue by urbandroid** [OpenLiberty/open-liberty#27534]
**Describe the bug**  
I'm trying to GraphQL server to run on OpenLiberty and it complains at start that :
https://github.com/smallrye/smallrye-graphql/issues/2018
I initially opened issue at the smallrye and got feedback from them to open here.  I have managed to
make it work with payara, wildfly and openliberty but open liberty fails if below dependency not added.

	```
	<dependency>
			<groupId>org.jboss.logging</groupId>
			<artifactId>jboss-logging</artifactId>
			<version>3.5.3.Final</version>
		</dependency> 
```

> `[WARNING ] CWNEN0047W: Resource annotations on the fields of the io.smallrye.graphql.entry.http.GraphQLServerWebSocket class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: org.jboss.logging.Logger
> [AUDIT ] CWWKT0016I: Web application available (default_host): http://ac6a5b861e67:9080/deneme2-web/
> [ERROR ] SRVE0283E: Exception caught while initializing context: java.lang.NoClassDefFoundError: org.jboss.logging.Logger
> at io.smallrye.graphql.entry.http.SmallRyeGraphQLServletLogging.(SmallRyeGraphQLServletLogging.java:17)
> at io.smallrye.graphql.entry.http.IndexInitializer.createIndex(IndexInitializer.java:55)
> at io.smallrye.graphql.entry.http.StartupListener.contextInitialized(StartupListener.java:55)
> at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2465)
> at [internal classes]
> 
> [ERROR ] SRVE0265E: Error occured while notifying listeners of web application start: java.lang.NoClassDefFoundError: org.jboss.logging.Logger
> at io.smallrye.graphql.entry.http.SmallRyeGraphQLServletLogging.(SmallRyeGraphQLServletLogging.java:17)
> at io.smallrye.graphql.entry.http.IndexInitializer.createIndex(IndexInitializer.java:55)
> at io.smallrye.graphql.entry.http.StartupListener.contextInitialized(StartupListener.java:55)
> at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2465)
> at [internal classes]
> 
> [AUDIT ] CWWKZ0012I: The application deneme2-ear was not started.
> [AUDIT ] CWWKT0017I: Web application removed (default_host): http://ac6a5b861e67:9080/deneme2-web/
> [ERROR ] SRVE0285E: Exception caught while destroying context: java.lang.NoClassDefFoundError: io.smallrye.graphql.entry.http.SmallRyeGraphQLServletLogging (initialization failure)
> at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:156)
> at io.smallrye.graphql.entry.http.StartupListener.contextDestroyed(StartupListener.java:69)
> at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextDestroyed(WebApp.java:2697)
> at [internal classes]
> 

**Steps to Reproduce**  
https://github.com/urbandroid/graphql-jakarta/commit/28d97e3ae00727fed386a0020c02a3390f26995b run this commit with 
1. mvn clean install 
2. docker build -f payara/Dockerfile -t urbandroid/deneme2 .
3. docker run -it --name payara -p 8080:8080 urbandroid/deneme2

**Expected behavior**  
Deployment should succeed just like it does with payara and wildfly. 

**Diagnostic information:**  
 - openliberty/open-liberty:full-java11-openj9-ubi docker image
 - Affected feature(s) : GraphQL
 - Java Version: openjdk version "11.0.21" 2023-10-17
IBM Semeru Runtime Open Edition 11.0.21.0 (build 11.0.21+9)
Eclipse OpenJ9 VM 11.0.21.0 (build openj9-0.41.0, JRE 11 Linux amd64-64-Bit Compressed References 20231122_912 (JIT enabled, AOT enabled)
OpenJ9   - 461bf3c70
OMR      - 5eee6ad9d
JCL      - 0fd7a05277 based on jdk-11.0.21+9)

 - server.xml configuration:

> <?xml version="1.0" encoding="UTF-8"?>
> <server description="new server">
> 
>     
>     <featureManager>
>         <feature>jakartaee-10.0</feature>
>     </featureManager>
> 
>     
>     
>     
>     
>     
>     
>     <basicRegistry id="basic" realm="BasicRealm"> 
>          
>     </basicRegistry>
>     
> 
>                   
>     
>     <applicationManager autoExpand="true"/>
> 
> </server>

`When org.jboss.logging and microprofile config added to dependency it works but i shouldn't be required according to smallrye team since it is a provided dependency and it works without this two dependency with payara and wildfly so i think it is a bug.`

**Comment by NottyCode** [comment]
Looking at the smallrye bug report I think they are saying that if you used the Liberty mpGraphQL-2.0 feature you wouldn't need to use this dependency, and you are right you wouldn't. We have some guides for how to use it [here](https://openliberty.io/guides/?search=graphql), and the documentation for our mpGraphQL-2.0 feature is [here](https://openliberty.io/docs/latest/reference/feature/mpGraphQL-2.0.html).

In your case though it looks like you have packaged the smallrye graphql in your application and are not using the `mpGraphQL-2.0` feature. If you choose to go this route then Liberty will treat the smallrye graphql as application code at which point you are required to package the dependencies of smallrye graphql as a part of your application. The `org.jboss.logging.Logger` class is not part of the Jakarta EE API you have configured, and runtimes are not obliged to package it for your application use. I would guess that WildFly and Payara do package the code, and package it in a way your application has visibility to it which is why it works there. Liberty does not package it for application use, we choose not to do this because doing so would limit your ability to independently manage the open dependencies in your application from Liberty.

I see in the smallrye bug report that the smallrye team don't want to change this dependency from provided scope to compile scope, that is really a question for them, but it seems unreasonable and incorrect to expect that all runtimes provides this dependency. I suspect the same issue will arise when using Tomcat.

**Comment by urbandroid** [comment]
Thank you @NottyCode my initial guess was the same hence i opened bug there first.

**Comment by NottyCode** [comment]
Based on the conversation over in the Smallrye issue and based on the thread here I'm going to close this issue since it does appear everyone here agrees this is a bug in Smallrye.
