### ISSUE TITLE
RolesAllowed() not working with Jakarta Rest after defining special-subject ALL_AUTHENTICATED_USERS

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#27906]
**Describe the bug**  
I want to annotate some methods with @RolesAllowed("Auth-User") where all authenticated users are permitted

**Steps to Reproduce**  
Create a Dummy HttpAuthenticationMechanism
```java
@ApplicationScoped
@AutoApplySession
public class SampleHAM implements HttpAuthenticationMechanism {

	@Override
	public AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response,
			HttpMessageContext httpMessageContext) throws AuthenticationException {
		if ("true".equals(request.getParameter("auth"))) {
			Set<String> groups = new HashSet<>();
			groups.add("HAM-User");
			return httpMessageContext.notifyContainerAboutLogin("DummyUser", groups);
		}
		return AuthenticationStatus.NOT_DONE;
	}
}
```
The sample Rest-Resource
```java
@Path("resource")
public class TestResource {

	@GET
	public Response getData() {
		return Response.ok("hello world unauthenticated").build();
	}

	@Path("secure-1")
	@GET
	@RolesAllowed("Ham-User")
	public Response getDataSecure1() {
		return Response.ok("hello world Ham-User").build();
	}

	@Path("secure-2")
	@GET
	@RolesAllowed("Auth-User")
	public Response getDataSecure2() {
		return Response.ok("hello world Auth-User").build();
	}
}
```
You can execute now following requests
```
http://localhost:9080/dev/rest/resource -> Valid Rewsponse
http://localhost:9080/dev/rest/resource?auth=true -> A Login will be performed. The User gets following Role "HAM-User"
http://localhost:9080/dev/rest/resource/secure-1 -> HTTP 403 !
http://localhost:9080/dev/rest/resource/secure-2 -> Valid Response
```
If i remove the security-role definition from server.xml the @RolesAllowed("Ham-User") works fine.

**Expected behavior**  
I want to annotate methods for specific Role (#getDataSecure1()) and also a other method (#getDataSecure2) for all authenticated users.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.2
 - Java Version: 21.0.2+13-LTS
 - server.xml configuration
 ```xml
<server description="Sample Liberty server">
	<featureManager>
		<feature>webProfile-10.0</feature>
	</featureManager>
	<webApplication id="testweb" location="testweb.war">
		<application-bnd>
			<security-role name="Auth-User">
				<special-subject type="ALL_AUTHENTICATED_USERS" />
			</security-role>
		</application-bnd>
	</webApplication>
</server>
```

**Additional context**  
I see following exception on first call to the unauthenticated rest resource and also when a login will be performed with SampleHAM
```
CWWKS3005E: Es ist eine Konfigurationsausnahme eingetreten. Es ist kein UserRegistry-Implementierungsservice verfügbar. Stellen Sie sicher, dass Sie eine Benutzerregistry konfiguriert haben.
```

**Comment by Zech-Hein** [comment]
Hi @c-koell,

I believe using @RolesAllowed("**") instead of @RolesAllowed("Auth-User") will fix your problem.  

You can then remove the following entry
```
   	<application-bnd>
   		<security-role name="Auth-User">
   			<special-subject type="ALL_AUTHENTICATED_USERS" />
   		</security-role>
   	</application-bnd>
```

You can find the "**" role mentioned in this doc: https://openliberty.io/docs/latest/authorization.html
It is used in annotations to apply to ALL_AUTHENTICATED_USERS

**Comment by c-koell** [comment]
@Zech-Hein i have tried "**" but it does not work.
Here is the [sample] (https://github.com/OpenLiberty/open-liberty/files/14598487/27906.zip) that you can try it easy by yourself

**Comment by ayoho** [comment]
Related issue: https://github.com/OpenLiberty/open-liberty/issues/26539

**Comment by c-koell** [comment]
@Zech-Hein is my usecase not possible at the moment ?

**Comment by c-koell** [comment]
@ayoho is my usecase at the moment not possible ?

**Comment by Zech-Hein** [comment]
@c-koell sorry for the delay

Based on my notes for a JAX-RS application there may be one-more thing to add for my suggestion to work for you,
add `@DeclareRoles("Ham-User")` annotation for your TestResource. 

It should look like
```
@Path("resource")
@DeclareRoles("Ham-User")
public class TestResource {
```

**Reasoning:**
Without the roles declared (`@DeclareRoles("Ham-User")`), then the roles are implicitly declared from the `@RolesAllowed` annotations. The issue with  `@RolesAllowed("**")` declaring a `"**"` role is that the `"**"` role is declared like a normal role, like "HAM-User", instead of the special ALL_AUTHENTICATED_USERS role.

By declaring the roles explicitly with `@DeclareRoles("Ham-User")`, `"**"` will not be a declared role, so `@RolesAllowed("**")` should behave how you want because it will only be treated as the special ALL_AUTHENTICATED_USERS role instead of as a normal declared role.

**Comment by c-koell** [comment]
@Zech-Hein thanks for the clarification. Now it works fine !
Maybe you adjust the documentation for that use case ..

**Comment by Zech-Hein** [comment]
Glad to hear it!
