### ISSUE TITLE
Unexpected end of file from server

### ISSUE THREAD

**Issue by martzkb** [OpenLiberty/open-liberty#28049]
**Describe the bug**  
Back to back requests randomly fails with "java.net.SocketException: Unexpected end of file from server"

```
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:917)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:724)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
```

**Expected behavior**  
We expect the request to not fail.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9+
 - Java Version: 11.0.21+9

**Additional context**  
We see this is a known Open Liberty issue [here](https://github.com/OpenLiberty/open-liberty/issues/25866). Based on the comments, this seems to be fixed ONLY for JAX-WS but we are seeing this using JAX-RS on both 23.0.0.9 and 24.0.0.3.

**Comment by jim-krueger** [comment]
Hi Kassidy,  Sorry this has taken so long.  I was thrown off a bit by the fact that this issue had a resolution in JAXWS.  After reproducing this problem a investigating it completely, I believe that what you are experiencing here is expected behavior.  Beyond that I also believe that the JAXWS resolution was not correct.

First, let me confirm something.   In the JAXWS issue referenced earlier and in my reproduction, the Keep-Alive value in the IHS proxy server was set to 3 seconds.  Assuming that is the case then that is the problem.

The Keep-Alive timeout for the JDK on the Liberty server defaults to [5 seconds](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java#L173).   This causes a problem.   See #5 in this [tuning guide](https://publib.boulder.ibm.com/httpserv/cookbook/Cookbook_General-Statistics.html#General-Statistics-Queuing_Theory-Tuning_Timeouts).

So to resolve this issue please ensure  that the keep-alive timeout values in you IHS proxy server are set higher than the corresponding values in JDK for the Liberty server it is sending request to.

Hopefully this helps.

**Comment by jim-krueger** [comment]
I am closing this issue as I believe my last update resolved this issue.   Please re-open this if more attention is needed.  Thanks
