### ISSUE TITLE
Exceptions when mpHealth-1.0 and sessionCache-1.0 are enabled

### ISSUE THREAD

**Issue by dacleyra** [OpenLiberty/open-liberty#2805]
When both mpHealth-1.0 and sessionCache-1.0 are enabled, several exceptions occur. See attached log.

[messages.log_mp_sc.txt](https://github.com/OpenLiberty/open-liberty/files/1838678/messages.log_mp_sc.txt)

**Comment by njr-11** [comment]
I tried enabling the exact feature set from the attached log file, including both mpHealth-1.0 and sessionCache-1.0 and did not see any errors.  Could you attach the server configuration file that you are using so that we can attempt to reproduce more precisely?

**Comment by mswatosh** [comment]
@dacleyra 
It looks like this might be an issue with newer Java versions. I tried the app on the following JDKs:
1.8.0_71 (IBM): No exceptions
1.8.0_151 (IBM): No exceptions
1.8.0_161 (IBM): An unexpected exception occurred when trying to retrieve the session context
java.security.ProviderException: setSeed() failed
    at sun.security.provider.NativePRNG$RandomIO.implSetSeed(NativePRNG.java:472)
    at sun.security.provider.NativePRNG$RandomIO.access$300(NativePRNG.java:331)
    at sun.security.provider.NativePRNG.engineSetSeed(NativePRNG.java:214)
    at java.security.SecureRandom.setSeed(SecureRandom.java:464)
....
Caused by: java.io.IOException: Operation not permitted
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:313)
    at sun.security.provider.NativePRNG$RandomIO.implSetSeed(NativePRNG.java:470)

1.8.0_161 (Oracle): SRVE8059E: An unexpected exception occurred when trying to retrieve the session context
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: javax.cache.configuration.FactoryBuilder$SingletonFactory
....
Caused by: java.lang.ClassNotFoundException: javax.cache.configuration.FactoryBuilder$SingletonFactory

**Comment by aguibert** [comment]
ok, so here is what I've found out so far:
- it's not JDK dependent (reproduced issue on Oracle 151 and 161, IBM JDK would probably have same issue if it didn't blow up on the secure random thing)
- issue occurs when `mpHealth-1.0` is enabled.  The MP Health code doesn't seem to be directly responsible, but it does pull in some suspicious looking features that could be causing the behavior change, particularly: `com.ibm.websphere.appserver.classloaderContext-1.0`
- issue occurs when the TCCL is `com.ibm.ws.classloading.internal.ThreadContextClassLoaderForBundles` as opposed to `com.ibm.ws.classloading.internal.ThreadContextClassLoader` or `AppClassLoader`


An easy way to resolve this issue appears to be to have the jcache API bundle export the `javax.cache.*` packages to the bundle thread-context.  However, this raises a much more general concern of `ThreadContextClassLoaderForBundles` instances not being able to load classes that the correspond bundle loader can.  I think we need @chackoj to weigh in on this to see if he can offer any insight as to why TCCL4Bundles works the way it does before we proceed.
