### ISSUE TITLE
Environment variables not available during service startup within Kubernetes/OpenShift

### ISSUE THREAD

**Issue by vickimfox** [OpenLiberty/open-liberty#28475]
**Describe the bug**  
I am building a REST API service that is deployed in a Kubernetes/OpenShift pod. I want to customize the Server List on the OpenAPI UI page to reflect the specific URL associated with the pod environment, such as DEV URL when running on DEV environment, TEST URL when running on TEST, etc.

The current approach is to set an environment variable on the OpenShift DeploymentConfig object with the URL I want to appear on the OpenAPI Server List. I then override the MicroProfile OpenApi OASFilter Class to read the environment variable and update the Server List.

When running the API within the Liberty Tools on Eclipse IDE, the Server List would update correctly.

However, when packaged and deployed to OpenShift, the Server List would remain empty. Adding an explicit System.getEnvVar() call and writing to log showed that the environment variable was not found. However, later processing after the CDI "engine" started, then all EnvVars are available.

The question is - why is the EnvVar missing in OpenShift when OASFilter class invoked early in startup processing but the EnvVar is populated after the service has started?

**Diagnostic information:**
- OpenLiberty Version: 23.0.0.4 and 23.0.0.12
- Affected feature: mpOpenApi
- Java Version: JDK 17

**Research and discovery:**
I did the following research and discovered the cause of the problem.

Since the only difference between running in Eclipse vs running in OpenShift was the startup processing, I looked into how the server is launched. For the IDE, the server started as a child of Eclipse and had full visibility to the EnvVars defined. However, for the Docker Image, there was a more involved startup process.

The Docker Image startup involved two scripts - `/opt/ol/helpers/runtime/docker-server.sh` and `/opt/ol/wlp/bin/server`. My discovery is:
- In K8s/OpenShift, the script starts the server as a background process, not in the foreground.
- To pass the foreground defined EnvVars, the script writes the EnvVars to a file and passes this file to the background process.
- The background process uses this file to create the EnvVars in the background process scope
- Main discovery, a significant portion of OpenLiberty startup runs BEFORE the EnvVars are rebuilt. The EnvVars are defined just-in-time for the start of the CDI "engine". As a result, there are several startup activities that run before the EnvVars are available.
- The OASFilter for building the OpenAPI is one of these early startup activities. As a result, it does not have visibility to the EnvVars.

Because MicroProfile Config works during this phase of startup, my workaround will be to leverage one of the files that Config searches and mount it via the DeploymentConfig mount configMap feature.

**Bug Request**
- Can the EnvVar redefinition phase be moved earlier in the lifecycle of the background process?
- Can the documentation be updated to describe the startup phases and what limitations, like the above, exist in running from Docker Image?

**Comment by tjwatson** [comment]
Can you reproduce with local Podman/Docker runs on the image where you pass in `--env` to set the configuration?
Are you using [Liberty InstantOn](https://openliberty.io/docs/latest/instanton.html)?  If not then the Liberty Java process should not be starting in the background.  The intention is that it is started in the foreground with PID 1 of the container.

**Comment by tjwatson** [comment]
Another question.  You mention Liberty starting in the background.  The default [`CMD` command](https://github.com/OpenLiberty/ci.docker/blob/2413736dbba3692495e2d41fae1848554f6bc8a5/releases/latest/kernel-slim/Dockerfile.ubi.openjdk21#L152) is set to `server run defaultserver`.  This should start the server in the foreground using PID 1 with the [`exec` command](https://github.com/OpenLiberty/ci.docker/blob/2413736dbba3692495e2d41fae1848554f6bc8a5/releases/latest/kernel-slim/helpers/runtime/docker-server.sh#L144) from the `docker-server.sh` script which is the [default ENTRYPOINT](https://github.com/OpenLiberty/ci.docker/blob/2413736dbba3692495e2d41fae1848554f6bc8a5/releases/latest/kernel-slim/Dockerfile.ubi.openjdk21#L151)

Is it possible you override the `CMD` in your container image to be something like `server start defaultServer`?  Using the `start` action would start the Liberty process in the background instead of the foreground.  Can we see an example of a `Dockerfile`/`Containerfile` you use to create the container image?

**Comment by vickimfox** [comment]
The `Dockerfile` does very little. Here is the abbreviated version, minus company documentation:

```
FROM .../openliberty/open-liberty:full-java17-openj9-ubi
COPY --chown=1001:0 src/main/liberty/config  /config/
COPY --chown=1001:0 target/query-service.war /config/apps/
EXPOSE 9080 9443
RUN configure.sh
USER 1001
```

I'm using the default `CMD` provided by the base image. Due to our corporate hub proxy still pointing to Docker Hub, the FROM pulls the 23.0.0.4 release. Working on migrating to the ICR hub.

I am not using Liberty Instant-On.

I will try to run local desktop instance of the Docker Image, but it will take me a couple days given my schedule.

To better illustrate what I'm seeing:

The following code fragment is from my OASFilter. This runs early in the OL lifecycle. It does not see the EnvVar. It uses MP Config to read EnvVar.

```
public class OpenApiFilter implements OASFilter {

    @Override
    public void filterOpenAPI(OpenAPI openAPI) {
        ...
        Config cfg = ConfigProvider.getConfig();
        String value = cfg.getValue("env.role", String.class);     // Read ENV_ROLE or env.role via MP Config
        ... logging value only shows empty string, the default set in server.xml ...
        ... not reading EnvVar
    }
}
```

However, the following code, which validates HTTP REST requests, which runs later in OL lifecycle, works perfectly.

```
@Provider
public class EnvAuthRequestFilter implements ContainerRequestFilter {

    @Inject SecurityContext secctx;

    @Override
    public void filter(ContainerRequestContext aRqsCtx) throws IOException {
        ...
       Config cfg = ConfigProvider.getConfig();
       String value = cfg.getValue("env.role", String.class);
       ... logging value shows the expected role of the environment (DEV, TEST, PROD, etc)
       ... which is set in EnvVar
    }
}
```

By the way, EnvAuthRequestFilter works correctly whether I use MP Config @Inject or call to `ConfigProvider`.

Thanks for looking into this.

EnvVar "hidden" early in lifecycle. But visible after CDI starts?

**Comment by Azquelt** [comment]
Found the cause of this: the OpenAPI document is being built and cached during the container build and the cache is not correctly invalidated.

Building the OpenAPI document takes a non-trivial amount of time, so we cache it where we can. When we build a docker container, the OpenAPI document is built and cached by the `configure.sh` script which runs at the end of the build process.

The problem is that we're not invalidating that cache. The caching code assumes that if the code hasn't changed and the config that's relevant to OpenAPI hasn't changed, then it's safe to reuse the model. This isn't true if there's any user code used to build the model because it could reference anything so we need to re-run it at startup.

**Comment by Azquelt** [comment]
We'll need to update the way we invalidate the cache, and probably change it so that we can cache the jandex index used for code scanning since creating that is the slowest part and that should still be safe to use if the code hasn't changed.

In the mean time, as a workaround, you can change this line in your dockerfile:

```Dockerfile
RUN configure.sh
```

to
```Dockerfile
RUN configure.sh && rm /output/workarea/org.eclipse.osgi/*/data/cache/*/model
```
which will delete one of the cache files which will cause the OpenAPI document to be recreated on container start. This will unfortunately mean your container will take slightly longer to start.

The command has two `*`s in it - the first one is for the bundle ID of the openapi bundle which we don't know ahead of time. The second is for the application name, you could replace this one with the name of your application.

**Comment by vickimfox** [comment]
Quick follow-up to say **thank you** for the quick resolution and the workaround fix.
