### ISSUE TITLE
Followup: Eclipselink 2.7 English NLSProps Update

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#332]
The ID review for issue #135 has a number of open English NLSProps updates, namely refactored English sentences, that were not completed when the pull request was submitted for integration.  This issue was opened to track completion of the nlsprops update.

**Comment by daliasheasha** [comment]
After spending some time looking at the EclipseLink messages, I noticed that we were detecting a lot more messages than expected between EclipseLink 2.6 and 2.7. It turned out that a change went into EclipseLink a while back that combined logging messages and trace messages into one file which were previously separated. The separation allowed us to exclude trace messages from translation since there is no need to translate trace. So, I went back to the EclipseLink community and asked if we could revert that change since we still need the message separation to easily distinguish between messages that need translation and messages that don't. After getting their approval, I went ahead and reverted the change in EclipseLink. Currently, the EclipseLink 2.7 and master branch have their trace and logging messages separated. I also committed changes to the messages according to the ID review. 
All these updates are currently in the EclipseLink repository. However, they are not in Liberty yet. Once Will Dazey has finished his task to upload the needed 2.7 binaries instead of the 2.7_WAS binaries, I will pull the 2.7 binaries into Liberty which will pull in the message changes into Liberty.
