### ISSUE TITLE
Feature-Request: Add featureExclude to featureManager in server.xml

### ISSUE THREAD

**Issue by 38leinaD** [OpenLiberty/open-liberty#3869]
This is a feature-request that came up when i was replacing the default jpaProvider in Liberty by a custom one.
You can read all of the discuss and also the discussion about the feature-request
[here](https://groups.io/g/openliberty/topic/20719688?p=Created,,,20,1,0,0::recentpostdate/sticky,,,20,2,0,20719688)

In essence what this about is that when developing against the Java EE 7 API, you have a very lean feature-list:
```
<featureManager>
		 <feature>javaee-7.0</feature>
</featureManager>
```
in the server.xml. This will internally add the feature
jpa-2.1 = jpaContainer-2.1 + EclipseLink impl

When pluging in my own Persistence-provider, the configuration for Java EE 7 + custom JPA provider requires this in the server.xml today:

```
<featureManager>
		<feature>servlet-3.1</feature>
		<feature>beanValidation-1.1</feature>
		<feature>ssl-1.0</feature>
		<feature>jndi-1.0</feature>
		<feature>jca-1.7</feature>
		<feature>jms-2.0</feature>
		<feature>ejbPersistentTimer-3.2</feature>
		<feature>appSecurity-2.0</feature>
		<feature>j2eeManagement-1.1</feature>
		<feature>jdbc-4.1</feature>
		<feature>wasJmsServer-1.0</feature>
		<feature>jaxrs-2.0</feature>
		<feature>javaMail-1.5</feature>
		<feature>cdi-1.2</feature>
		<feature>jcaInboundSecurity-1.0</feature>
		<feature>jsp-2.3</feature>
		<feature>ejbLite-3.2</feature>
		<feature>managedBeans-1.0</feature>
		<feature>jsf-2.2</feature>
		<feature>ejbHome-3.2</feature>
		<feature>jaxws-2.2</feature>
		<feature>jsonp-1.0</feature>
		<feature>el-3.0</feature>
		<feature>jaxrsClient-2.0</feature>
		<feature>concurrent-1.0</feature>
		<feature>appClientSupport-1.0</feature>
		<feature>ejbRemote-3.2</feature>
		<feature>jaxb-2.2</feature>
		<feature>mdb-3.2</feature>
		<feature>jacc-1.5</feature>
		<feature>batch-1.0</feature>
		<feature>ejb-3.2</feature>
		<feature>json-1.0</feature>
		<feature>jaspic-1.1</feature>
		<feature>distributedMap-1.0</feature>
		<feature>websocket-1.1</feature>
		<feature>wasJmsSecurity-1.0</feature>
		<feature>wasJmsClient-2.0</feature>

		<feature>jpaContainer-2.1</feature>
    </featureManager>
```

This is because the only feature we want to not have is the jpa-2.1 feature (note that <feature>jpa-2.1</feature> is not in the list).

It would be better if the featureManager offers something like a featureExclude mechanism to exclude a feature that is pulled in by some other feature.
E.g. a config like below would allow a simpler configuration like this:

```
<featureManager>
  <feature>javaee-7.0</feature>
  <featureExclude>jpa-2.1</featureExclude>
  <feature>jpaContainer-2.1</feature>
<featureManager>
```

As <feature>javaee-7.0</feature> is the default setting for everyone developing against the full Java EE 7 API, this would not require to think and know about all the sub-modules pulled in by <feature>javaee-7.0</feature> transitively in case a custom persistence-provider is plugged in.

**Comment by brenthdaniel** [comment]
I think this would quickly become very dangerous for any feature other than the convenience features (javaee-x). Most features define a minimum set of sub-features required for that component to operate, so removing one is likely to cause issues. 

Another option would be to create a user feature that includes the features you need without JPA-2.1. Then you would only need to specify your user feature rather than a long list of features.

**Comment by aguibert** [comment]
Also, hopefully the large feature list you had to specify makes one realize how much extra stuff gets dragged in by the `javaee-7.0` convenience feature.  Consider if you actually need all of these features enabled.  Remember that by specifying a smaller set of features, the server will start faster, have a smaller memory footprint, and can be minified down to a smaller image size on disk.

**Comment by 38leinaD** [comment]
> I think this would quickly become very dangerous for any feature other than the convenience features (javaee-x). Most features define a minimum set of sub-features required for that component to operate, so removing one is likely to cause issues.

Understand. I was also thinking this particular case is very special and maybe there are not alot of other use-cases where you want to remove a feature when there is a dependecy to it.

> Another option would be to create a user feature that includes the features you need without JPA-2.1. Then you would only need to specify your user feature rather than a long list of features.

Where can I read up on user features? I have not come across them yet.

**Comment by 38leinaD** [comment]
> Also, hopefully the large feature list you had to specify makes one realize how much extra stuff gets dragged in by the javaee-7.0 convenience feature. Consider if you actually need all of these features enabled. Remember that by specifying a smaller set of features, the server will start faster, have a smaller memory footprint, and can be minified down to a smaller image size on disk.

Understand and this might be a concern in large large microservice architectures, but these are all not concerns I face with customers. The difference in startuptime is 2 seconds on my computer when I start with servlet-3.1 only versus full javaee-7.0. The difference in RAM is ~30 MB.
I rather have a single feature and can code against the full java ee spec instead of cherry-picking some features. Fiddling with the "right" feature-list will over time cost me considerably more than the price for additional 30 megabytes of RAM.

**Comment by 38leinaD** [comment]
> I wonder if instead we could get the feature provisioner to get the jpaContainer feature in the following configuration to automatically drop the jpa-2.1 feature:

I think that would make most sense!
I you have read the discussion i was linking to in my initial change-request-text, Will Dazey explain to me that actually jpa-2.1 is also a "convenience feature" in that regard that

jpa-2.1 = jpaContainer-2.1 + EclipseLink impl
jpaContainer-2.1 = JPA 2.1 spec + container integration

So, the feature provisioner would need to drop jpa-2.1 but still make sure that jpaContainer-2.1 stays in the feature-set.

Btw.: Depending on if it will be agreed that this is a useful feature and what the level of skill required is, I am interested to give it a shot myself. Obviously, this would require some guidance because I have zero experience with the liberty code-base.

**Comment by 38leinaD** [comment]
To me this looks like a good approach. i am not sure if by default all features should be optional for javaee-7/8, webProfile-7/8, and microProfile-1.X though.
the jpa-container is a specific feature to swap out the JPA-implementation and much more common then swapping out other parts of the spec (at least that is my feeling).

- So, making JPA easily swappable: Yes -> should be "optional".
- The other specs: should not be optional by default (but could be made optional in the future easily as the feature to support it, is generic).

**Comment by Azquelt** [comment]
@aguibert When discussing this, don't forget that if you change the feature metadata used for doing feature resolution, then some work will also need to be done to get that new metadata stored in the repository so that it can be used when working out which features to install from the repository.

**Comment by brenthdaniel** [comment]
There would also be an extensive amount of work to the feature checker. There would also be a significant amount of ongoing work to deal with the new permutations that would result from adding this. 

I'm not sure that adding an "exclude" element is feasible or even desireable. It seems like we're trying to solve a very specific problem with JPA with a general solution that would not extend very well to future cases. It also unnecessarily complicates the way users define a set of features. If we can't simply refactor the features so that the feature resolver can automatically pull in the correct set of dependencies, I think it would be better to focus on a solution like Alasdair proposed where we automatically exclude a feature under certain conditions (maybe a "negative" autofeature..)

**Comment by NottyCode** [comment]
Had a discussion about doing this and the concern is still that getting the feature resolver updated to deal with this will be expensive in terms of development time and result in very complex behaviour in the feature manager.  So we discussed whether it would make sense (if we were to spend that much resource on it) writing some code that could essentially detect which programming model features to run. Ultimately we weren't sure what the best tradeoff was in terms of a) usability and b) cost to implement c) complexity to the runtime.

There hasn't been a conclusion as yet, but we've been throwing some ideas around.

**Comment by tevans78** [comment]
We are still considering various options for this issue.

**Comment by NottyCode** [comment]
This issue keeps coming up. During a recent discussion with someone else asking for the exact same thing it occurred to me that a possible option would be instead of adding exclude configuration we could have a tool that generates a new feature based on one of our grouping features (and only for the grouping features like webProfile-X, javaee-X, microProfile-X) minus the feature that is not required. This feature could then be installed as an user feature.

This would require better tooling support in Open Liberty for installing user features, but it would make it easy for people to essentially create their "everything in Java EE except JPA" configuration and it wouldn't make resolution at runtime impossible because you could end up with an un-resolvable runtime.

**Comment by aguibert** [comment]
That is an interesting idea, but I expect that this extra tool that can generate and then apply a new custom feature to their runtime seems more tedious than the original workaround which is to simply list out every `<feature>` in server.xml.

The steps as-is today are:
1. Find the "server installed the following features" message after starting the server
1. Copy/paste the feature list into server.xml
1. Surround each feature shortname with `<feature>SHORTNAME</feature>`, insert line breaks, and remove commas.

These steps on the surface are not that difficult and I think in general users would be OK with doing this. I believe the problem is that it's not clear what features enable each other, so even if users did list out all of their features in server.xml they wouldn't know which ones they could get rid of.

Perhaps we could introduce a new format for the "features installed" message to give a visualization of what features are pulling in each other? For example:
```xml
<server>
  <fm>
    <f>javaee-8.0</f>
  </fm>
</server>
```
Might show logs like this:
```
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-3.0, beanValidation-2.0, cdi-2.0, ejbLite-3.2, jaspic-1.1, jaxrs-2.1, jaxrsClient-2.1, jdbc-4.2, jpa-2.2, jpaContainer-2.2, jsonb-1.0, jsonp-1.1, managedBeans-1.0, webProfile-8.0, websocket-1.1].
[AUDIT   ] CWWKF0099I: The feature dependencies are:
webProfile-8.0
+- appSecurity-3.0
|    \- jaspic-1.1
+- beanValidation-2.0
+- cdi-2.0
+- ejbLite-3.2
|    \- managedBeans-1.0
+- jaxrs-2.1
|    \- jaxrsClient-2.1
+- jpa-2.2
|    \- jpaContainer-2.2
|        \- jdbc-4.2
+- jsonb-1.0
|    \- jsonp-1.1
+- jsonp-1.1
+- websocket-1.1
```
(I'm not sure if this graph is 100% accurate, but it's the basic idea -- format derived from `mvn dependency:tree` output)

**Comment by NottyCode** [comment]
Alasdair to extract from a meeting recording the latest state of discussion and replace this comment with a summary.

**Comment by cbridgha** [comment]
After discussing this request several times...  The complexity for the implementation, including a high chance the user causing unintended exclusions...   The decision has been made to keep the existing practice of simply listing each feature in the server.xml

**Comment by hantsy** [comment]
Need this feature exactly, it is really useful when using alternative features. 

For example, I would like to use Mojarra to replace the Myfaces.

For the syntax, I think it can be more simple, not need add extra new element, add a "-" or "!" to at the front of the feature name is ok.

eg. 

```xml
<feature>-jsf-2.3</feature> <!-- indicate this feature should be exclued.-->
<feature>!jsf-2.3</feature> <!-- indicate this feature should be exclued.-->
```

**Comment by hantsy** [comment]
>The complexity for the implementation, including a high chance the user causing unintended exclusions... The decision has been made to keep the existing practice of simply listing each feature in the server.xml

```xml
<featureManager>
    <feature>javaee-8.0</feature>
    <feature>!jsf-2.3</feature>
    <feature>jsfContainer-2.3</feature>
</featureManager>
```
**Not sure why it is so complexity to calculate the features?**

Just list all features, and minus the excluded, then get the feature to be installed.

**Comment by hantsy** [comment]
For me, in a Java EE/Jakarta EE application, list all features of Java EE , and just exclude one of them,  the experience is so bad.
