### ISSUE TITLE
Minfying and then starting a server can result in two singleton features being started

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#3925]
When you have a server which uses features with dependencies that have tolerates, you can end up with a minified server which includes two versions of a singleton feature.

E.g. in my development environment, I had
* mpFaultTolerance-1.1 -> mpConfig-1.1 (tolerates 1.2)
* mpMetrics-1.1 -> mpConfig-1.2

If I run `server package --include=minify` then the minified server includes both mpConfig-1.1 and mpConfig-1.2. (This fine and, I think, as expected)

However, if I then run `server run`, the server starts both mpConfig-1.1 and mpConfig-1.2 at the same time! (Predictably, this then causes my app not to start).
`[AUDIT   ] CWWKF0012I: The server installed the following features: [mpFaultTolerance-1.1, servlet-3.1, ssl-1.0, jndi-1.0, jsonp-1.0, appSecurity-2.0, mpConfig-1.1, jaxrs-2.0, mpConfig-1.2, jaxrsClient-2.0, concurrent-1.0, mpRestClient-1.0, mpMetrics-1.1, json-1.0, cdi-1.2, distributedMap-1.0].`

**Note 1**: I'm not sure how likely this is to happen in the real world with openliberty at the moment as I don't know how many tolerated feature dependencies we have. Some investigation is needed to see if it's possible to reproduce this on a released version. By the time it's ready for release, mpFaultTolerance will probably just require a specific version of mpConfig.

**Note 2**: I haven't checked if this occurs on Websphere Liberty (we have many more tolerated features there because we have things that work with Java EE6 and Java EE7)

**Note 3**: Packaging and then running a server might not seem a common scenario, but it's very likely to happen when using the liberty maven plugin if you've configured it to produce a minified package or runnable server jar. When testing for development you're likely to run `mvn package liberty:run-server` which will build the package and then start the server.

**Note 4**: Starting the server with `--clean` the first time after packaging fixes the issue. We probably just need to clean out the workarea directory after (and maybe before?) packaging the server. I don't know if it's possible to do this in the maven scenario.

**Comment by canterburymalcolm** [comment]
It looks like this is caused by the minify operation writing to the top-level `workarea/platform` folder, which the server then uses to get its cached feature resolution instead of creating it correctly.

@dazavala, 
@tjwatson suggested using the `workarea/workarea-util` folder added in #7491 to store the information used during the minify operation so it won't collide with the runtime's real workarea.

**Comment by Azquelt** [comment]
FYI: I think they worked around the common case in the maven plugin by packaging and running the server in different locations. I assume the issue in Liberty still exists, I haven't checked since I raised the defect.

**Comment by tjwatson** [comment]
The defect still exists.  The issue is the minify process is writing a cached feature resolve result into `workarea/platform`.  That result is then being used if you start the server using that `workarea/platform`.  During minify the feature resolver uses a mode that pulls in various tolerated features instead of only the actual one that will get selected at runtime.  I don't recall exactly why that choice was made to do it that way, but it has been that way from the start.

What is surprising is that the fix in #7491 did not fix this issue.  I would expect when the minify utility is run it would store the feature resolution cache into `workarea/workarea-util/platform`, but it is still storing it in the main `workarea/platform` directory.  Here are the steps to reproduce:

1. server server create `testServer`
1. add these features to server.xml `mpFaultTolerance-1.1`, `mpMetrics-1.1`
1. Run a minify on the server: `server package testServer --include=minify
1. Start the original server: `server run testServer`

Note that you must not start/run the `testServer` until the final step.  If you start/run the `testServer` before the minify step then you will not reproduce the issue.

**Comment by dazavala** [comment]
The problem recurs because the fix for issue 7491 does not seed the location service with the utility workarea directory specific to the server package command (utility). The feature manager uses the location service to locate and obtain the bundle and feature caches of the server. In the fail case, the feature manager caches the feature set computed by the utility to the workarea of the target server rather than the workarea we expect the utility to use; and when the server is restarted, the server runtime starts the unexpected feature set. 

PR 9388 modifies the bootstrap facility to propagate the package command's workarea via a server config property, making it available at service activation. The location service will then initialize the workarea directory resource and corresponding variable registry value as expected. The solution impacts any command utility that launches an embedded server with the utility-specific workarea.
