### ISSUE TITLE
Can't run app with LocalDate fields in JAX-RS entities

### ISSUE THREAD

**Issue by mthmulders** [OpenLiberty/open-liberty#399]
I've tried to write a simple app that exposes one JAX-RS endpoint. The endpoint accepts an HTTP `POST` with a date field. I expect the JSON to be unmarshalled into a `LocalDate` instance. To do that, I wrote a simple `XmlAdapter`.

This approach works fine in Payara or WildFly, but it fails to work in Liberty. I've created a simple [reproduction repo](https://github.com/mthmulders/openliberty-lombok-jackson-issue). I'm not sure Lombok has to deal with the issue at hand - I used `@Builder` first but even if I drop that it doesn't work.

**Comment by andymc12** [comment]
Hi @mthmulders, I create PR [1](https://github.com/mthmulders/openliberty-lombok-jackson-issue/pull/1) for this issue.  

It seems like the problem is that the app either depends on a newer version of Jackson than what Liberty ships, or the lombok code (of which, I'm unfortunately not familiar with) depends on Jackson APIs in order to handle the JSON serialization.

Liberty packages an old version of Jackson, and does not expose the APIs to user applications.  The latter is intentional as it allows users to provide their own version of JSON serialization without needing to resort to classloader tricks like using _parentLast_ or shared libraries, etc.  

The changes in the pull request are based on code I submitted as part of an article on [bringing your own Jackson](https://developer.ibm.com/wasdev/docs/jax-rs-websphere-liberty-byo-jackson/).  This change should also work with other vendors' app servers, and gives you (the application deployer) more control over what provider(s) are used for JSON serialization/deserialization.

In the future, I would suggest using JAX-RS 2.1 and JSON-B 1.0 which is very similar to Jackson, but more portable - and without needing to package your own JSON provider (though it is also flexible enough to allow you to do it without the classloader tricks ;)  ).  

Hope this helps, Andy

**Comment by andymc12** [comment]
@mthmulders I upgraded the level of Jackson in OpenLiberty, and this resolves the issue for me.  Can you give it a try to see if it works for you too?  If so, you could avoid the workaround I suggested earlier.

Thanks, Andy

**Comment by mthmulders** [comment]
Sure, I'd love to give it a try. Should I just grab the [latest dev build] (https://openliberty.io/downloads/)?

**Comment by andymc12** [comment]
Yes, I think the 2017-10-14 build should have the updated Jackson libraries.  Thanks!

**Comment by mthmulders** [comment]
Just tried the 2017-10-14, 20:03 build and I can confirm the issue is resolved. Thanks a lot!
