### ISSUE TITLE
MP FaultTolerance 2.0: Feature Test Summary

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#4079]

**Comment by Azquelt** [comment]
Here are the main changes in Fault Tolerance 2.0 and the test plan to go with them

* Specify the interactions between Fault Tolerance annotations
  * **Note:** this requires a complete rethink of the way we handle methods annotated with `@Asynchronous` and will likely result in a redesign of large parts of the core Fault Tolerance implementation. (Initial implementation merged as #5506)
  * Existing tests should be sufficient to give us assurance that the redesigned implementation doesn't cause regressions (except in cases where the new specifications requires changes from our previous behaviour).
  * New TCKs will be added to verify the correct behaviour where there are multiple annotations on the same method (eclipse/microprofile-fault-tolerance#333)
* Allow methods annotated with `@Asynchronous` to return `CompletionStage` (as well as `Future`)
  * Test returning a result as a completion stage
  * Test correct handling of thrown exceptions
  * Test adding actions to be run when the stage completes, both before and after it is returned from the method and verify that the actions are executed in the correct order
  * Test returning an incomplete completion stage which is then completed later
  * Test returning a CompletionStage in conjunction with each of the fault tolerance annotations
* Specify interactions with `@AroundInvoke` interceptors applied to CDI beans
  * Test that we can add `@AroundInvoke` interceptors both before and after the Fault Tolerance interceptor and that they are executed as expected
  * Test that the interceptors are executed as expected with each of the fault tolerance annotations
    * Interceptors with a lower priority should always be executed exactly once on the calling thread
    * Interceptors with higher priority should be executed for each retry attempt
    * Interceptors with higher priority should not be executed if a CircuitBreakerOpenException occurs
    * Interceptors with higher priority should not be executed if a BulkheadException occurs
    * When running asynchronously, interceptors with a higher priority should not run on the calling thread
  * Test that the priority of the Fault Tolerance interceptor can be set at startup using a config parameter
* Possible feature: handling of CompletionStage could be changed so that fault tolerance handling is applied when the returned CompletionStage completes, rather than when the method returns
  * In addition to the tests described above, we'd want to do more testing with returned completionstages that are incomplete.
  * We should create FAT tests which test the use of this functionality with the new JAX-RS 2.1 `.rx()` features as this is expected to be a common use case.
