### ISSUE TITLE
Subject is null on unconstrained resources

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/open-liberty#4196]
`PolicyContext.getContext("javax.security.auth.Subject.container")` returns null on unconstrained Servlets, even when authentication was performed.

### Reproducer setup
Enable JACC by installing a provider, for example https://github.com/ggam/jacc-provider from @arjantijms

The project contains a OSGi bundle and a "testjacc.mf" manifest.

Server.xml:
```
<server description="new server">

    <featureManager>
        <feature>javaee-7.0</feature>
        <feature>localConnector-1.0</feature>
        <feature>usr:testjacc</feature>
    </featureManager>
    
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"/>
    
    <ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" />
    <keyStore id="defaultKeyStore" password="CHANGEIT" />
    
    <basicRegistry id="basic" realm="customRealm" />
    
    <webContainer deferServletLoad="false"/>
    <ejbContainer startEJBsAtAppStart="true"/>
                  
    <applicationManager autoExpand="true"/>
</server>
```
Deploy the following war (rename to app-securitycontext.war or compile directly from https://github.com/eclipse-ee4j/soteria/tree/master/test/app-securitycontext): [app-securitycontext.zip](https://github.com
/OpenLiberty/open-liberty/files/2167508/app-securitycontext.zip)

### Steps to reproduce 
Go to http://localhost:9080/app-securitycontext/servlet?name=reza&password=secret1
The call is authenticated via JASPIC, and `HttpServletRequest#isUserInRole()` return the correct results, but `PolicyContext.getContext("javax.security.auth.Subject.container")` returns null and so `SecurityContextImpl` doesn't find any role. All EJB `#isCallerInRole` calls also return false.

### Expected result

When the call is authenticated, the Subject must be available at `PolicyContext.getContext("javax.security.auth.Subject.container")`.

**Comment by utle** [comment]
Hi, 
Can yo enable security trace by adding the following line in the server.xml, re-create this problem and upload the trace.log.  Thanks. 
<logging traceSpecification="*=info:com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.security.*=all" />

**Comment by ggam** [comment]
Here it is: [trace.log](https://github.com/OpenLiberty/open-liberty/files/2197038/trace.log)

The output of http://localhost:9080/app-securitycontext/servlet?name=reza&password=secret1:
```
This is a servlet 
web username: reza
web user has role "foo": true
web user has role "bar": true
web user has role "kaz": false
ejb username: reza
ejb user has role "foo": false
ejb user has role "bar": false
ejb user has role "kaz": false
context username: reza
context user has role "foo": false
context user has role "bar": false
context user has role "kaz": false
has access to /protectedServlet: false
All declared roles of user []
```

Expected output is to have the same roles on web, EJB and "context".

**Comment by arkarkala** [comment]
Sorry for the delay and thanks for the traces. We were also able to reproduce this issue. We will update with our findings/fix soon.

**Comment by ggam** [comment]
Great, thanks for keeping me informed

**Comment by arkarkala** [comment]
The fix for the Subject being null has been delivered. However, in order to run your test successfully changes seem to be required in your app. One way that seem to work..
1) Use the @RolesAllowed("foo", "bar") annotation to match the 1-1 mapping supported in your JACC provider for the EJB.
2) Move the SecurityContext calls before the EJB calls. Looks like in the current order, the SecurityContext calls rely on the EJBContext which is not available outside the EJB.

**Comment by ggam** [comment]
Thanks @arkarkala. Is this fix already released? Can I get a nightly build from a Maven repository?

We can change our `SecurityCodeImpl` implementation if we are relying on non portable behavior. I'll have a look at it.

**Comment by arkarkala** [comment]
Yes, you can get it from the latest nightly development builds.

**Comment by tevans78** [comment]
This issue has been resolved so I am closing it.

**Comment by arkarkala** [comment]
Hi, will look into this more but can you try using the appSecurity-3.0 feature (that supports JSR375) instead of appSecurity-2.0 or better just include the javaee-8.0 feature that includes all javaee8 features including appSecurity-3.0? 

If I remember correctly, the @RolesAllowed annotation is needed for the EJB authz (1-1 role to group mapping) to work. Should not be related to null subject. Please try that and see.

**Comment by ggam** [comment]
Thanks @arkarkala, I'll try what you say. The reason I'm manually selecting features is that I want to use Soteria as the JSR375 implementation, so I need the disable the one from OpenLiberty. Since JSR375 relies only on JASPIC and JACC, this should easily work.

I'm installing a custom JACC provider (https://github.com/arjantijms/jacc-provider) which should manage the 1:1 role mapping. I'll try with the ``@RolesAllowed` though and will debug the JACC provider code to ensure it's being correctly called with and without the annotation.

Thanks for the insight.

**Comment by arkarkala** [comment]
So using our JSR375 provider your tests seem to work provided you add the @RolesAllowed for EJB (more on this later).

If you are using Soteria's JSR375 impl, in addition to @RoleAllowed, you have to move all the SecurityContext.* calls before the testEJB.* calls in your Servlet.java. I think that might be because of the way SecurityContext is implemented in Soteria - its dependency on EJBContext. I remember discussing this with our EJB experts - that is why suggested changing the order - see the Sept 27th comment. Moving the testEJB calls after Web and SecurityContext in the Servlet.java seems to work fine.
 
Regarding the @RolesAllowed, this looks like how the EJBRoleRefPermission is propagated to the JACC provider. If @PermitAll is used instead, the ** roleName is passed in the EJBRoleRefPermission to imply any authenticated user but the JACC provider may not handle ** role. Have to look into this more but @RolesAllowed should work for all app servers.

**Comment by ggam** [comment]
@arkarkala, thanks a lot for the insight!

You're totally right, adding `@RolesAllowed` instead of `@PermitAll` fixes the issue. We'll have to change the SecurityContextImpl order to look at Servlet before EJB, and I'll look at the JACC provider code to see how is it handling "**". I see some different behavior between JACC and non-JACC authorization behavior, but that's another story and I'll open a different issue for that.

I'll try to finish this on the weekend and confirm you everything is working. Thanks again for your time!
