### ISSUE TITLE
The configured features passwordUtilities-1.0 and jpa-2.1 include one or more features that cause the conflict. 

### ISSUE THREAD

**Issue by santiago-ortega** [OpenLiberty/open-liberty#4329]
WebSphere Liberty Profile version: 18.0.0.2
server.xml features:
```
        <feature>appSecurity-2.0</feature>
        <feature>servlet-3.1</feature>
        <feature>jpa-2.1</feature>
        <feature>jaxrs-2.0</feature>
        <feature>jdbc-4.1</feature>
        <feature>localConnector-1.0</feature>
        <feature>jaxb-2.2</feature>
        <feature>jndi-1.0</feature>
        <feature>json-1.0</feature>
        <feature>passwordUtilities-1.0</feature>
```
Error message:
```
7/19/18 10:50:33:192 EDT] 0000001a FeatureManage E   CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.connector.internal-1.6 and com.ibm.websphere.appserver.javax.connector.internal-1.7 cannot be loaded at the same time.  The configured features passwordUtilities-1.0 and jpa-2.1 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
```
Workaround:
Add the jca-1.7 feature
```
                 <feature>appSecurity-2.0</feature>
		<feature>servlet-3.1</feature>
		<feature>jpa-2.1</feature>
		<feature>jaxrs-2.0</feature>
		<feature>jdbc-4.1</feature>
		<feature>localConnector-1.0</feature>
		<feature>jaxb-2.2</feature>
		<feature>jndi-1.0</feature>
		<feature>json-1.0</feature>
		<feature>passwordUtilities-1.0</feature>
		<feature>jca-1.7</feature>
```

**Comment by dazey3** [comment]
Is the issue here the conflict between JPA-2.1's javax.transaction dependency:

https://github.com/OpenLiberty/open-liberty/blob/57b0b64211cd2e3626919c9d32a792c6a3e136e5/dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.1/com.ibm.websphere.appserver.jpa-2.1.feature#L226

and passwordUtilities javax.transaction dependency:

https://github.com/OpenLiberty/open-liberty/blob/57b0b64211cd2e3626919c9d32a792c6a3e136e5/dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.0/com.ibm.websphere.appserver.passwordUtilities-1.0.feature#L13

The `ibm.tolerates` makes it look like it should work, but if you look at the transaction 1.1 & 1.2 features:

https://github.com/OpenLiberty/open-liberty/blob/57b0b64211cd2e3626919c9d32a792c6a3e136e5/dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.1.feature#L18

will conflict with:

https://github.com/OpenLiberty/open-liberty/blob/57b0b64211cd2e3626919c9d32a792c6a3e136e5/dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.2.feature#L17

when they both try to load, right?

**Comment by aguibert** [comment]
Here is the conflicting feature chain:

```
com.ibm.websphere.appserver.passwordUtilities-1.0 
    -> com.ibm.websphere.appserver.javax.connector-1.6 
        -> com.ibm.websphere.appserver.javax.connector.internal-1.6
com.ibm.websphere.appserver.jpa-2.1 
    -> com.ibm.websphere.appserver.transaction-1.2 
        -> com.ibm.websphere.appserver.javax.connector.internal-1.7
```

When I test out this feature list in a Liberty image that has all features installed already, it works fine.  However, when we start with a smaller image and use installUtility to add extra features, the `jca-1.7` feature never gets downloaded (since `installUtility` doesn't take tolerated features into account).

**Comment by Azquelt** [comment]
I just recently rewrote the repository resolver to use the same logic for resolving features as the kernel resolver used at runtime, so it should now be possible to have install utility handle this case properly, as long as it knows the full list of features used in the server.

I.e. we could use this logic when the user passes a server.xml to `installUtility` but I wouldn't want to change the logic used when they just give a bunch of features on the command line.

**Comment by NottyCode** [comment]
Given installUtility is not in Open Liberty, but the commercial WebSphere Liberty product I'm going to close this bug since it can't be fixed here. It is a known valid bug against WebSphere Liberty, but I would recommend following the the IBM product support route to report problems in WebSphere Liberty.
