### ISSUE TITLE
Allow filling existing messages.log/trace.log files before rolling

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/open-liberty#4364]
See https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=112257

**Comment by jhanders34** [comment]
Interesting issue and pull request.  Not sure if we want to change the default behavior or not.  Usually options are not done as JVM arguments, but as server.xml options for a particular feature.  I assume we should add something to the logging stanza.  Maybe that isn't possible because this is so early in the code.  Not sure.

**Comment by kgibm** [comment]
Available since Liberty 18.0.0.4 using `com.ibm.ws.logging.newLogsOnStart=false` in bootstrap.properties
