### ISSUE TITLE
APSFOUND-18: Liberty shutdown improvements

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#4464]
Liberty shutdown currently has a quiesce feature, but it doesn't do what one would expect a quiesce feature to do. We need to ensure that sources of incoming work are shutdown and that all existing work is allowed to complete.

**Comment by gkwan-ibm** [comment]
**Serviceability Approval Comment** - Please answer the following questions for serviceability approval (note that this is a new approval step -- comments welcome on how to improve it):

1.  WAD -- does the WAD identify the most likely problems customers will see and identify how the feature will enable them to diagnose and solve those problems without resorting to raising a PMR?  Have these issues been addressed in the implementation?

2.  Test and Demo -- As part of the new serviceability process we're asking feature teams to test and analyze common problem paths for serviceability and demo those problem paths to someone not involved in the development of the feature (eg. L2, test team, or another development team).  
a) What problem paths were tested and demonstrated? 
b) Who did you demo to?
c) Do the people you demo'd to agree that the serviceability of the demonstrated problem scenarios is sufficient to avoid PMRs for any problems customers are likely to encounter, or that L2 should be able to quickly address those problems without need to engage L3?

3.  SVT -- SVT team is often the first team to try new features and often encounters problems setting up and using them.  Note that we're not expecting SVT to do full serviceability testing -- just to sign-off on the serviceability of the problem paths they encountered.
a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  

4.  Queues -- Which L2 / L3 queues will handle PMRs for this feature? Do the respective L2 / L3 teams know they are supporting it?

**Comment by gscottj** [comment]
List of focal points:

Area	Focal Point

Accessibility	Scott Johnston

Globalization/TVT	 ??? 

Legal 	Cass Tucker

WDT 	Leonard Theivendra

FAT	Kevin Smith

IEA/STE/FFW	Swati Kasundra

ID	Brandy Gantt

SVT / CPT	Chris Regan / Brian Hanczaryk

CTS	Scott Highbarger

Performance	Tim Pickett

Serviceability	Don Bourne

Launch Readiness	Dave Sudlik

WAD Approvals	Alasdair Nottingham


Accessibility Focal Point tab in Liberty Dashboard:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.dashboard.viewDashboard&team=Release%20Management/Liberty%20Details&tab=_37


(Atosa) For your reference, I have included the URL for your 2Q17 Feature approval in the table below.  Ping me in case you have any question. 
Focal Point Team Name	Query URL

SVT	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_8gv-kBAGEeecGqTDYw5OVQ

Performance	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_p1abEAXlEeeSkN-EYru4Fg

CTS	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_1CuoEAXlEeeSkN-EYru4Fg

Accessibility	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_9KZSwAXlEeeSkN-EYru4Fg

Translation/TVT	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_jKQKoAXlEeeSkN-EYru4Fg

ID	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_FYKa4AXlEeeSkN-EYru4Fg

Legal	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_4UE1EAj7EeeGlJ-iNH2r2Q
	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_tv5wIAXkEeeSkN-EYru4Fg

STE	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_IfgJ0AXmEeeSkN-EYru4Fg

FATs	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_Hn5pgJezEeaB9rIOFI9Cfw

Serviceability	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_cG41kAXlEeeSkN-EYru4Fg

WDT	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_EIJvEAXmEeeSkN-EYru4Fg

Blog	https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.runSavedQuery&id=_mrdPIAKFEeeSkN-EYru4Fg

Accessibility Approval already granted: 
Accessibility focal point approval has already been granted. Why is there a new request for approval?

Accessibility Requirements for Feature Approval: 
Does this feature have an end-user user interface?
If so, has the UI been tested for accessibility compliance requirements? 

IBM Accessibility Checklist v7.0 (http://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)

  For instance, see the Web Accessibility Checklist 5.2  -  http://w3-03.ibm.com/able/devtest/web.html
  For instance, see the Web Accessibility Checklist 6.1 - http://w3-03.ibm.com/able/devtest/ci162/accessibility_checklist_web.html
  For instance, see the Software Checklist 3.6.1 -  http://w3-03.ibm.com/able/devtest/software_v3.6.1.html
  For instance, see the CLI Software Checklist 3.6.1 - http://w3-03.ibm.com/able/devtest/swclicheck.html
  For instance, see the Software Checklist 6.0 -  http://w3-03.ibm.com/able/devtest/ci162/accessibility_checklist.html
  For instance, see the CLI Software Checklist 6.0 - https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/Wa7b684534a33_4971_b961_4529f9ad4a2e/page/CLI%20guidelines%20and%20sample%20checklist
  For instance, see the Documentation Checklist 2.1 (*.txt, *.log, *.doc, *.pdf, etc...) - http://w3-03.ibm.com/able/devtest/doccheck.html
  For instance, see the Doc for Web Checklist 1.2 (html, css, js, javadoc, etc...) - http://w3-03.ibm.com/able/devtest/docwebcheck.html
  For instance, see the Doc for Web Checklist 6.1 (html, css, js, javadoc, etc...) - http://w3-03.ibm.com/able/devtest/ci162/accessibility_checklist_web.html


General Accessibility Questions:
Based on the description, I am unable to tell whether this feature has any end-user user interfaces (i.e., Web, CLI, Software, Documentation). 
If so, have the UIs been tested for accessibility compliance requirements?
  For instance, see the Accessibility Checklist 7.0 (http://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
  For instance, see the Web Accessibility Checklist 6.1 - http://w3-03.ibm.com/able/devtest/ci162/accessibility_checklist_web.html or the Software Checklist 6.0 -  http://w3-03.ibm.com/able/devtest/ci162/accessibility_checklist.html
  For instance, see the Web Accessibility Checklist 5.2  -  http://w3-03.ibm.com/able/devtest/web.html or the Software Checklist 3.6.1 -  http://w3-03.ibm.com/able/devtest/software_v3.6.1.html

Generate Output?  
Does this feature generate output that has an end-user user interface?
If so, the output generated by this feature must also be tested for accessibility compliance. For generated output, it is important to ensure that the end user (the person providing input to the feature for its generated output) has an opportunity to make the user interface accessibility compliant, even if we don't require that they do so.  For instance, if the user can include a picture in a generated web UI, the picture is supposed to have alternative text that describes the content of the image. For the picture to pass accessibility requirements, the user should have an opportunity to add alternative text. Accessibility testing would fail if the user does not have opportunity to add alternative text to the image they include in the web UI. However, accessibility would still pass if the user omits the alternative text in their generated text (because they had the opportunity to do so). And, accessibility would still pass if the user misrepresents the content of the image (e.g., provides alternative text for an image of an apple, but the image is actually an banana). 

To meet accessibility compliance, all user interfaces provided in or created by this feature must be tested for accessibility compliance against the requirements listed in the Web Accessibility Checklist - https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html

Accessibility Verification Testing: 
Accessibility Verification Testing (AVT) of web interfaces requires three types of testing
AVT-1 Automated Syntax Checking using Rational Policy Tester  (which is easiest to use as the Dynamic Assessment Plug-in for Firefox )
AVT-2 Manual testing  with assorted tools and keyboard only usage
AVT-3 Screen reader testing  with JAWS screen reader  (IBM has a site license, so let me know if you need that the information on how to install and get a license for testing)

If any of the required Accessibility Verification Testing (AVT)  demonstrates accessibility compliance limitations, then these issues must be resolved before it can be released. Otherwise, the whole Liberty offering will have to request a deviation which must be approved by our General Manager (Denis Kennelly). 

Feature has a GUI or CLI and must go through AVT 
Based on the description, this feature seems to need a user interface (either GUI and/or CLI). As such, those user interfaces must be tested against accessibility compliance requirements.
To meet accessibility compliance, all user interfaces provided in or created by this feature must be tested for accessibility compliance against the requirements listed in the Accessibility Compliance Checklists. For instance, see the Accessibility Checklist v7.0 https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html

Based on the description, this feature does have a CLI associated with it. The CLI must be tested against accessibility compliance requirements. Generally speaking, CLI accessibility testing is very basic. And, as long as we are not changing the basic functionality provided by the operating system, then accessibility for CLI should not be a problem.

Verify that the CLI meets the accessibility compliance requirements as defined in the CLI Software Accessibility Checklist .
https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/Wa7b684534a33_4971_b961_4529f9ad4a2e/page/CLI%20guidelines%20and%20sample%20checklist

Based on the description, I am unable to tell whether this feature has any end-user user interfaces (i.e., Web, CLI, Software, Documentation). If so, have the UIs been tested for accessibility compliance requirements? See IBM Accessibility Checklist v7.0 (http://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)

Additionally, if there are any updates or changes made to the javadocs for using this feature, those javadoc files also must be tested to comply with accessibility compliance requirements. Javadocs are provided in html format, and therefore should be tested against the Web checklist.

Feature is for a Open Source, Sample, Demo or otherwise made freely available to the public
Accessibility Approval Comment: 
If this feature and its supporting materials (guides, videos, samples) are no charge, then accessibility testing still needs to be done but the records and results of those tests do not need to be tracking as part of a product release or in the IBM Accessibility Compliance System (ACS). Instead, the testing and results need only be documented within our own tracking systems (such as RTC or GHE) for internal verification purposes. 

In contrast, if this feature is included in a purchasable offering (one which has a PID), then the accessibility test results need to be included as a component of the product offering. As such, all efforts need to be made to ensure the feature and supporting materials satisfy all checkpoint requirements so avoid needing to get an accessibility compliance deviation approved by our GM. 

For Accessibility Approval, please confirm that this feature is being made freely available to consumers and that testing of any or all supporting materials has been tested for accessibility compliance. 

As previous stated, because the materials are being made freely available through the open liberty initiative means that we do not have to record the results of accessibility tests with the rest of the accessibility test results for WebSphere Liberty itself. However, please keep in mind this that does not excuse us from making our products accessible and testing its accessibility. We still need to be good global citizens and make all our deliverables available to all users, including those with disabilities. I leave it to you and the ID team ensure the right things happen for our clients.


Feature does not have a GUI or CLI
Accessibility Approval Comment:  
Based on the description provided, it appears that this feature does not have any end-user user interfaces that require accessibility compliance testing. If this assumption is not correct, then let me know that required accessibility verification testing of the UI will be performed before it is shipped and what are the results from those tests.

**Comment by gscottj** [comment]
Accessibility Approval Comment:  
Based on the description provided, it appears that this feature does not have any end-user user interfaces that require accessibility compliance testing. If this assumption is not correct, then let me know that required accessibility verification testing of the UI will be performed before it is shipped and what are the results from those tests.

**Comment by brenthdaniel** [comment]
@gkwan-ibm 

1) Yes, improving serviceability is one of the goals of this feature and that is indicated in the WAD. 
2) We have not yet demoed this to another team. 
3) SVT agreed that existing testing was sufficient for this. 
4) Any issues would likely go to WASADM. This would not be different than today, so there's no need to alert them. L3 would be handled by LL3KRN.

**Comment by brenthdaniel** [comment]
Feature test summary: #4635

**Comment by gkwan-ibm** [comment]
@brenthdaniel would you point me to the serviceability slide(s) of the WAD?

**Comment by brenthdaniel** [comment]
@gkwan-ibm slide 19 here: https://ibm.box.com/s/3ejxp2a5nuv5lt17u3428kf6fp739g2f

(Note to others, the link is only accessible to IBM employees)

**Comment by bsbyrd1** [comment]
Approved ID, as no ID is required for this feature.

**Comment by brenthdaniel** [comment]
After talking this over with Alasdair, we agreed this needs more time in the build to flush out intermittent issues in other components before including it in a release. I'm going to move this to 4Q, revert the existing changes and deliver them again after the clone next week.

**Comment by olendvcook** [comment]
@brenthdaniel Hi,

I stumbled across this while digging into a build break we got while this was in. High level TLDR: We had a resource that is being removed currently by ServerQuiesceListener, when PauseableComponentQuiesceListener existed it causes us to double dip, try to remove it twice, and throw an error. IMO, when/if PauseableComponentQuiesceListener is readded, it shouldn't just call .pause(), or needs to pass something on to the components because some might want to do different things based on a regular pause, or a server shutdown. Before I noticed this class was gone, I was scratching my head around trying to figure out how to tell if the pause was called because of a true, mid server run pause, or a server quiesce.

**Comment by brenthdaniel** [comment]
@olendvcook 
Hi, 
Thanks for the information. I don't think we want to change the design of PauseableComponents to include a reason for the pause. I think before doing that we would just remove the PauseableComponentQuiesceListener and make sure all pauseable components did something similar to pause() in serverStopping(). 

I think that in general components that implement both Pauseable and QuiesceLIstener should be able to handle situations like this, probably by keeping some state variable or just checking to see if a resource is nulled out.

**Comment by atosak** [comment]
@brenthdaniel  please make sure the required approvals are in place for this feature. Some are still missing.

**Comment by marikaj123** [comment]
According to Brent translation is complete and is in Master branch.

**Comment by sabolo** [comment]
I am doing a quick run through of features in advance of the Feature FAT approvals.  At present I am unable to find any links to a WAD, either from this Epic of in the AHA feature.  Please can you ensure there are links to the WAD in the top level description of this Epic.  Many thanks

**Comment by sabolo** [comment]
Additionally, could you confirm that code and FAT are fully complete and the feature is ready to close out?  Many thanks

**Comment by brenthdaniel** [comment]
The WAD is available here: 
https://ibm.box.com/s/3ejxp2a5nuv5lt17u3428kf6fp739g2f

(Again, for others reading this, this link is not accessible to non-IBM employees)

The code and FAT are fully complete and the feature is ready to close out. The feature test summary is located here: 
https://github.com/OpenLiberty/open-liberty/issues/4635

**Comment by donbourne** [comment]
@brenthdaniel for serviceability approval, can you please give more detail on question 3?  It's not just asking if SVT tested it -- more focused on what they thought of the overall likelihood of it causing PMRs.

a) Who conducted SVT tests for this feature?
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?

**Comment by brenthdaniel** [comment]
@donbourne I don't know that I can answer those questions for them. @hanczaryk ?

**Comment by hanczaryk** [comment]
@donbourne 
a) Who conducted SVT tests for this feature?  Brian Hanczaryk
b) Do they agree that the serviceability of the problems they encountered is sufficient to avoid PMRs, or that L2 should be able to quickly address those problems without need to engage L3?  Yes, I agree that serviceability of any problems encountered were sufficient.

**Comment by brenthdaniel** [comment]
Per offline discussion, serviceability approval is probably not required for this feature.

**Comment by donbourne** [comment]
Thanks @hanczaryk !

**Comment by marikaj123** [comment]
STE file is uploaded to https://ibm.box.com/s/yed0mqne01a6tp7c3oljsucs7w3ho0gj
