### ISSUE TITLE
Improve TCK output from the POV of the build monitor tool

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#4518]
```
 public static int runTCKMvnCmd(LibertyServer server, String bucketName, String testName, Map<String, String> environmentVariables) throws Exception {
        if (!init) {
            init(server);
        }
        // Everything under autoFVT/results is collected from the child build machine
        int rc = runCmd(MvnUtils.mvnCliTckRoot, MvnUtils.tckRunnerDir, mvnOutput, environmentVariables);
        String failingTestsList = postProcessTestNgResults();
        // mvn returns 0 if all surefire tests pass and -1 otherwise - this Assert is enough to mark the build as having failed
        // the TCK regression
        Assert.assertEquals("In " + bucketName + ":" + testName + " the following tests failed: [" + failingTestsList + "].\n"
                            + "The TCK has thus returned non-zero return code of: "
                            + rc +
                            ".\nThis indicates test failure, \nsee: ...autoFVT/results/" + MvnUtils.mvnOutputFilename +
                            " \nand ...autoFVT/results/tck/surefire-reports/index.html for more details", 0, rc);
        return rc;
    }
```
Make different test case failures look the same.

**Comment by hutchig** [comment]
^^^ sylvaing@uk.ibm.com
Make the  launchConfigTck() @Test only fail if there are no results of any kind (PASS or FAIL)

**Comment by SylvainGarcon** [comment]
So the problem here from the BM tool is that we match stacktraces to form groups. In the current format, the microprofile TCK test outputs upon failure something like
```
junit.framework.AssertionFailedError: 2018-07-26-09:02:53:041 In com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck:class com.ibm.ws.microprofile.faulttolerance.tck.FaultToleranceTck11Launcher:launchFaultTolerance11TCK the following tests failed: [ testClassLevelRetryMaxDuration].
The TCK has thus returned non-zero return code of: 1.
This indicates test failure 
```
with only the bit in [ ] changing for different test failures. since these differences constitute a minority of the overall stacktrace, different failures can get matched to the same group, and so multiple problems may be marked against the same work item. This is not useful for debug. For better separation of issues, it would be good if the stacktrace of the (first) failing test could be forwarded through, or failing that removing a good portion of the current output which is always the same no matter the failure would hopefully mean that independent issues are grouped independently. This would help build monitors identify defects/issues more accurately, to provide them in a more helpful state to those of you who work in this area.
Please feel free to ask myself or any of the CSI team more about this as I am not entirely sure how well I've explained this.

**Comment by tevans78** [comment]
Closing as duplicate
