### ISSUE TITLE
The ssl-1.0 / transportSecurity-1.0 feature should notify user when no available SSL configuration is present

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/open-liberty#474]
It is possible to get into a situation where the server appears to be configured for SSL/TLS but no SSL/TLS port opens. In this particular case, it is because the default configuration is used, but no defaultKeyStore is provided.

I'd like to proposed that when the default configuration is used:

**dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml**
`<sslDefault sslRef="defaultSSLConfig" />`

**dev/com.ibm.ws.ssl/resources/OSGI-INF/wlp/defaultInstances.xml**
`<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" />`

That an audit message is issued when the expected defaultKeyStore is not present that we print a clear warning message on how to resolve, something like this:

The default SSL configuration expects a <keyStore> element with an ID of {0} and a password. The {0} <keyStore> element is missing. Either define the missing element: `<keyStore id="{0}" password="..." />` or change the default SSL configuration to use an existing keystore: `<ssl id="defaultSSLConfig" keyStoreRef="newKeyStore" />`.

**Comment by SueBayliss** [comment]
Can the CWPKI0817A message be enhanced to make it clear that this is not necessarily an error.  
For example, the use case when the ssl Liberty feature is loaded implicitly by another feature, (so user may not have choice over loading it), but they do not require SSL and intentionally do not configure it.

When we saw the message, we were concerned it was an error (even though it was an Audit message) and had not appreciated that the SSL initialization was being attempted because we had (implicitly) loaded the ssl feature. So if improved words, could clarify those things that would be good. 

1. Suggestion to update the message text: 
- Add " If SSL is not required, this message can be ignored. If SSL is required", for example:
"CWPKI0817A: The default SSL configuration expects a <keyStore> element with an id value of defaultKeyStore, and a password. The defaultKeyStore <keyStore> element is missing, or the password is not specified. **If SSL is not required, this message can be ignored. If SSL is required, e**ither define the missing element: <keyStore id="defaultKeyStore" password="yourpassword" />, or change the default SSL configuration to use an existing keystore. See the following example: <ssl id="defaultSSLConfig" keyStoreRef="newKeyStore" />."

2. Suggestion to update the KC documentation for message: 
(Based on current content in WebSphere Application Server Liberty Core...Messages > com.ibm.ws.ssl.resources.ssl > CWPKI0817A https://www.ibm.com/support/knowledgecenter/en/SSD28V_9.0.0/com.ibm.websphere.messages.liberty.doc/com.ibm.ws.ssl.resources.ssl.html)

Explanation: **SSL initialization has been attempted because the ssl feature has been loaded. The initialization could not complete, because the default SSL configuration expects a keystore element with the specified id value and a password. The keyStore element is missing, or the password is not specified.**
Action: **If SSL is not required, this message can be ignored. If SSL is required, review the configuration and either add the missing keystore, or change the default SSL configuration to use a different keystore.**

**Comment by barecode** [comment]
@SueBayliss thanks for the improvements Sue! I've created PR #2129 created to resolve.

**Comment by barecode** [comment]
Considering this issue closed, thanks!
