### ISSUE TITLE
Deploying Liberty+Spring Boot uber jar to dropins/spring fails

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/open-liberty#5050]
Now that Boost supports producing a Liberty uber jar, we should support deploying that uber jar directly to Liberty via dropins/spring or `<springBootApplication/>`.

Using the following command:
`mvn package io.openliberty.boost:boost-maven-plugin:0.1:package`

I can produce a Liberty uber jar. This JAR behaves like a Spring Boot uber jar - I can run it with `java -jar`. However, I can not deploy this Liberty uber jar via the dropins/spring folder. It results in the following error:

[INFO] [ERROR   ] CWWKZ0002E: An exception occurred while starting the application spring-petclinic-2.0.0.BUILD-SNAPSHOT. The exception message was: java.lang.IllegalArgumentException: CWWKC0257E: The Spring Boot application META-INF/MANIFEST.MF file must specify a Start-Class header.

It is reasonable to expect that developers will use the Liberty uber jar, give that uber jar to their operations team (if they're in that model) and the ops team will try to deploy the uber jar to a Liberty server. This is possible with the Spring Boot uber jar (with Tomcat or Jetty), but not in the Liberty uber jar case.

We should handle deploying Liberty uber jars via dropins/spring or `<springBootApplication/>`.

**Comment by scottkurz** [comment]
Is there any doc needed about what parts of the embedded application get used in the environment of the server we're deploying this uber JAR to, or is it obvious?    E.g. if I have an 18002 uber JAR and deploy to an 18003 server, I would personally think it's obvious that the 18002 OL runtime is effectively discarded and we use the 18003 runtime of the server we deploy to.  

Is there any other part of the SpringBoot app that we might have a conflict where we have to make a decision to get some piece of the app from the Uber JAR we're deploying vs. the runtime of the deployed-to-server?

**Comment by barecode** [comment]
I think its obvious, in so far as the way we deploy a Spring Boot app today (with Tomcat) is that we discard the embedded app server. I don't have an issue documenting what happens, I just don't think its critical.

**Comment by tjwatson** [comment]
One concern we have to keep in mind is that the Liberty uber JAR will contain a pre-thinned application.  So we will not have the original FAT Spring Boot JAR around to thin with the current version of Liberty be used.

If the Liberty uber JARed application was thinned at some point in time using the latest release (e.g. 18.0.0.3) then the Liberty uber JAR will contain 18.0.0.3 as well as the thin application + lib.index.cache that were created by the springBootUtility from 18.0.0.3.  Moving forward we are going to have to ensure that future versions of Liberty will always be able to understand the formats used by previous versions of the liberty springBootUtility.  If we change the format for some reason (enhancements or performance reasons etc) we must be able to read the old format because that old format may be used by one of these Liberty uber JARs.  This is because for this scenario to work we are going to have to use the already thinned application and lib.index.cache as-is and throw away the rest of the contents of the Liberty uber JAR at runtime.

**Comment by tjwatson** [comment]
Everything I mentioned in the previous comment likely already applies to the zero migration promise.  Using a server configuration that has a pre-thinned application must continue to work without requiring re-thinning the application using the latest springBootUtility.

**Comment by tjwatson** [comment]
I'm going to move this over to Anjum to review and finish up the work I have done so far on this.  Anjum, can you please take over my branch at https://github.com/tjwatson/open-liberty/tree/handleLibertyUberJar

I think it covers the basics, but we need to add some error messages.  I also haven't started a real pull request or done any builds.

**Comment by anjumfatima90** [comment]
Yes, I will work on it asap.

**Comment by tjwatson** [comment]
This was fixed in 18.0.0.4
