### ISSUE TITLE
Pass cmd line args for Spring Boot app on Open Liberty

### ISSUE THREAD

**Issue by Hemankita** [OpenLiberty/open-liberty#5430]
Using Liberty Boost plugin to get my Spring Boot application onto Open Liberty.

I am trying to pass the arguments to jar file from command line.

For Spring Boot, it works if I run `java -jar build/libs/micro-inventory-0.0.1.jar --spring.datasource.url=${URL} --spring.datasource.username=${USERNAME} --spring.datasource.password=${PASSWORD} --spring.datasource.port=${PORT}`

How does I do this if I am using Open Liberty in place of Tomcat.

For Open Liberty, I tried running the below commands and these doesnot accept the values from the command line. The app is still using the environment variables that comes with the `application.yml` 

`java -jar target/liberty-inventory-spring-0.1-SNAPSHOT.jar --spring.datasource.url=${URL} --spring.datasource.username=${USERNAME} --spring.datasource.password=${PASSWORD} --spring.datasource.port=${PORT}`
`java -jar target/liberty-inventory-spring-0.1-SNAPSHOT.jar -Dspring.datasource.url=${URL} -Dspring.datasource.username=${USERNAME} -Dspring.datasource.password=${PASSWORD} -Dspring.datasource.port=${PORT}`

**Comment by aguibert** [comment]
related to the solution being discussed in https://github.com/OpenLiberty/open-liberty/issues/1610

**Comment by yeekangc** [comment]
Thank you, @aguibert.  So, this isn't so much with Spring support itself but support for properties from command line in Liberty.

@tjwatson

**Comment by aguibert** [comment]
Initially #1610 was just for passing in system properties, but the final proposed resolution at this time (https://github.com/OpenLiberty/open-liberty/issues/1610#issuecomment-427832871) accounts for both system properties and passing main args to a Spring app.

**Comment by yeekangc** [comment]
Do we have an outlook for #1610?  It was targeted for a milestone that ended on Oct 5?

**Comment by tevans78** [comment]
There is now a feature on the backlog for the spring part, no outlook though

**Comment by tjwatson** [comment]
One thing to note: if passing java args for system properties (e.g. `-Dspring.datasource.url=${URL}`) I think that must come before the `-jar ...` option.  Otherwise they get treated as arguments to pass to `main(String[] args)` and are not processed by java as system properties.

With that said using the `-Dspring.datasource.url=${URL}` approach still may not work because of the way the liberty uber JAR launcher has to fork a java process in some conditions.  For example, if being launched with a JRE instead of a JDK.  In this case I do not expect the system properties being set with `-D` will make it over to the forked java process.

**Comment by tjwatson** [comment]
This is fixed in 18.0.0.4.
