### ISSUE TITLE
mpJwt-1.x feature must support multiple token issuers

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#5433]
In servers to server (n to 1) trusted communications, the initiators can self-issue JWT to impersonate users. Each initiating server can be considered as an issuer with its own signing key. The mpJwt-1.x feature in recipient need configuration options to resolve the corresponding signature verification key for the issuer identified in JWT payload.

**Comment by danpfe** [comment]
Agree, not only for impersonating but also when an organisation migrates to another OIDC-issuer and there is a time where you can receive acceptable tokens from the old and the new issuer. Already tried creating new "mpJwt"-elements in the server.xml, but got CWWKS5521E: Too many MicroProfile JWT services [alternativeMpJwtConfig, defaultMpJwtConfig] are qualified to handle the request. Then tried to remove the issuer-attribute altogether, which causes the issuer not to match (empty string vs the issuer in the token). So I +1 this feature request as well ;-)

**Comment by danpfe** [comment]
Hi guys, for completeness I'd like to share my ideas that I already mentioned to @gcharters.

Although I believe I could easily offer a pull-request that allows us to disable issuer-verification (like <mpJwt verifyIssuer="false" ... />) to get past this current problem I feel that the MP-JWT-spec perhaps may be lacking from the perspective of "multi tenancy"-support (i.e. allowing a REST API to be invoked by different clients and thus different JWT issuers).

Since MP-JWT can by spec be configured through MP-Config and in most middleware products through it's custom configuration mechanisms I believe it would be beneficial to extend the spec with new annotations and new config properties.

From the OpenLiberty perspective an idea would be to allow a new childnodes to the mpJwt-element as following:

```xml
<mpJwt id="myConfig" ...>
  <tenants>
    <tenant jwksUri="https://a/keys" issuer="a"/>
    <tenant jwksUri="https://b/keys" issuer="b"/>
  </tenants>
</mpJwt>
```

The aforementioned example would be for static multi-tenancy.

For dynamic multi-tenancy it would be nice if MP-JWT could look for an annotated bean in the application's classpath (as is done with @LoginConfig et cetera), for example

```java
@ApplicationScoped
public class MyTenantProvider implements TenantProvider {
  @Override
  public Collection<Tenant> getTenants() {
    final var tenants = // ... fetch your tenants from somewhere, like the DB
    return tenants;
  }
}
```

Ideally the aforementioned way of fetching tenants should (optionally?) not only be called during startup; if, as seen in the example, we may want to add another tenant during application runtime. An idea here would be to cache the response unless we get a new token containing a tenant (issuer) which we do not know, yet.

Please see this write-up as a very rough draft, as you can see there are no suggestions for a system property structure (such as -Dmp.jwt.tenants...) or as in the dynamic tenant example how often the provider's getTenants should be called (the addition case is I mentioned, but what if we remove a tenant without restarting? We probably don't want to invoke it each time we get a JSON Web Token...)

**Comment by teddyjtorres** [comment]
Thank you. There are several aspects to consider in a multi issuer support and we are currently evaluating this request.

**Comment by danpfe** [comment]
Hi @teddyjtorres,

no problem whatsoever. As I said, my suggestion was purely given as a rough idea around this issue and I can't claim that I have yet thought of every single aspect that would be required to get this to both become a part of the spec and an actual implementation in Liberty.

If you believe any further input from my end would be of any help then don't hesitate to reach out.

/D

**Comment by malincoln** [comment]
This will be resolved by https://github.com/OpenLiberty/open-liberty/issues/8998.
Closing per discussion with @NottyCode and @teddyjtorres.
