### ISSUE TITLE
Feature dependency issue with appSecurity

### ISSUE THREAD

**Issue by Hemankita** [OpenLiberty/open-liberty#5720]
There was a change in Liberty and we had to add appSecurity ourselves. 

Deployed the application on `wlp-webProfile7 18.0.0.3` using Maven. I don't have any errors and it is running fine. But when the same application is deployed on `wlp-webProfile8 18.0.0.3` using Maven, I see the below error.
 
```
[ERROR   ] CWWKS5604E: A JsonWebToken Principal can't be injected because one is not available. Protect the requesting resource so authentication occurs before the resource is accessed.
```
 
This error is resolved by adding `appSecurity-2.0` in server.xml.

How are these two different and why should we add the `appSecurity-2.0` here?

**Comment by aguibert** [comment]
hi @Hemankita, can you please include the feature list in your server.xml?

**Comment by Hemankita** [comment]
```
    <featureManager>
        <feature>microprofile-1.3</feature>
        <feature>usr:opentracingZipkin-0.30</feature>
    </featureManager>
```

**Comment by yeekangc** [comment]
FYI, @chunlongliang-ibm.

**Comment by NottyCode** [comment]
By using the webProfile8 zip file of Liberty you have automatically upgraded all the microProfile features from EE 7 to EE8 because the EE 8 features are all that is available.

In EE 7 the JAX-RS features were enabling application security, which wasn't intended so the EE 8 version doesn't do this (we fixed it in EE 8 to not break existing deployed apps). 

The problem ends up being that the mpJwt features have a requirement that app security is enabled, but they don't indicate that dependency, which results in errors occurring. @chunlongliang-ibm was going to be fix that.

**Comment by hrstoyanov** [comment]
I got bitten by this nasty issue as well in OL 18.0.0.4, upgrading from OL 18.0.0.1 - had no idea I need to add feature appSecurity-2.0! Thanks for the hint @Hemankita , you saved me hours of frustration! Please fix!
