### ISSUE TITLE
Intermittent VirtualHostMapTest failure

### ISSUE THREAD

**Issue by billw1024** [OpenLiberty/open-liberty#6025]
Some vhost unit tests are failing that have worked for years, and no changes to the tests or vhost code has been made recently.  So for now will comment out these test, and then try to figure out what is the issue.

**Comment by billw1024** [comment]
#link 257655

**Comment by wtlucy** [comment]
The changes I made in PR #3981 affected this test scenario: we now log a message and alert listeners when a context root is added even if there are zero ports associated with the context root.  The failing test - VirtualHostMapTest.testThreadedAddRemoveMultipleVHosts  - assumes that two of the context roots it's working with (/z and /y) will only notify contextRootAdded listeners once.  When this test fails, it's because that a listener for one of those roots was notified more than once.  Before PR #3981 that would never happen, since the /z and /y might have had zero associated ports at the time of addContextRoot() was called; we should now tolerate multiple notifications for those roots.
