### ISSUE TITLE
SRVE0319E Managed Class does not match Bean class with CDI and class inheritance

### ISSUE THREAD

**Issue by kumm** [OpenLiberty/open-liberty#6094]
I try to deploy a war package.
I have a servlet class `A`, and a servlet class `B extends A`.
Servlet class `A` is located in a module without beans.xml, `B` is located in a module with beans.xml `bean-discovery-mode="all"`.

Only `A` servlet is activated by web.xml.
In this case the application is deployed, but servlet `A` is out of work. I get an error on the first request:

> SRVE0319E: For the [Servlet Name] servlet, `A` servlet class was found, but a resource injection failure has occurred. com.ibm.ws.managedobject.ManagedObjectException: Managed Class {`A`} does not match Bean Class {`B`}

After adding `@Vetoed` to class `B` it starts to work properly.
It seems `A` servlet instance is createad as it were a CDI bean with the wrong bean class.

I've encountered the issue in my integration tests, it can be easily reproduced.
After cloning from here: https://github.com/kumm/cdi/tree/wlp
In `vaadin-cdi-itest` module run:
> mvn -Pwlp test -Dtest=SmokeTest#injectionDoesNotHappenWithDisabledCdiServlet

**Comment by Emily-Jiang** [comment]
@benjamin-confino can you take a look at this please?

**Comment by benjamin-confino** [comment]
Hello @kumm 

I attempted to run the integration tests you suggested but it appears I need a vaadin pro licence to do so, which sadly I do not possess. When I looked at the source for your test to try and recreate the test application manually I see that CDIView is annotated `@Route` and I'm not sure what I need to do to mimic the effects of that vaadin class. 

However the good news is that I believe this issue might be fixed by #5883. I was going to use the tests to verify if that is correct. Could you please advise me on how to recreate the test without a vaadin pro licence? Alternatively you could run your tests against a compilation of the latest trunk of liberty. 

Regards
Benjamin

**Comment by kumm** [comment]
Sorry about it, I've forgot tests require a vaadin product.
The good news is the whole test suite passes with 2019-01-02_1452 daily build.
Are you still interested in a runnable test? If so, I can create a trimmed one.

**Comment by benjamin-confino** [comment]
That's wonderful news. If it passes there is not need to send me a trimmed build. I've written tests to verify 5883, I just wanted to make sure you were hitting the same issue. 

If you have no objections, may I mark this issue closed?

**Comment by kumm** [comment]
Thanks, of course, I'm closing it.
Just to be sure I'm Going to build from https://github.com/OpenLiberty/open-liberty/commit/432193714b9a869d2d76a20057f5cb7d9acbbcf3 and 1 commit before.

**Comment by benjamin-confino** [comment]
You're welcome, and let If you need anything else.
