### ISSUE TITLE
Filter out embedded server dependencies for Spring Boot 2.1.x

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#6360]
We need to find a better way of filtering so that the thin utility is not affected by the future releases of the embedded servers.

com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java

**Comment by dazavala** [comment]
Currently, the filter within the spring boot utility fails to thin (filter-out) dependency jars for 2.1.x starters because the runtime does not identify the starter type, which renders the filter unable to match the starter dependency jars, and unexpectedly, the runtime stores all to the target lib cache. @tjwatson We can 1) add feature support for springBoot 2.1, 2) add a simple heuristic that defaults the starter type to closest supported version, 3) add static support for 2.1.x starters, or 4) develop a general solution.

**Comment by marikaj123** [comment]
@tjwatson - Can @anjumfatima90 use the last green Release build to test the fix?

**Comment by anjumfatima90** [comment]
The changes have also been verified in https://github.com/OpenLiberty/boost/issues/258.
