### ISSUE TITLE
Beta Blog: MicroProfile Concurrency 1.0 in OpenLiberty #5301

### ISSUE THREAD

**Issue by marikaj123** [OpenLiberty/open-liberty#6568]
Beta Epic: https://github.com/OpenLiberty/open-liberty/issues/5301

**Comment by marikaj123** [comment]
Development progress update

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

   ii. Feature name (eg websockets-1.0)

   iii. Is this a new feature or is it an update to an existing feature for this release?

   iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

g. Attach any images to this work item as .png files.

**Comment by aguibert** [comment]
removing myself from this issue since @njr-11 is providing the content

**Comment by lauracowen** [comment]
Thanks @njr-11 . Re our conversation on Slack, here's the standalone blog post draft: https://github.com/OpenLiberty/blogs/blob/concurrency/drafts/mp-concurrency.adoc so we can promote this initial implementation available in development builds. We can tweet it etc to share it with the developer community.

I'll also use your text above in the summary release announcement blog post and link from there to your standalone post.

**Comment by dbarfield** [comment]
note to whoever (posted by Marika but I am guessing that was posted on behalf of someone ?)

`iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)
I have never been able to answer this question. Can someone provide education on how to determine it?`

I don't know if there is a recommended way but if you look in the SUBSYSTEM.MF for mpConcurrency-1.0.esa you see 
`Subsystem-Localization: OSGI-INF/l10n/com.ibm.websphere.appserver.mpConcurrency-1.0`

**com.ibm.websphere.appserver.mpConcurrency-1.0.esa** (esa is just added on it doesn't get displayed) is what we are looking for.

**Comment by alexsm82** [comment]
When I read that I wasn't entirely sure if it was asking which features were affected by the changes or which feature files were changed.  I asked Nathan R (who I believe is the other person you are referring to) and he said he always put not sure and had never heard anything so that's what I did as well.  Maybe updating the example to something like: "(eg: if you update the transport security feature - com.ibm.websphere.appserver.transportSecurity-1.0.esa)".

**Comment by pnickoll** [comment]
The file that contains the subsystem manifest (which contains the string `OSGI-INF/l10n/com.ibm.websphere.appserver.mpConcurrency-1.0`) is com.ibm.websphere.appserver.mpConcurrency-1.0.esa. Rather than dig into the file, the filename itself should suffice. Although I'm not sure the filename has to match the fully qualified name (but I believe it does atm).

If we do dig into the Subsystem manifest, the localization field is just where the translated files are kept, which could change and is not tied down to the feature name (it happens to use it atm though). The Subsystem-SymbolicName field contains the fully qualified name.

**Comment by pnickoll** [comment]
From a source project I think you'd find the symbolic name (and you may need bVersion too) in the bnd file for Open Liberty features.
