### ISSUE TITLE
JAX-RS security without a web.xml

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#68]
Currently, in `jaxrs-2.0` and `jaxrs-2.1` with the `appSecurity-2.0` feature enabled, it is possible for a user to add `@DenyAll`, `@PermitAll`, and `@RolesAllowed` annotations to JAX-RS resources and expect security (authentication and authorization), but only if the user has also provided a web.xml that defines the security constraints for the URIs exposed by the resources.  The security constraints in the web.xml is required for authentication.  Only when the user is authenticated would the `@RolesAllowed` annotation be of any use for authorization - if the user is not authenticated, then that user is most likely not in any roles.

This issue should address this gap by distinguishing between a user that is unauthenticated (in which case a 401 should be returned so that the client could retry the request with the proper credentials) and one that is unauthorized (in which case a 403 should be returned).

**Comment by arjantijms** [comment]
This is indeed somewhat of a gap in the Java EE security machinery, and one that I personally hope we can address better in a next version of JSR 375 / Java EE Security. But it's not totally unaddressed.

I believe that the container upon encountering a JAX-RS resource (method) annotated with an `@RolesAllowed`, and where the caller is unauthenticated, should not immediately send a 401, but should call `HttpServletRequest.authenticate()`. This will call the authentication mechanism again, but now with authentication being mandatory. 

Depending on the authentication mechanism in question, it can now decide to return a 401, or, perhaps, make use of a credential that was in the request all along but wasn't used before since authentication wasn't mandatory, or do whatever else makes sense for the specific type of authentication mechanism being used.

The addition of `HttpServletRequest.authenticate()` into the Servlet spec was done with this very use case in mind, but eventually the Java EE spec should be more clear about this.

**Comment by andymc12** [comment]
@arjantijms Thanks for the feedback.  I implemented your proposed solution in PR #73.  I've already merged these changes, but if you see anything obviously wrong (or something that we could improve), please let me know.

Thanks again for the feedback!  Andy
