### ISSUE TITLE
New-issue template text demands actions not possible for all users

### ISSUE THREAD

**Issue by johnarwe** [OpenLiberty/open-liberty#6921]
The OpenLiberty Issue template, paragraph 3 says:

> If this issue is to raise a problem found in released code, or to document a problem
that **could** be seen in a previous full release (17.0.0.4, 18.0.0.1, etc. not a daily driver)
it MUST be labelled with “release bug” 

Labeling an issue requires write access to the repo, per GitHub's help https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests .

The template goes on to make scary-sounding statements that I read to imply issues not so labelled will never be integrated.  Most users will not have write access to the repo, so anyone who reads & believes the template but does not already have repo-write is effectively being discouraged from opening the issue (by raising the effort bar), which is probably not the desired effect in an open community.

**Comment by garypicher** [comment]
Hi John, I agree with you that the text is misleading.  Note that the intention was definitely NOT to imply that issues without "release bug" won't be fixed.  We fix non release bug issues all of the time.  The purpose of the label is so that, when a new release is generated, we can .  This way if a user encounters a particular issue when using the product, they can easily tell when it was fixed.

Issues that don't impact a previous release of the product (such as test case fixes, or infrastructure fixes) are still important to fix, but don't need to be labelled in this way.

What I'm going to do is remove the new issue template entirely.  We already have a pull request template that states the same information.  Leaving the template in the pull request makes it clear that the onus for putting "release bug" on the issue is on the fixer of the problem.

Does this address your concern?

**Comment by johnarwe** [comment]
sure; especially since a PR owner would, I assume/not having checked, have sufficient privs to label the PR as the template asks for.
