### ISSUE TITLE
How to do API Discovery in open liberty?

### ISSUE THREAD

**Issue by travatine** [OpenLiberty/open-liberty#6975]
Hi,

With Open Liberty (running on z/OS), how can I do API discovery (i.e. see Swagger annotated REST APIs) if apiDiscovery-1.0 is not available?

(Yes I really am running openLiberty on z/OS, and I'm not asking about the IBM version of liberty.)

Thanks again

**Comment by bpaskin** [comment]
Hi, OpenLiberty does not include the API Discovery feature.  If you want to use that feature, then you need either the paid version of Liberty, or you can include the necessary libraries and configuration with Swagger.  I have an example called [SwaggerExample](https://github.com/bpaskin/JavaExamples). Please read the description since the UI needs to be downloaded and placed in the app.  -Brian

**Comment by aguibert** [comment]
hi @travatine, check out the `mpOpenAPI-1.0` feature, which provides REST API discovery similar to the `apiDiscovery-1.0` feature.

Here is a blog post that talks about it: https://openliberty.io/blog/2018/05/22/microprofile-openapi-intro.html
