### ISSUE TITLE
Investigate possible difference in values between Prometheus and JSON format metrics

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#7440]
per https://github.com/eclipse/microprofile-metrics/issues/320 the value shown in prometheus format from `/metrics` isn't the same value as from JSON format.  

```
prometheus value = 0.000043196000000000005
json value = 43196.0
```
Example endpoint
```
@Path("/")
public class ResourceMeteredTimed {
    @Timed(name = "timed",
            description = "Metrics to monitor the times of timed method. - @Timed",
            unit = MetricUnits.MINUTES,
            absolute = true)
    @GET
    @Path("/timed")
    public Response timed() {
        return Response.ok().build();
    }
}
```

**Comment by jennifer-c** [comment]
It seems that the discrepancy between Prometheus and JSON values is due to how the Timer works, and how it is converted for Prometheus.

One important thing to note is that the current implementation does not factor in units despite being specifiable. All units will return the same results (i.e. there is no difference in using `unit=MetricUnit.MINUTE` vs `unit=MetricUnit.NANOSECOND` in the current implementation)

It seems that the [Timer](https://github.com/eclipse/microprofile-metrics/blob/master/api/src/main/java/org/eclipse/microprofile/metrics/Timer.java) always measures in nanoseconds. Since the JSON metric writer takes the raw values from the timer (without conversion), the JSON mapping will also return the value in nanoseconds. 

In the current implementation of [PrometheusBuilder](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/helper/PrometheusBuilder.java#L69), the conversion factor will convert nanoseconds into seconds (does not take in account other units). Conversion to seconds is expected behaviour per 3.2.8 in the Metrics spec (3.2.9 in the 2.0 spec)

From here, there are a couple of options:
1. Clarify in the spec that the JSON will always display times in nanoseconds and remove the ability to specify the units to be used.
2. In OpenLiberty, convert the units as specified by `units=` for JSON.

**Comment by donbourne** [comment]
Reviewed and discussed in scrum today that option 2 seems to be the most appropriate.
