### ISSUE TITLE
Feature to enable config-based REST endpoints

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#7462]
Under #6509, a REST endpoint for validation is being added that will depend on enablement of restHandler-1.0 (protected feature) along with enablement of the feature that provides the configuration being validated (for example, jdbc-4.3 for dataSource,  jms-2.0 for jmsConnectionFactory, and so forth).

In addition to the the /ibm/api/validation/ endpoint mentioned above, there is also the /ibm/api/config/ REST endpoint, which applies to all config and so would be conditional on just restHandler-1.0.  It is expected that the same pattern will be followed for other configuration-based REST endpoints that are introduced in the future.

The issue to discuss is the users cannot directly enable restHandler-1.0.  They currently need to enable other feature that enables it, such as restConnector-2.0, but in doing so, additional dependencies are brought into the server.  This issue is opened to socialize whether or not this is acceptable or whether another approach should be taken such as promoting restHandler-1.0 to be a public feature.

For comparison, the following is a list of dependencies brought in by
/com.ibm.websphere.appserver.features/visibility/public/restConnector-2.0/com.ibm.websphere.appserver.restConnector-2.0.feature
which are not brought in by
/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.restHandler-1.0.feature

-bundles=com.ibm.ws.filetransfer.routing.archiveExpander, \
 com.ibm.ws.jmx.connector.server.rest, \
 com.ibm.ws.jmx.connector.client.rest, \
 com.ibm.ws.filetransfer, \
 com.ibm.websphere.filetransfer, \
 com.ibm.ws.jmx.request, \
 com.ibm.json4j
-jars=com.ibm.websphere.appserver.api.restConnector; location:=dev/api/ibm/
-files=clients/restConnector.jar, \
 clients/jython/restConnector.py, \
 dev/api/ibm/javadoc/com.ibm.websphere.appserver.api.restConnector_1.3-javadoc.zip, \
 clients/jython/README,

**Comment by NottyCode** [comment]
So general discussion was against having a validator feature since we would then have new features for every new REST API we might ever invent which could get unwieldy. Exposing the restHandler feature is undesirable because it doesn't really help the end user understand what is going on.

Proposal is to look into whether we have introduce a new restConnector-3.0 feature which adds these new API's, and at the same time see if we can remove json-1.0, distributedMpa-1.0 from the list of public dependent features and review once that has been looked into. If we can't create a restConnector-3.0 then overload into restConnector-2.0 makes most sense at this time.

**Comment by njr-11** [comment]
Implementing under #7621
