### ISSUE TITLE
@Traced not working on timer EJB

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#7700]
I have an EJB Timer class like this.  I'd like to using OpenTracing to trace with an explicit span when the timer triggers.  Unfortunately, the @Traced annotation has not effect.

```
@Singleton
@Startup
public class OrderProcessTimer {


    @Schedule(second = "*/10", minute = "*", hour = "*", persistent = false)
    @Traced
    public void processOrder() {
        // do stuff here....
    }

}
```

**Comment by fmhwong** [comment]
@gcharters Can you send me the EAR file and steps on how to reproduce?

Alternatively, you can enable trace for
`com.ibm.ws.microprofile.opentracing.*=all:com.ibm.ws.opentracing.*`

**Comment by fmhwong** [comment]
Is this still an issue?

**Comment by fmhwong** [comment]
From Graham:

Hi Felix, the problem was found when trying to add `@Traced` to this EJB:
https://github.com/gcharters/coffee-book-example/blob/master/coffee-shop/src/main/java/com/example/coffee_shop/control/OrderProcessTimer.java

One the `processOrder` method

**Comment by fmhwong** [comment]
@gcharters In Slack, you said "Yeah, already doing that.  I was trying to get the fallback to show up in the OT flow so you know what path it went down when viewing in OT.  Tom explained why this doesn't work.  It's because the fallback method is on the same bean and so the OT interceptors are not run."

I'm no expert in CDI.  Is this a CDI issue or OT issue?

**Comment by covener** [comment]
I think no impl issue on either side.
IMO since @Traced is "just" an Interceptor binding, it sounds like a limitation / working as intended.

OT would benefit from language like FT, currently the only hint is in an `example` block where @Traced is an InterceptorBinding.

FT: https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/relationship.asciidoc#relationship-to-java-interceptors
```
Fault tolerance interceptors bindings must applied on a bean class or bean class method otherwise it is ignored,

invocation must be business method invocation as defined in CDI specification.
```

Maybe some oppty for FT to generate OT events on these non business method invocations.?

**Comment by fmhwong** [comment]
@tevans78 Do you agree this is a limitation?

**Comment by tevans78** [comment]
Well really this is something that should be clarified by the OT spec. I see no reason why `@Traced` should not work on an EJB timer method. There are clearly technical (implementation) reasons why `@Traced` won't work on a FT fallback method ... but it is still something that a user might expect to work. It might still be possible to implement it, just not in a standard way and maybe not without a OT spec change? @Emily-Jiang might have more thoughts on this.

**Comment by fmhwong** [comment]
@Emily-Jiang Do you have any advice on this issue?

**Comment by fmhwong** [comment]
No activities for almost a year. Please reopen if you still want to pursuit this.
