### ISSUE TITLE
Do features like jacc and jaspic also need the javaeeCompatible-8.0 feature?

### ISSUE THREAD

**Issue by ewhoch** [OpenLiberty/open-liberty#788]
An update under #659 added javaeeCompatible-8.0 to many places, usually ones that already had JavaeeCompatible-7.0.

A question was raised whether this should also be on jaspic and jacc, even though they didn't previously state the javaeeCompatible-7.0 feature. In my opinion it bleeds into a core question of where and why we put those features in.

**Comment by aguibert** [comment]
@ewhoch both the jaspic and jacc features have been around since Java EE 6, and there have not been any new revs of their specs since that time.  So theoretically we could make them tolerate javaeeCompatible 6, 7, and 8, but I don't really see a point in doing so, since it would never have any effect with any combination of features.

**Comment by ewhoch** [comment]
Does that indicate that they aren't part of the javaee-7.0 convenience feature or am i still misunderstanding something?

**Comment by aguibert** [comment]
@ewhoch They are part of the javaee-7.0 convenience feature yes.  And they will also be part of the javaee-8.0 convenience feature (since there is no new rev of the spec in EE8)

**Comment by ewhoch** [comment]
OK. so there would clearly be issues if that was a compatibility problem, so I agree these should be fine as is.
