### ISSUE TITLE
mpHealth 1.0 throws error in some cases

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#8573]
I have an application, microprofile-primitives.war, which works fine.

However, starting in 19.0.0.8, if I change the name to microprofile-primitives-2.2.war, I get the following error when I hit the /health endpoint.

```
ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#microprofile-primitives-2.2#microprofile-primitives-2.2.war
    at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
    at [internal classes]
[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: WEB#microprofile-primitives-2.2#microprofile-primitives-2.2.war
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5051)
    at [internal classes]
Caused by: java.lang.IllegalStateException: WEB#microprofile-primitives-2.2#microprofile-primitives-2.2.war
    at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
    ... 1 more
```

**Comment by pgunapal** [comment]
@jdmcclur as a workaround, can you try changing the name attribute in the application element in your server.xml, to "microprofile-primitives-2.2", instead of "microprofile-primitives", and try accessing the "/health" endpoint again?

The issue happens only for applications where the name attribute is explicitly specified in the server.xml and it does not match the WAR file name. As in this case:
`<application type="war" id="microprofile-primitives" name="microprofile-primitives" location="${shared.app.dir}/webcontainer/microprofile-primitives-2.2.war"/>`

**Comment by jdmcclur** [comment]
@pgunapal - interesting, yes it works fine when I update the name.

**Comment by wraschke** [comment]
#regression
