### ISSUE TITLE
Add PKCE code_challenge_method supported values to discovery 

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#8744]
Discovery should include the values for code_challenge_method that we support.  Those values are:
"plain" and "S256"

**Comment by clarkek123** [comment]
@c00crane, Looking at the OpenID connect discovery specification, I see Section 3. listing the openid connect client metadata that is returned on discovery (https://openid.net/specs/openid-connect-discovery-1_0.html)   I don't see any reference to code_challenge_method.  Is this actually for OIDC and does it belong in discovery metadata for the OIDC provider?  Also, should it be written in terms of "supported_code_challenge_methods" so that it is named consistently with other metadata values reported by discovery.

**Comment by clarkek123** [comment]
It looks like discovery either returns an endpoint or a value with _supported. So we need to decide between the following when supplying this for discovery:  1) code_challenge_method, 2)code_challenge_method_supported or the plural 3) code_challenge_methods_supported.

**Comment by c00crane** [comment]
Use #3
"code_challenge_methods_supported": [ "plain", "S256" ]
