### ISSUE TITLE
FAT Approval Test Summary - APSFOUND-30

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#9020]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by mrsaldana** [comment]
This feature includes a new FAT bucket: com.ibm.ws.transport.http.compression_fat. It makes use of a single servlet and a series of tests that will send requests over to said servlet in order to trigger different scenarios for the compression feature. All testing is automated and will be added to the OL repository as part of the compression beta feature. 

Each test will evaluate the response and look to validate that it is either compressed or not compressed. Unless otherwise stated, the servlet will set the same response payload. The plain text message is known to the tests. As such, when the tests verify that the response is not compressed, the body is expected to match this plain text message. When compressed, the tests will verify that the message is changed and that the response headers include a Content-Encoding header with whatever encoding algorithm is expected. The HTTP channel already contains tests that validate the compression algorithms, so these tests focus on whether or not the expected algorithms are chosen (using the Content-Encoding header) and if the payload is plain text or not.

The following are descriptions for each function and corresponding test:

**_Quality Values - A client signals to the server that it accepts compression through the use of an "Accept-Encoding" header. This header's value is a list of encoding algorithms and optionally a quality value. This value is to be within 0 to 1 (with at most three decimal spaces). 0 means not accepted and 1 being the highest priority. If a quality value is not supplied, then the corresponding encoding algorithm has a quality value of 1._** 

**Test 1: testQValueWeight** - This test will send three requests to a server configured to do compression. 

The first request contains an Accept-Encoding header set to "deflate;q=0.75,gzip;q=0.5". The expected result is for the server to compress using the highest quality value specified by the Accept-Encoding header (in this case, the deflate algorithm). 

The second request reverses the order, sending gzip prior to deflate with the same quality values, "gzip;q=0.5,deflate;q=0.75". Just as before, the response is expected to be compressed under the highest quality value algorithm (deflate). 

The third request contains an Accept-Encoding header set to "identity, deflate;q=0.75". This specifies that while deflate compression is acceptable, the client prefers identity (analogous to no compression). As such, the test expects the response to not be compressed. 

**Test 2: testCompressionFavorsGZIP** - When there are more than one algorithm set to the highest quality value, if one of these algorithms is GZIP, that will be set as the preferred algorithm. This test will send a request with both deflate and gzip set on the Accept-Encoding header. The quality values for both are set to 1. A second request is sent reversing the order to gzip and then deflate. In both cases, the response is expected to be compressed with the gzip algorithm, regardless of order. 

**Test 3: testQValueRange** - This test will ensure the server honors the range of quality values as described by the RFC. A valid quality value is to be within the range of 0-1 with up to 3 decimal spaces. The server covers this by executing a regular expression. A server configured with the <compression> element will receive eight requests to test this regular expression through the use of Accept-Encoding headers with the following quality values defined: A negative quality value (expected not to compress), a quality value larger than intended (q=1.1; expected not to compress), a quality value of 0.1 (expected to compress), a quality value of 0.11 (expected to compress), a quality value of 0.111 (expected to compress), a quality value of 0.1111 (expected to not compress), a quality value of 1.000 (expected to compress), and finally a quality value of 0 (expected to not compress).

**Test 4: testDefaultQValue** - When the quality value is not provided in the Accept-Encoding header, the RFC specifies that the default is considered to be 1. This test will send an Accept-Encoding header with deflate (set to a quality value of 0.999) and gzip with no quality value defined. The test expects the response to be compressed with the gzip algorithm.

Server supported compression algorithms - As of the writing of this bucket, the server supports the gzip, deflate, x-gzip, zlib, and indentity compression algorithms.  If during the parsing of the Accept-Encoding header, there is no server supported algorithm that can be chosen, no compression will occur. 

**Test 5: testNoSupportedCompression** - A request is sent over to a server enabled for compression with an Accept-Encoding header whose value is "MostEfficientCompressionType". Since this is not an algorithm that the server supports, the server will not attempt to compress the response. The test expects a plain text response with no Content-Encoded header.

Regarding Accept-Encoding header parsing - The Accept-Encoding is defined by the RFC to contain a comma delimited list of compression algorithm values. Optionally, a quality value can be provided to each value by appending a semi-colon character followed by a 'q=' and a value ranging from 0-1 (as described previously). If a compression/quality value pair is not properly formatted, it should not be considered for compression.

**Test 6: testMalformedAcceptEncodingHeader** - Five requests are sent over to a server configured to enable compression with incorrectly formatted Accept-Encoding headers. The server is expected to not compress if no valid compression algorithm is parsed from the header. In such cases, the test is expecting a plain text response with no Content-Encoded header. The first request will add more than one semi-colon character "deflate;;q=1". The second request will send a bad quality value: "deflate;qq=1, gzip;q=NOT_A_NUMBER". The third request provides a semi-colon but no quality value to go with it: "deflate;". The fourth request provides a quality value but no compression algorithm: ";q=1". The fifth request sends a combination between a correct and an incorrect configuration of the values: "deflate;q=1, gzip;q=NOT_A_NUMBER". In this case, deflate will be validated, so the response will be compressed and a Content-Encoded header with the value of deflate is expected.

**_Regarding the Vary header - Since the server considers the Accept-Encoding header when determining whether to compress or not, a Vary header with the value of "Accept-Encoding" should be added to the response. If a Vary header already existed, the server should append "Accept-Encoding" to the value of the existing Vary header._**

**Test 7: testVaryHeader** - Three requests will be sent to a server configured to enable compression. 

The first request will send an Accept-Encoding header with the value of deflate. The response headers will be verified by the test to obtain the value for the Vary header. The Vary header's value is expected to be exactly "Accept-Encoding". 

A second request is sent over, including the same Accept-Encoding header with the value of deflate. However, an additional servlet-specific request header, TestCondition, is added with a value of "Vary". This will tell the servlet to create a Vary header with the value of "test". Instead of creating a new "Vary" header, the server should see the Vary header already contains a value and, instead, append the "Accept-Encoding" value to the header.  As such, the test evaluates that the "Vary" header for this response matches "test, Accept-Encoding". 

Finally, a third request will be sent changing the servlet-specific request header, TestCondition, to have a value of "testContentEncoding". The application will use this to set the Vary header with a value of "Accept-Encoding". The server should see this header's value already has "Accept-Encoding" and not try to modify it. In this case, the test evaluates that the Vary header for this response matches "Accept-Encoding" exactly. 

**_Regarding Compliance - The Accept-Encoding header is not the factor to consider for whether or not the server should attempt compressing the response. In cases where the content-length is known, the server should not attempt compressing responses whose size is less than 2048 bytes. Additionally, it should only attempt compressing payloads whose Content-Encoding is a type that is both present in the include and not defined by the exclude "types" lists. These lists are defined as an attribute, named "types", in the <compression> element. By default, this list is set to "text/*, application/javascript"._**

**Test 8: testCompressionSizeCompliance** - Two requests are sent to a server configured for compression. Both requests send an Accept-Encoding header with a value of "deflate". 

The first request contains a servlet-specific request header, TestCondition, with a value of "smallSize". This will tell the servlet to define the Content-Length header with a value of "35" bytes. Consequently, the server should not attempt to compress the response. The test will then verify that the response is not compressed. 

The second request contains a servlet-specific request header, TestCondition, with a value of "regularSize". This will tell the servlet to define the Content-Length header with a value of "2235" bytes. Since the value is larger than 2048, the server is expected to compress the response. The test will then verify that the response is compressed using the "deflate" Content-Encoding.

**Test 9: testCompressionTypesOptions** - Throughout other tests in the bucket, the application will set a Content-Type of "text/plain". Since the default "types" configuration for a server configured for compression is "text/*, application/javascript", this type is compliant and would allow the server to compress the response if all other conditions are valid. This test, however, will modify this. This test will modify the types attribute to be "+test, -text/plain" which will modify the types included and excluded sets. The resulting sets should be: 
Include - "text/*, application/javascript, test"
Exclude - "text/plain"

Both of the requests sent by this test will set the Accept-Encoding header to "deflate".

The first request will set an application-specific header, TestCondition, with a value of "testContentType". This will tell the application to set the Content-Type of the response with a value of "test". Since the configuration added "test" to the list of included content types, and it is not present in the exclude list, the server is expected to compress the response. The test will verify that the response is compressed using the deflate encoding. 

The second request will set an application-specific header, TestCondition, with a value of "regularSize". This will tell the application to set both a Content-Length with a value larger than 2048 and a Content-Type of "text/plain". However, the server is expected to not attempt compression since this type has been added to the include list.  Consequently, the test will verify that the response is not compressed. 

**Test 10: testCompressionServerPrefAlgorithm** - This test will set the serverPreferredAlgorithm attribute on the <compression> configuration to a value of "deflate". This will be the compression algorithm chosen by the server as long as the client accepts it, specified through the Accept-Encoding header with a quality value larger than 0.  This test will send three requests. 

The first request will contain an Accept-Encoding header containing the value of "deflate;q=0.5, gzip". Since "deflate" is set as the preferred algorithm, it should be chosen for compression by the server, regardless of its quality value being smaller than gzip. The test will verify that the response is compressed with the deflate algorithm. 

The second request will contain an Accept-Encoding header containing the value of "identity; q=0.5, gzip". Since "deflate" is not accepted by the client, the server should compress using the highest compression algorithm accepted by the client. As such, the test will verify that the response is compressed using gzip compression. 

The third request will contain an Accept-Encoding header containing the value of "deflate, gzip". Typically, in the case of ties among quality values, gzip would be favored. However, since "deflate" is set to be the algorithm of preference, the test will verify that the response is compressed using the deflate compression. 

**Test 11: testCompressionEncodedServlet** - This test will verify that the server does not attempt compressing a response that has already been compressed by the application. A request is sent over to a server configured for compression that includes an Accept-Encoding header with the value of "gzip" and a servlet-specific header, TestCondition, with the value of "testContentEncoding". This will signal the servlet to set a Content-Encoding header with the value of "gzip". Since the response will contain a Content-Encoding header, the server should not attempt compressing the payload. As such, the test verifies that the response contains a Content-Encoding header set to "gzip" and that the default payload message matches the expected plaintext value. 

**Test 12: testCompressionRefConfig** - This test will set the compression element outside of the <httpEndpoint> and use a reference ID within the <httpEndpoint> to enable compression on it. It sends a single request with an Accept-Encoding header set to deflate to verify that the response is indeed compressed with this alternate configuration file.

**Comment by pnicolucci** [comment]
Test Confidence: 5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Comment by dave-waddling** [comment]
Hi @pnicolucci,

Thanks for completing the Feature Test Summary!

Regarding Test 3 (testQValueRange): You describe using Q values with 3 decimal places but according to the UFO (slide 33) "Quality values specified in the Accept-Encoding header must be float numbers ranging from 0 to 1 with a maximum of two decimal  spaces". Please can you confirm that the correct number of decimal places is being used in the test/implementation of this feature?

Regarding Test 13 (testCompressionRefConfig): I'm assuming that something's eaten the tag `<httpEndpoint>` from your text when you write "This test will set the compression element outside of the and use a reference ID within the to enable compression on it." Would you mind just confirming that's what this test is doing or quickly clarify if I'm mistaken?

Apart from the two questions above this is looking good for approval. The test coverage looks great and it's passing cleanly in the SOE.

**Comment by mrsaldana** [comment]
From the RFC regarding quality values: "HTTP/1.1
   applications MUST NOT generate more than three digits after the
   decimal point."

rfc link: https://tools.ietf.org/html/rfc2616#section-3.9 

The test should be addressing the correct amount of digits. 

For Test 13, yes, there's a typo, it should read "This test will set the compression element outside of the httpEndpoint element and use ...". The test simply passes the <compression> element into <httpEndpoint> thru a reference ID. I'll edit the summary above to correct the typo.

**Comment by pnicolucci** [comment]
Let me update the WAD as there is a typo there it should state three vs two decimal places. I'll post here when we're all set and we should be good.

**Comment by dave-waddling** [comment]
Hi @pnicolucci and @mrsaldana,

Thank you both for the quick replies. 

Glad to hear it's the UFO that's incorrect rather than the implementation - once it's updated I'll add the approval.

**Comment by pnicolucci** [comment]
@dave-waddling  I've updated the WAD. Let me know if you need anything else for approval. Thanks!

**Comment by dave-waddling** [comment]
Hi @pnicolucci,

Thanks for updating the UFO, I'll add the approval to the parent epic.
