### ISSUE TITLE
Ability to rename future versions of features

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#9214]
Technology names change which sometimes map onto our public Liberty feature names.  For example the following liberty public features:

jsf-2.2
jsf-2.3
jsfContainer-2.2
jsfContainer-2.3

JSF is likely to be renamed to just Faces.  So for version 2.4 we would have public features:

faces-2.4
facesContainer-2.4

The new faces named features must still be singletons and they cannot be allowed to be configured with the previous jsf named features.

The following must be allowed to work WRT to tolerates when another feature includes one of these features:

```
com.ibm.websphere.appserver.jsf-2.3; ibm.tolerates:="2.2,2.4"
```
and
```
com.ibm.websphere.appserver.faces-2.4; ibm.tolerates:="2.2,2.3"
```

In other words a feature must be able to tolerate versions across the required feature rename.  In the first example a feature prefers jsf-2.3 but can tolerate jsf-2.2 and faces-2.4.  In the second example a feature prefers faces-2.4 but can tolerate jsf-2.2 and jsf-2.3.

The solution that comes to mind is one that involves adding some kind of alternate name metadata to each feature that has a previous and/or future names.  Here the jsf features would have to specify com.ibm.websphere.appserver.faces as their alternate name and the faces feature would have to specify com.ibm.websphere.appserver.jsf as its alternate name.

Both seem needed in cases where a server is minified to only include one of the versions of the renamed feature.  In that case we need to know the alternate name for each incase the previous named feature is only available or if only the future named feature is available.

This will involve enhancing the feature meta-data as well as the Liberty feature resolver.  The feature resolver is used by others outside of the Liberty runtime and such users will need to be aware of the new meta-data if they want to model the feature resolution of the renamed features accurately like the runtime does.

**Comment by NottyCode** [comment]
The design issue currently assumes that we need an alias approach to feature names so we can consider upgrading a feature that depends on a Java EE stack to one that depends on a Jakarta EE 9 stack. However that probably isn't possible because of the package rename which means it is likely that most features that depend on Jakarta EE will not tolerate swapping out Java EE 7/8 with Jakarta EE 9. If that is the case we just need a mechanism to ensure that you can't configure Java EE 7 or 8 and Jakarta EE 9 at the same time. This might be simpler to solve than the current problem statement.

**Comment by dazavala** [comment]
Last meeting, 21jan, we determined that support to rename public features is obviated by the discovery that Liberty will not tolerate any combination of JakartaEE9 and JavaEE features. Also, we would investigate the runtime and javaeeCompatibility feature model and devise a solution to reject feature configurations that include JakartaEE9 and JavaEE features, and to emit a serviceable error message for incompatible enterprise feature conflicts.

The following is a general solution to reject unsupported combinations of enterprise features, including any combination of JakartaEE9 and JavaEE features. This solution easily narrows to strictly JakartaEE9+JavaEE configurations. I think we can use this opportunity to improve the JavaEE solution, which rejects unsupported JavaEE feature combinations and emits the generic singleton toleration conflict message, CWWKF0033E. When used for incompatible enterprise feature conflicts the message indicates symbolic names for private (internal) features and is not immediately understandable.

**1 - Add a new message specific to incompatible enterprise feature combinations.** Message content will agree with external documentation. 

ENTERPRISE_CONFLICT_FEATURE_ERROR=CWWKF0043E: The features {e.g. jsf-2.3} and {e.g. faces-2.4} cannot be loaded at the same time. The configured feature {jsf-2.3} of {e.g. Java EE 8} is incompatible with the configured feature {faces-2.4} of {e.g. Jakarta EE 9}. Your configuration is not supported; update server.xml to remove the incompatible features.
ENTERPISE_CONFLICT_FEATURE_ERROR.explanation=The server configuration contains an incompatible combination of features that support the Jakarta EE or Java EE programming models. This conflict can happen if the two incompatible features are configured directly in the server configuration. Or, if the configured features include different versions of a feature that are incompatible.
ENTERPISE_CONFLICT_FEATURE_ERROR.useraction=Try to specify a compatible version of the configured features that caused the conflict in the server.xml. If no other versions are available, then the configured features are incompatible with each other and cannot be configured at the same time. Features that support the Jakarta EE 9 programming model are incompatible with features that support Java EE. If the error indicates Jakarta EE 9, then ensure that the server.xml specifies features supporting Jakarta EE 9 or Java EE, but not both.

Q: Is this message still too general. I think so, and we can provide a message specific to JakartaEE<=9+JavaEE compatibility, and another for JavaEE<=8 compatibility.
Q: Do we consider Jakarta EE 8 anywhere?

**2 - Modify the enterprise compatibility feature model.**

**2.a - Add private, singleton feature enterpriseCompatible-9.0.**
**2.b - Rename javaeeCompatible-x.0 features to enterpriseCompatible-x.0 for x in {6..8}.** This was suggested in the last meeting.
**2.c - Enable feature alias support for private features (internals), only**. The private alias enables us to modify metadata in the enterpriseCompatibility features, only, and eliminates the requirement to modify the Subsystem-Content attribute of any pre-JakartaEE9 feature.
**2.d - Set the `WLP-SymbolicName-Alias` to the previous symbolicName within all renamed javaeeCompatibility features.**
**2.e - Set the `Subsystem-Name` attribute to the platform name -- "Java EE 8",  "Jakarta EE 9", etc. -- for all enterprise compatibility features.** This change enables the feature manager to emit messages containing platform name rather than the symbolicName of enterpriseCompatibility features. Note that Subsystem-Name can be localized.
**2.f - Declare feature enterpriseCompatible-9.0 in the `Susbsystem-Content` of every JakartaEE9 feature.**

**3 - Modify FeatureManager#reportErrors() to identify the toleration conflict involving incompatible enterprise features and emit the new message.**

**Comment by dazavala** [comment]
The team voted yes on "Option 2" with agreement that we change feature name enterpriseCompatible change to **eeCompatible**. Also, the server should identify two types of enterprise conflicts and emit messages that describe either (1) the restriction about combining JakartaEE[9..x] and JavaEE[6..8] features along with advice to configure server.xml with features compatible with one platform or the other, but not both; or (2) a general message to configure server.xml with compatible features, which would apply to conflicts involving JavaEE[6..8] features XOR JakartaEE[9..x] features.

Additional concerns:

- Investigate feasibility of adding feature configuration suggestion(s) to conflict message(s).
- Document restriction about configuring JakartaEE9 and JavaEE features at `https://openliberty.io/docs/ref/feature/` under heading `Combining features` 
- Investigate potential documentation and product changes regarding **JakartaEE8** support
