### ISSUE TITLE
Fix code to not strip slashes from a keyring

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#9329]
Slashes are being stripped form a the keyring.  The code needs to be modified to take this path as the keyring is not file based.

**Comment by dburdine** [comment]
Changes in 19.0.0.9 may break SAFKeyring access. Here are a couple of symptoms. See circumvention at bottom.

"java.io.IOException: Error in Ring_name length or RACF_userid length com.ibm.ws.ssl.config.WSKeyStore$1 do_getKeyStore"

ERROR CWPKI0033E: The keystore located at safkeyringhybrid:/mySAF.Keyring did not load because of the following error: Errors encountered loading keyring. Keyring could not be loaded as a JCECCARACFKS or JCERACFKS keystore.

CIRCUMVENTION:
The issue is any <keyStore> element with a id=defaultKeyStore may break. Instead utilize an <ssl> element to point to the <keyStore> element that has an id other than "defaultKeyStore".

<ssl id="defaultSSLConfig" keyStoreRef="myKeyStore" />

<keyStore id="myKeyStore" location="safkeyring:///MYKEYRING" type="JCERACFKS" password="password" fileBased="false" readOnly="true" />
