### ISSUE TITLE
openapi-3.1 feature not honoring the: openapi publicURL configuration

### ISSUE THREAD

**Issue by blindenvy** [OpenLiberty/open-liberty#9345]
WebSphere Application Server 19.0.0.9 (wlp-1.0.32.cl190920190905-0148) does not seem to honor the openapi-3.1 feature setting: `<openapi publicURL="myAPI" />`. When starting the server the openapi is still being deployted to `api` instead of `myAPI`.

**Comment by arturdzm** [comment]
This is expected behaviour, as `openapi-3.1` switched to using mpOpenAPI-1.0 as a base and as per MicroProfile OpenAPI spec the additional configuration is done through MicroProfile Config and
`mp.openapi.extensions.*` property

To set the publicUrl  use `mp.openapi.extensions.liberty.public.url=myAPI`
SInce this is server wide configuration it is applied either through system properties or jvm.options file

**Comment by blindenvy** [comment]
Thank you for the clarification, I was looking at documentation for `openapi-3.0`. I can confirm that adding this property to the `jvm.options` file is working properly.
