### ISSUE TITLE
Performance: Daytrader7/Ddaytrader8 see 3-5% performance regression. 

### ISSUE THREAD

**Issue by sameerlodhi** [OpenLiberty/open-liberty#9564]
It is between cl191120191025-0810 and cl191120191028-0300 build. Regression is seeing on Daytrader7/Daytrader8 on EJB mode.

https://github.com/OpenLiberty/sample.daytrader8

**Comment by jhanders34** [comment]
#regression

**Comment by jhanders34** [comment]
The performance team believes that this is caused by the changes in https://bugs.eclipse.org/bugs/show_bug.cgi?id=542491.  We believe setting eclipselink.jdbc.force-bind-parameters to true in the persistence.xml will allow things to run the old way.  There are reasons for the change done in the bug related to SQL injection attacks.  As such the default behavior to be secure is preferred.

**Comment by jgrassel** [comment]
As stated previously, this performance regression was caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=542491, which changed parameter binding behavior with DB2.  Previously, generated SQL included literal values as part of the SQL; however this could be considered a possible avenue for a SQL Injection Attack, so the SQL generation was updated to use prepared statement parameters even for literal values.  However, this came at a cost as cited in this issue's title.

Customer Impact: Presently, improved security (improved protection against SQL injection attacks) at the cost of a few % points of performance.

Workaround: Using the "eclipselink.jdbc.force-bind-parameters" = "true" property should restore the old processing.

**Comment by dazey3** [comment]
`eclipselink.jdbc.force-bind-parameters` (https://bugs.eclipse.org/bugs/show_bug.cgi?id=542491) was added to EclipseLink in order to allow users to force EclipseLink to bind all parameters for DB2. Binding parameters on DB2 was disabled by default for all functions. 
However, with binding enabled, EclipseLink was also binding literals into the query. This caused the following exception to be thrown:
```
Internal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: The statement was not processed because the statement contains an invalid use of one of the following: an untyped parameter marker
```
I then disabled literal binding on DB2. I think the issue may be the use of CriteriaBuilder in the application since I did not originally test with this, only JPQL queries. I will write up some tests with CriteriaBuilder to see if I can reproduce this issue locally. 

Also, the query isn't failing, the SQL in the statement is different, but the query result should be unchanged.

**Comment by marikaj123** [comment]
@jgrassel What is the status for fixing the defect?

**Comment by jdmcclur** [comment]
Will, were you able to look at the CriteriaBuilder?

**Comment by jhanders34** [comment]
To give some details about the resolution of this bug:

The possible causes of this bug earlier in this issue were incorrect.  When this regression started happening it was actually related to a change in EclipseLink where the default value of `shouldBindLiterals` was changed to `false`.  When the setting is true, EclipseLink converts non prepared statement to prepared statements.  To resolve the regression, there were two options.  One option was to set the property to true in the persistence.xml.  An example is shown below.  The other option was to update the CriteriaBuilder usage in the application to use parameters to instruct JPA to use a prepared statement with the parameters that were specified.  We chose to use the second option because it demonstrates best practice code and uses the API correctly to configure a prepared statement.

```
<properties>
    <property name="eclipselink.target-database-properties" value="shouldBindLiterals=true"/>
</properties>
````
