### ISSUE TITLE
Reactive Messaging using Kafka resulting in duplicate messages

### ISSUE THREAD

**Issue by HasseNasse** [OpenLiberty/open-liberty#9808]
**Describe the bug**
I have a simple application using openliberty 19.0.0.11 and reactive messaging using the liberty-kafka connector. A simple @Incoming and @Outgoing seems to be producing every emission twice. Even if I dont connect to a Kafka Broker.

**Steps to Reproduce**
https://github.com/HasseNasse/NotificationService

**Expected behavior**
Non-duplicate messages

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.11/19.0.0.9
 - Java Version: Java 11
 - server.xml configuration: See the liberty folder in the above repo

**Additional context**
A similar problem could be found here, although for quarkus and AMQP. https://github.com/smallrye/smallrye-reactive-messaging/issues/123

**Comment by Azquelt** [comment]
Hi, the reason that you're getting messages coming out twice is that you've included this in your pom.xml:

```
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-reactive-messaging-kafka</artifactId>
            <version>1.0.8</version>
        </dependency>
```

This has pulled in `smallrye-reactive-messaging-provider` as a dependency which means you have two implementations of reactive messaging running (the smallrye provider in your app and the implementation in open liberty) which is why you see messages in the logs twice.

As you're not actually using the smallrye kafka connector (at least, your configuration uses the one built into open liberty) you can remove that dependency and add just the reactive messaging api as a provided dependency:

```
        <dependency>
            <groupId>org.eclipse.microprofile.reactive.messaging</groupId>
            <artifactId>microprofile-reactive-messaging-api</artifactId>
            <version>1.0</version>
            <scope>provided</scope>
        </dependency>
```

Note however, that open-liberty doesn't support `@Channel` which you're using in `NotificationResource` as it's not yet in the reactive messaging specification.

**Comment by HasseNasse** [comment]
I see, that I should have noticed..
Am i however correctly assuming that I can use smallrye as a implementation for reactive messaging by including 
```
<dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-reactive-messaging-kafka</artifactId>
            <version>1.0.8</version>
</dependency>```
 
and disabling the `<feature>mpReactiveMessaging-1.0</feature>` feature, Or might this have other consequences?

**Comment by HasseNasse** [comment]
Got my application to work by using smallrye to be able to inject a channel into a CDI bean and then emit it as Server sent events to a UI. Topics are fead through a kafka topic and it seems to be working fine now.

Thanks for the help.

**Comment by Azquelt** [comment]
> Am i however correctly assuming that I can use smallrye as a implementation for reactive messaging by including [snip] and disabling the `<feature>mpReactiveMessaging-1.0</feature>` feature?
> 
> Or is there a specific reasoning behind wanting to use the container native implementation?

Yes, that should work. You may potentially hit issues interacting with some JavaEE features if the smallrye implementation creates its own (non-managed) threads.
