### ISSUE TITLE
Add ability to enable JNDI trace to ldapRegistry-3.0

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#9902]
It would be useful if we could enable a dump of the incoming and outgoing LDAP ASN.1 BER packets when using ldapRegsitry-3.0 to aid in resolving customer issues.

Add a new configuration element that would allow us to configure the `com.sun.jndi.ldap.trace.ber` environment property passed into the JNDI context.

The config would probably be something similar to the following, where the user points to a file. We probably also should support the use of "System.out".

`<ldapRegistry ... jndiBerOutputFile="${server.config.dir}/logs/ber-dump.log" ... />`

The code would look something like this:

```
if (berDumpEnabled) {
   env.put("com.sun.jndi.ldap.trace.ber", <FileOutputStream | System.out>);
}
```

**Comment by kristip17** [comment]
Working on a case right now where this would be useful.

**Comment by jvanhill** [comment]
@agiridharan - Could you update this issue to show how you actually implemented it?

**Comment by agiridharan** [comment]
Added an internal config variable "JndiOutputEnabled". This variable can be set in Ldap Registry to a boolean value (default is false). When the variable is set to true, this property will write the incoming LDAP ASN.1 BER packets to system.out. The packets can be use in the trace.log file. This config variable is set to internal, since the trace.log file output will be massive, so we don't want customers to use it regularly.
