### ISSUE TITLE
accessTokenSupported=true and a good access_token results in clientId parm missing msg with LibertyOP

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#9928]
I have a config with accessTokenSupported=true and I pass a good access_token.  I get a failure claiming that the clientId is missing.  I it shouldn't be required.

**Comment by ayoho** [comment]
Looks like my "fix" to support the accessTokenSupported=true case is still incomplete. The `OAuthLoginFlow` class in question goes through this logic:
```Java
TAIResult handleOAuthRequest(HttpServletRequest request, HttpServletResponse response, SocialLoginConfig clientConfig) throws WebTrustAssociationFailedException {
    if (SocialUtil.useAccessTokenFromRequest(clientConfig)) {
        TAIResult result = handleAccessTokenFlow(request, response, clientConfig);
        if (result != null && clientConfig.isAccessTokenRequired()) {
            return result;
        }
    }
    String code = webUtils.getAndClearCookie(request, response, ClientConstants.COOKIE_NAME_STATE_KEY);
    if (code == null) {
        return handleRedirectToServer(request, response, clientConfig);
    } else {
        return handleAuthorizationCode(request, response, code, clientConfig);
    }
}
```
The trace shows that the `handleAccessTokenFlow()` call is returning back a non-null `TAIResult` object. The processing of the access token that is provided actually succeeds, which means that the `TAIResult` object that's being returned would be the result of
```Java
TAIResult.create(HttpServletResponse.SC_OK, username, subject);
```
So a good result is being returned, but because of the `&& clientConfig.isAccessTokenRequired()` condition I had added, we're not returning that result even though we should. So processing goes forward and the code attempts to go through the normal authorization code flow.

I'll make a change to check the status of the `TAIResult` object in addition to the `accessTokenRequired` attribute value to determine when to return that `TAIResult` object.

**Comment by c00crane** [comment]
This issue has been fixed.  Tests using accessTokenSupported=true and passing a good token all now work (multiple tests for same original issue each with various values passed/not passed as the LTPA token)
