### ISSUE TITLE
Unable to resolve SessionScoped bean in PhaseListener after forward

### ISSUE THREAD

**Issue by stevendegroote** [OpenLiberty/open-liberty#9929]
**Describe the bug**
In a regular Phaselistener, as of JSF 2.2, it is usually possible to \@Inject a bean. In my case, I'm injecting a SessionScoped bean, which works well in normal conditions.

However, if an exception occurs, and the PhaseListener is called again for the error page, then the injection point fails. This should not happen.

`org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped
     at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)
     at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
     at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:164)
     at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
     at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
     at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
     at org.primefaces.test.WebSession$Proxy$_$$_WeldClientProxy.getName(Unknown Source)
     at org.primefaces.test.LoginController.afterPhase(LoginController.java:26)
     at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersAfter(PhaseListenerManager.java:117)
     at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:210)
     at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
     at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
     at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
     at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
     at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56) `

**Steps to Reproduce**
 - Download vanilla openliberty webprofile
 - Start defaultServer
 - Dropin the attached application
 - Navigate to home of the application.

**Expected behavior**
The output should be the error page (in the reprocase, something like "ERROR ERROR" (due to an error in test.xhtml), but instead, a stacktrace about the missing SessionScope pops up, as that occurred in the error page.

**Diagnostic information:**
 - OpenLiberty Version: openliberty-webProfile8-19.0.0.11
 - Java Version: Java(TM) SE Runtime Environment (1.8.0_212-b10)

**Additional context**
Deploying the attached war on Wildlfy 18 correctly renders the error.xhtml .

[session-inject-fail-with-sources.zip](https://github.com/OpenLiberty/open-liberty/files/3886421/session-inject-fail-with-sources.zip)

**Comment by pnicolucci** [comment]
MyFaces JIRA link: https://issues.apache.org/jira/browse/MYFACES-4335

**Comment by volosied** [comment]
Hi @stevendegroote ,

We apologize for the severely delayed response to this issue. I have spent time investigating this, and I have been unable to reproduce the issue with the provided steps and code. 

I've tested on various liberty version and jsf versions, and also in jetty.  In all cases, the test.xhtml was rendered without errors and the websession object was injected properly.  

I'd be happy to look further into this issue, but could you provide additional information for us?   
-  We would appreciate any server.xml configurations you've used.
-  Any logs (messages.log or trace.log)
-  Could you also ensure the issue is still reproducible with the provided code? 
-  What is the specific error in the test.xhtml? 

Thanks!

**Comment by stevendegroote** [comment]
Hello again,
I'm very sorry, but my original repro seems to be incorrect.

Please find attached a more problematic case.

The homepage (test.xhtml) has a syntax error (it's an EL error, which is silently ignored on Wildfly), so then the server tries to render error.xhtml, where this happens:
`WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped`

The same problem occurs on WAS9, but not on JBoss7 and Wildfly18

[session-inject-fail-with-sources-2.zip](https://github.com/OpenLiberty/open-liberty/files/4747661/session-inject-fail-with-sources-2.zip)

**Comment by volosied** [comment]
We'll take a look and see what we can discover. Thank you for providing an application for us!

**Comment by volosied** [comment]
Hi again @stevendegroote ,

I've finished my investigation, and the issue is not with MyFaces or CDI, but with webcontainer.  There is an issue with the timing of when the destroy listeners are called due to the EL Exception. However, thanks to @wtlucy, he pointed out a property that will address this ContextNotActiveException.  Please add the following to your server.xml: 
`<webContainer deferServletRequestListenerDestroyOnError="true" />`

I've tested out that property, and the error page is displayed when testing with your updated app. Let us know if that property also works for you. Thank you. 

More can be read about it here: 
https://www.ibm.com/support/pages/apar/PI26908
https://stackoverflow.com/questions/23135373/omnifaces-fullajaxexceptionhandler-error-page-generates-contextnotactiveexce

**Comment by stevendegroote** [comment]
Ok thanks, I'll try it out!

However, may I ask why this debug should be "enabled" with a property? In what case would you want to keep the erroneous behaviour? Or in other words, what are the side effects of setting this property?

**Comment by wtlucy** [comment]
There should not be any side effects caused by this property.  The only reason that this more-correct behavior is not the default is because WebSphere has historically been very strict with preserving existing behavior, so that customers can take new fixpacks (WebSphere updates) without seeing any behavior changes.  That is, apps might have been depending on the incorrect behavior.  Ideally this `deferServletRequestListenerDestroyOnError` would have been enabled by default with a new Servlet version - we'll have to consider doing that for Servlet 5.

**Comment by stevendegroote** [comment]
I can confirm this setting solved my issue! Thanks

**Comment by berghanalista** [comment]
If you are using sessionscoped from javax.enterprise.context, you should inject your ben into the class that implements PhaseListener. Remember, you started using sessionscoped from the javax.enterprise.context package and not from the deprecated jsf. Then you must do so @Inject Authentication authentication and search for the objects that are in it. Then just do your logic.
Ex:
public class PhaseLife implements PhaseListener {

private static final long serialVersionUID = 1L;

@Inject
private Authentication authentication;

@Override
public void afterPhase (PhaseEvent event) {

FacesContext context = event.getFacesContext ();
String paginaAtual = context.getViewRoot (). GetViewId ();

boolean ehPaginaDeLogin = (paginaAtual.lastIndexOf ("login.xhtml")> -1);



if (! ehPaginaDeLogin && authenticationacao.getServidorLogado (). getMatricula () == null) {
NavigationHandler nh = context.getApplication (). GetNavigationHandler ();
nh.handleNavigation (context, null, "login? faces-redirect = true");

}

}

@Override
public void beforePhase (PhaseEvent event) {

}

@Override
public PhaseId getPhaseId () {
return PhaseId.RESTORE_VIEW;
}

}

Hope this helps
